### ISSUE TITLE
Rename retry to retryOnError

### ISSUE THREAD

**Issue by davidbjames** [ReactiveX/RxSwift#1008]
**Rename retry to retryOnError**:

Currently the ReactiveX standard supports a `retry` operator which retries the sequence on error. Compared to most other operators, `retry` does not read very well. On it's own, it implies that the Observable will _always_ retry whenever a next event reaches the operator. This of course is not what we want. It would make more sense to indicate that `retry` only fires on Error condition. Hence, I am suggesting in RxSwift that we rename `retry` to `retryOnError` to make this clear.

I understand that exceptions in the ReactiveX standard operator names are sometimes used (and documented on ReactiveX.io) and that these decisions are based on making Rx more logical/easier to reason about. I am suggesting that RxSwift take the lead in renaming `retry` to something that is easier to reason about by naming it `retryOnError`.

**Comment by kzaher** [comment]
Hi @davidbjames ,

I guess I'm not a native english speaker but it doesn't seem to me that we have issue with `retry` naming.

`retry` implies that something should be tried again because an error occurred on previous try. I'm afraid that if we were to go this road we would need to rename all of the operators.

`map` -> `mapElements`
`filter` -> `filterElements`
...

I'm not convinced that would improve usability. 

When one is using Rx it is important to think about it in terms of observable sequences and not particular events.

¯\\\_(ツ)\_/¯

**Comment by dangthaison91** [comment]
>On it's own, it implies that the Observable will always retry whenever a next event reaches the operator

I think it should be `repeat`, `retry` told me that there are somethings wrong then I need to retry.

**Comment by davidbjames** [comment]
@kzaher Thank you for your feedback. 

Several operators are idiomatic. That's OK. We don't need to rename them. `takeWhile` doesn't need to be `takeWhilePredicateIsTrue`. `takeWhile` is enough to make the mental association. `flatMap` and `debounce` have generally accepted meanings, even though the names themselves are not obvious. `map` and `filter` are OK too, as-is.

I'm thinking how all these read declaratively. 

`retry` is not the same. It stands out as an imperative command: "retry this sequence regardless". This may be confusing for beginners. 

What it really means is "retry on error".

**Comment by scotteg** [comment]
I think `retry` is the most appropriate name. However, I would consider making the overload `retry(_:)` that takes a `maxAttemptCount` value to be renamed to `maxAttempts` and _not_ be omitted at the call site, i.e., `retry(maxAttempts:)`, because it is syntactically important to indicate to the caller that it is actually the _total_ number of attempts including the first one, i.e., `retry(2)` will only retry _once_. `retry(maxAttempts: 2)` better conveys what is actually going to happen. @kzaher, I'd be glad to implement this with a deprecation warning, just lmk

**Comment by scotteg** [comment]
I feel that `retry` is the appropriate name. However, I would change the parameter name in the overload `retry(_:maxAttemptCount:)` and include the parameter name externally at the call site: `retry(maxAttempts:)`. This would better convey what's actually happening, i.e., the parameter value is the _total_ number of attempts. For example, to retry _once_ you would pass `2`. @kzaher I'd be glad to implement this with a deprecation warning if you'd like, just lmk.

**Comment by kzaher** [comment]
Hi guys,

@davidbjames I definitely trust you when you say that you were confused by the current name and I'm sorry because of that. Meaning of certain words definitely depends on one's subjective previous experiences in life and common contexts in which a certain word was used.

The real question is how often would people be confused when they see. I'm not sure I have those statistics so I've done the simplest thing that I can.

I've googled [retry](https://www.google.hr/search?q=retry&oq=retry&aqs=chrome.0.69i59j69i61l3j0l2.640j0j7&sourceid=chrome&ie=UTF-8) and it seems to me that it's usually mentioned in context of try again after failure.

It also seems to me that other implementations are using the same name.

If we wanted to name this operator most accurately we would have to name it `resubscribeOnError` IMHO, but I bet nobody would understand what that operator does.

I'm assuming that the reason why it was named `retry` was exactly because it should be easy to deduce is what scenarios is this operator meant to be used.

@scotteg I think naming it `retry(maxAttempts:)` would make sense and improve a bit current interface, but I think that we should wait with that change until RxSwift 4.0. Renaming it right now wouldn't gain us much since this form was here for past 2 years, but I agree it could be improved.

**Comment by davidbjames** [comment]
Thanks for the explanation, and I agree the semantics of `retry` implying failure. 

The confusion was in how I saw events trickling down the operator chain. Order is important. Adding `retry` at a certain point in the chain, seemed to "declare" something unintuitive to me. `resubscribeOnError` or `retryOnError` would have been more intuitive IMO, as`catchError` is intuitive.

I'll go ahead and close this issue for now. Thanks.
