### ISSUE TITLE
Looking for more documentation on how to setup tableview/collection view with rxswift. It seems that it rxswift doesn't play nice with storyboard/xib together.

### ISSUE THREAD

**Issue by rlam3** [ReactiveX/RxSwift#1046]
Looking for more documentation on how to setup tableview/collection view with rxswift. It seems that it rxswift doesn't play nice with storyboard/xib together. Would love to see more documentation on how to use custom tableview/collectionview cells in storyboard with rxswift when talking to backend.

I've been getting similar issues to the following when trying to customize cells and storyboard.

Or maybe somebody could point out why this is happening...? Is rxswift overwriting xib/storyboard? 

```
Hint: Maybe delegate was already set in xib or storyboard and now it's being overwritten in code.
```

Thanks!

**Comment by kzaher** [comment]
Hi @rlam3 ,

It's warning you that you are using storyboard to set data source or delegate but you are also using RxCocoa and overwriting those same delegates and data sources.

Just don't set them in storyboards and by using RxCocoa.

If you want to use RxCocoa with additional custom delegates, you need to use `rx.setDelegate` and `rx.setDataSource` instead of just setting `delegate` and `dataSource`.

**Comment by rlam3** [comment]
@kzaher Thanks for pointing this out for me. But I think I need a bit more sample code before I fully grasp what Rx can do here. Would you mind sharing a gist or a sample project you may have worked on that uses this specific way? 

Or vice versa... say I did set the datasource and delegate on the storyboardy. is there a way for rx to play with storyboard that way? Thanks!

**Comment by kzaher** [comment]
There is a couple of examples in this repo.

https://github.com/ReactiveX/RxSwift/tree/master/RxExample/RxExample/Examples | grep "TableView"

> ... say I did set the datasource and delegate on the storyboardy. is there a way for rx to play with storyboard that way? Thanks!

Unfortunately not as far as I can tell. There can be only one delegate, dataSource per table/collection view.

We've enabled using two delegates (Rx + custom one) by using objc message forwarding mechanism, but that requires setting setting delegates/data sources through Rx.

Yes, we could have made it transparent so we just set existing delegate/data source as forwarding delegate by just automagically call `rx.setDelegate/DataSource`, but I really dislike automagical solutions.

That would give people impression that they can just normally set `delegate/dataSource` without invalidating Rx integrations since it would work in some cases.

The summary is:
* theoretically it can be done
* we've opted in for boring and more tedious but **safer** solution
