### ISSUE TITLE
Is it really necessary to have RxBlocking as a 3rd framework?

### ISSUE THREAD

**Issue by lfaoro** [ReactiveX/RxSwift#109]
RxBlocking contains only 1 file with an RxSwift dependency and ~150 lines of code. Is it really necessary to have it as a separate framework?

I believe the goal is to make sure Rx users don't use blocking in their code and link RxBlocking just to their test target but I'm wondering...

Is it really worth it to increase the complexity of the framework instead of just displaying a warning to the users on ⌥-click?

**Comment by m00sey** [comment]
RxBlocking is designed to ease unit tests, and not meant for production code, hence it is a separate framework.

**Comment by DanielAsher** [comment]
Xcode 6.4 refused to run an iOS app with a `LaunchServicesError error 0.` when I add `RxBlocking` as an embedded library. Adding to the test target solved the problem. Potential risk, then, in including it in a production app. Perhaps like `Quick` and `Nimble`

**Comment by kzaher** [comment]
Hi @lfaoro,
IMHO, short answer is that it is :)

I don't think that number of lines of code is a good argument to determine should something be separated into modules.

It was done that way because:
* you should never use it with RxSwift outside of testing environment
* it is extremely dangerous because it can cause deadlocks

I'm working on this framework primarily for myself to use, and I would be grateful if I could eliminate certain class of accidental errors during CRs just by looking at does it use `import RxBlocking`.

**Comment by kzaher** [comment]
Closing this one :)
