### ISSUE TITLE
The Unit documentation conflates physical unit with measurement

### ISSUE THREAD

**Issue by blagh** [ReactiveX/RxSwift#1092]
Hey all, I'm just starting with RxSwift so apologies if I'm misunderstanding but: the documentation about how real-world units work is just wrong. It tries to make a distinction between a "measurement" unit and a "physical" unit but nowhere can I find definitions that back that up. 

A unit does not have a number attached -- in fact I would find a unit more directly analogous to a type, uninstantiated. A meter, a gram, a litre -- they are [a reference quantity of distance or mass or volume][2]. Even a unit of soldiers in an army describes a _particular_ quantity of soldiers (although it may vary by the particular army), and 15 units of soldiers is not the same thing as a unit.

  [2]: https://www.google.ca/search?q=unit+definition

When you add a number to a unit, what you are describing is a _measurement_ - 56 grams, or 332 kilometers. An edge case, 1 litre, is a measurement that happens to describe the same quantity as the reference unit. You've instantiated how much of the thing there actually is, to carry the metaphor further.

When you perform operations with measurements (e.g. 72 meters / 12 seconds), you first calculate the quantity portion (72 / 12), then you calculate the resulting unit (m/s). The result, is another _measurement_, 6 m/s. Note that the documentation currently uses "unit" both to describe a unit with a quantity, _and_ a unit of measurement on its own.

If you really wanted to, and it were convenient for some reason, you can define units based on other units. For example, [inches are defined to be exactly 2.56 centimeters long][1].  There are also convenience units for orders of magnitude (e.g. a kilometer - 1000 meters, a millilitre - 1/1000th of a litre). But even so, an inch is the unit, and if you are talking about any quantity of inches then it is a _measurement_.

  [1]: https://en.wikipedia.org/wiki/Inch

I don't need to call out Unit as an incorrect abstraction for RxSwift, because I'm honestly not familiar enough to make that call. But the way things are currently documented is a big obstacle for me, trying to understand the terminology.

**Level of RxSwift knowledge**: just starting

**Comment by kzaher** [comment]
Hi @blagh ,

**disclaimer: Units terminology is for now specific only for RxSwift project. If you are interested in only cross platform terminology, don't use them. I couldn't find any other cross Rx implementation naming conventions to explain property algebras built on top of observable sequences.**

For example RxJava has:
* `Observable` -> 0..N flows, no backpressure
* `Single` ->  a flow of exactly 1 item or an error
* `Completable` -> a flow without items but only a completion or error signal
* `Maybe` -> a flow with no items, exactly one item or an error

RxCocoa has:
* `Driver` -> main scheduler + shareReplayLatestWhileConnected + noErrors
* `Event` (or something like this in next release) -> main scheduler + shareReplayLatestWhileConnected + noErrors

**All of these types are equivalent to a tuple of `Observable` sequence + guarantees of certain properties (unit).** I would call these types units.

I think that documentation could be improved further because I'm assuming a lot of people are potentially confused.

> It tries to make a distinction between a "measurement" unit and a "physical" unit but nowhere can I find definitions that back that up.

I'm not sure I understand you. Maybe my terminology was wrong. When referring to units, I've always meant "measurement" or "physical" units. I think I should probably replace "physical" with "measurement".

Let's use `meter` example.

If I were to model meters in Swift, there are multiple ways how to model this. I think you are referring to this way:

```
let measurement = (3.14, Meter())
```

Measurement is a tuple that contains a real number describing quantity and a Meter describing a unit in which that quantity was measured.

One can also model this in a slightly different way.

Using `NSMeasurement` it would probably look something like

```
Measurement<UnitLength>(value: 3.14, unit: .meters)
```

... which is again in its essence a tuple.

You can also model it this way

```
struct Meter {
    let value
}
```

> A unit does not have a number attached -- in fact I would find a unit more directly analogous to a type, uninstantiated.

In this example, type `Meter` is the unit, and when one instantiates a `Meter` then yes, I would  assume that the term measurement would be probably more appropriate.

Why are units useful? Well, if one performs some calculations and the result unit is unexpected, then there has to be some error in the calculation. Getting the correct unit doesn't prove they got the answer right, but it provides additional level of safety.

That's kind of similar to how compilers work. If compiler is pleased with input source code because all type checks pass, that means that it has done it's due diligence and it will allow you to run your program. That doesn't mean that if compiler gives you green light your program is correct, it just means that if compiler sees an error, your program can't be possibly correct. 

Ok, so why didn't I just say types. There is a set of types and set of operators/operations that enable conversions between those types.

Maybe it's weird to explain it when there is just one `Driver` unit, so I'll add:

`Observable` - no properties are guaranteed (`xs` variable)
`SharedSequenceWithShareReplayLatestWhileConnected` - shareReplayLatestWhileConnected (`a` variable)
`SharedSequenceWithShareReplayLatestWhileConnectedOnMainScheduler` - shareReplayLatestWhileConnected + main scheduler (`b` variable)
`Driver` - shareReplayLatestWhileConnected + main scheduler + noErrors (`c` variable)

Here is an example:

```
let xs: Observable<Int> = // some sequence
let a = xs.shareReplayLatestWhileConnected()
let b = a.observeOn(MainScheduler.instance)
let c = b.catchError(onErrorJustReturn: -1) 
```

We can encode this information in a more type safe way.

```
struct SharedSequenceWithShareReplayLatestWhileConnected<E> {
     let xs: Observable<E>
     init(source: Observable<E>) {
        xs = source.shareReplayLatestWhileConnected()
    }
}

struct SharedSequenceWithShareReplayLatestWhileConnectedOnMainScheduler<E> {
    let xs: Observable<E>
    init(source: SharedSequenceWithShareReplayLatestWhileConnected<E>) {
       xs = source.observeOn(MainScheduler.instance)
    }
}

struct Driver<E> {
    let xs: Observable<E>
    init(source: SharedSequenceWithShareReplayLatestWhileConnectedOnMainScheduler<E>, defaultValue: E) {
        xs = source.catchError(onErrorJustReturn: defaultValue)
    }
}

let xs: Observable<Int> = // some sequence
let a = SharedSequenceWithShareReplayLatestWhileConnected(source: xs)
let b = SharedSequenceWithShareReplayLatestWhileConnectedOnMainScheduler(source: a)
let c = Driver(source: b, defaultValue: -1)
```

**Comment by blagh** [comment]
A unit is a constant -- it doesn't make sense to add a value, and still call it a unit. Perhaps I was slightly mistaken in drawing an analogy with types, but your examples illustrate that there are actually two different concepts.

The tuple-based version is simple, and correct.

And holy flip there is an [NSMeasurement][2], _and_ [NSUnit][1]. Note the properties on each of these classes - NSUnit pretty much only gives you a symbol that is used to represent that particular unit. It's NSMeasurement where you have both a unit _and_ a value.

Your struct example is wrong, unless you want to suggest that a Meter is sometimes a different length depending on the whims of the programmer. This is what that API would suggest to me.

> when one instantiates a Meter then yes, I would assume that the term measurement would be probably more appropriate.

Then, your class should be called Measurement instead. This example, it would be like a Name class that also contains a date of birth field -- you probably want to call it Person instead.

Perhaps a point of confusion: the term "unit of measurement". This still just refers to a unit, a point of reference. A unit is used _for_ measuring; it's not something which is also used to denote a measurement itself. Although it's not commonly used, a "measurement unit" would refer to the same thing - a value without a quantity.

I'm definitely sympathetic to the difficulties of naming, and the challenges in writing documentation. And I understand that you're trying to build a new abstraction on top of the existing Observables. I don't perfectly understand what your code snippet at the bottom of the page is driving at, apologies.

> I think I should probably replace "physical" with "measurement".

You should replace "physical unit" with "measurement", because that is what you are actually describing.

  [1]: https://developer.apple.com/reference/foundation/unit
  [2]: https://developer.apple.com/reference/foundation/nsmeasurement

**Comment by kzaher** [comment]
I've tried to improve documentation in develop branch.

https://github.com/ReactiveX/RxSwift/blob/67f4a960794050cfe8c197311fbccce270ca0de4/Documentation/Units.md

I'm hoping that maybe some parts are more clear now.

> And holy flip there is an NSMeasurement, and NSUnit. Note the properties on each of these classes - NSUnit pretty much only gives you a symbol that is used to represent that particular unit. It's NSMeasurement where you have both a unit and a value.

I think there are multiple ways how one can model this problem depending on desired compile time guarantees. It seems to me that the way Apple has decided to model unit and measurement API is more suitable for converting between measurements of same unit type (meters, centimeters, yards ...) and ease of extensibility while sacrificing compile time safety.

Swift compiler will happily compile this and run this code even though it is invalid:
```
if #available(macOS 10.12, *) {  
    let a = Measurement<Dimension>(value: 3.0, unit: UnitLength.meters)  
    let b = Measurement<Dimension>(value: 3.0, unit: UnitEnergy.calories)  
    let c = a + b  
    print(c) 
} 
```

... while this is exactly the type of mistakes we want to prevent.

> I'm definitely sympathetic to the difficulties of naming, and the challenges in writing documentation. 

I couldn't think of any better analogy then units. If there is some mathematical abstraction that fits it better, I'm all ears. I don't want to be the guy that has worst analogies.

**Comment by blagh** [comment]
Hey there apologies for taking a few days on a response - just making sure my thoughts are clear. I'm interested in digging into exactly what is going on in that Measurement example you've provided, because the result of the addition is not 6 as you might expect if it were just adding the numbers together - it comes out `15.552 m`.

**Comment by kzaher** [comment]
Hi @blagh ,

the whole point of that example is that we want compile time safety that those kinds of mistakes can't happen. 

In that example I've added meters (unit of length) and calories (unit of energy) which doesn't make sense.

Every result other than compile time error is not wanted :)
