### ISSUE TITLE
Issues with `share()` and `shareReplay(_:)`

### ISSUE THREAD

**Issue by fpillet** [ReactiveX/RxSwift#1111]
We've been running some tests in a playground and found some interesting behavior of `share()` and `shareReplay(n)` where n > 1. Let me start with some playground code:

```swift
import RxSwift
import PlaygroundSupport
PlaygroundPage.current.needsIndefiniteExecution = true

let obs : Observable<String> = Observable.create { observer in
	print("observable subscribed to")
	var subscribed = true
	DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
		if subscribed {
			print("observable emit")
			observer.onNext("VALUE")
			observer.onCompleted()
		} else {
			print("observable would emit but observer unsubscribed")
		}
	}
	return Disposables.create {
		print("observable disposed")
		subscribed = false
	}
}

let shared = obs
  .share()
  //.shareReplay(1)
  //.shareReplay(2)
  //.shareReplayLatestWhileConnected()

shared.subscribe(onNext: { value in
	print("* subscription1: \(value)")
}, onCompleted: {
	print("* subscription1 complete")
})

DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
	shared.subscribe(onNext: { value in
		print("* subscription2: \(value)")
	}, onCompleted: {
		print("* subscription2 complete")
	})
}
```

Execute this code in a playground and you'll notice that after the second subscription immediately completes, the source observable is subscribed to and immediately unsubscribed from:

```
observable subscribed to
observable emit
* subscription1: VALUE
* subscription1 complete
observable disposed
* subscription2 complete
observable subscribed to
observable disposed
observable would emit but observer unsubscribed
```

comment out the `.share()` line, uncomment the `.shareReplay(1)` line and you'll see a different behavior:

```
observable subscribed to
observable emit
* subscription1: VALUE
observable disposed
* subscription1 complete
* subscription2: VALUE
* subscription2 complete
```

Which looks more like what we're expecting. Now comment out this line and uncomment the `.shareReplay(2)` line, and you see the strange behavior again:

```
observable subscribed to
observable emit
* subscription1: VALUE
* subscription1 complete
observable disposed
* subscription2: VALUE
* subscription2 complete
observable subscribed to
observable disposed
observable would emit but observer unsubscribed
```

So there's definitely an unstable behavior of `share()` and `shareReplay(_:)` when it comes to re-subscribing to the source observable. In the cases where the source performs significant work, this can have a serious cost.

**Comment by kzaher** [comment]
Hi @fpillet ,

yes, I've noticed that anomaly and like you've said, I've tried to first solve it for most common operators such as `share` and `shareReplay`.

Solving this problem is simple for those operators. It's just a matter of adding another check on subscription:
* if the subject [stopped](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Subjects/ReplaySubject.swift#L46) then just send information
* if not, do everything as normal

RxJS has those same checks. I've checked a few days ago. They've silently upgraded subject type with that `isStopped` check.

But the rabbit hole gets deeper.

If we do that, that won't solve the generic composition case:

```
let shared = obs
  .publish().refCount()
  //.share()
  //.shareReplay(1)
  //.shareReplay(2)
  //.shareReplayLatestWhileConnected()
```

But again, this will (and should solve this behavior for all Rx implementations consistently):

```
let shared = obs
  .subscribeOn(CurrentThreadScheduler.instance)
  .publish().refCount()
  //.share()
  //.shareReplay(1)
  //.shareReplay(2)
  //.shareReplayLatestWhileConnected()
```

But the rabbit hole gets deeper still.

But that won't solve the `retry` issue.

```
let shared = obs
  .subscribeOn(CurrentThreadScheduler.instance)
  .publish().refCount()
  //.share()
  //.shareReplay(1)
  //.shareReplay(2)
  .retry(3)
```

This will still work horribly with `retry` since `publish`/`share`/`shareReplay` operator will immediately just replay latest error.

That is one of the reasons we've introduced `shareReplayLatestWhileConnected` (`Driver` uses it) and made it stateless.

This will work as expected:

```
let shared = obs
  .subscribeOn(CurrentThreadScheduler.instance)
  .shareReplayLatestWhileConnected()
  .retry(3)
```

So aaaaanyway:
* we can optimize `.share()` operator "glitch" behavior to be equivalent to `shareReplay(1)`.
* we can add that stopped check for `.shareReplay(n)` case so it doesn't cause that glitch subscription
* how to solve `multicast(subject).refCount()` issues? Have no idea. Either subject should be "stateless" (clear state on sequence complete), or every subject needs to `isStopped` property, or this operator is designed to have that glitch (which I doubt). Somebody should push this question to organization scope.

Do you have time to help with this?

**Comment by groue** [comment]
Hello,

`share` is a very important operator, since it helps creating observables on shared resources like operating system singletons, or stateful objects based on a start/stop API like CLLocationManager.

This issue is concerning, because it looks like subscribers may not get the events they expect.

Would you please mind exposing the issue in an easier vocabulary, so that readers that are not expert in the RxSwift internals and rich set of operators can understand what's wrong, and eventually apply a workaround?

**Comment by fpillet** [comment]
@groue there is a basic flaw in `share()` and `shareReplay(n)` (_where n > 1_), where the observable gets resubscribed to and the subscription immediately disposed if an observer subscribed after the observable initially completes.

You can see the sequence of events as:
```
1. Observer subscribes to sequence
2. Sequence subscribed to
3. Sequence emits value
4. Observer receives value
5. Sequence completes
6. Observer's subscription disposed
7. Another observer subscribes to sequence
8. Another observer's subscription immediately completes
**9. Sequence subscribed to**
**10. Sequence immediately unsubscribed from**
```

The problem is with steps **9** and **10**. Re-subscribing to the sequence triggers the side effects (i.e. firing a network request). It shouldn't happen because the shared sequence has already completed.

**Comment by groue** [comment]
@fpillet Thanks for the explanation!

**Comment by kzaher** [comment]
I've investigated other implementations.

RxJS
```
var Rx = require('@reactivex/rxjs');

var interval = Rx.Observable.interval(1000);

var shared = Rx.Observable.of(1)
    .do(function (x) {
            console.log('Side effect');
    })
    .share();

shared.concat(shared).subscribe(function (x) {
        console.log(x);
    });

// Side effect
// 1
// Side effect
// 1
```

Subject has `isStopped` property.

RxJava
```
Observable<Integer> shared = Observable.just(1).doOnNext(new Consumer<Integer>() {
            @Override
            public void accept(@NonNull Integer integer) throws Exception {
                System.out.println("Side effect");
            }
        }).share();

        ArrayList<ObservableSource<Integer>> all = new ArrayList<ObservableSource<Integer>>();
        all.add(0, shared);
        all.add(1, shared);
        Observable.concat(all).subscribe(new Consumer<Integer>() {
            @Override
            public void accept(@NonNull Integer integer) throws Exception {
                System.out.println("Result " + integer.toString());
            }
        });
// Side effect
// Result 1
// Side effect
// Result 1
```

Subject has `hasThrowable` and `hasComplete` property.

I'm glad there is consensus how this should behave. I believe this was a bit different some time ago, or maybe just Rx.NET behaves differently. I've checked Rx.NET and I think it does still behave differently.

For RxSwift 4.0 we'll make `share` and `shareReplay` operators behave like RxJS/RxJava by default. We'll also add terminal event property on subject and adapt the rest of sharing operators. This will solve all other problems.

Right now for 3.0 we can create temporary patch `share` and `shareReplay`. We'll add new versions of the operators:
`share(subjectPerConnection: Bool)`
`shareReplayLatest(subjectPerConnection: Bool)`

If `subjectPerConnection` is `false`, we'll use current `share` and `shareReplay` implementations.
If `subjectPerConnection` is `true`, we'll use `shareReplayLatestWhileConnected` and new operator for `share` I'll create.

In 4.0 we'll just deprecate `shareReplayLatestWhileConnected` and redirect:
* `share` -> `share(subjectPerConnection: true)`
* `shareReplayLatest` -> `shareReplayLatest(subjectPerConnection: true)`

This will improve consistency between platforms.

I'll work on this next week so if somebody doesn't like `subjectPerConnection` parameter name or some part of this plan we can discuss it here.

**Comment by fpillet** [comment]
@kzaher I confirm that #1275 fixes the errors reported above 👍
