### ISSUE TITLE
Subscribe not getting triggered. (question)

### ISSUE THREAD

**Issue by rslim087g** [ReactiveX/RxSwift#1161]
I'm new to RxSwift. It seems like such a powerful way of programming but i cant get it to work. 

So i have a model ..
         class Person {

       var id: String
       init(id: String) {
      self.id = id
      }
       }

And in my ViewController,

    var person: Variable<Person> = Variable(Person(id: "1234"))
    let disposebag = DisposeBag()

    And in viewdidLoad, i'm calling the function setupPersonsIDObserver
       private func setupPersonsIDObserver {

         self.person.asObservable()
          .subscribe(onNext: {   person in
           print("triggered")
            })
           .addDisposableTo(disposebag) 
       }

Every time i press a button, it updates the person's id to a random uid 
           @IBAction func updatePersonsID(_ sender: Any) {
                     self.person.value.name = UUID().uuidstring
                }

I was hoping that every time i update the person's id the print statement in the subscription "triggered" prints.  however it does not.. and i was wondering what im doing wrong.

**Comment by biboran** [comment]
That's because your `Person` is a class rather than a struct. When you get person.value.name = String() you are simply updating `name` parameter of a `person` object. If you want `Variable<Person>` to trigger you have to push a new value to the `value` parameter. If you change `Person` to struct that's what it will implicitly do. If you want it to remain a class you have to do something to the extent of `person.value = Person(id: someNewID)` every time.

**Comment by rslim087g** [comment]
Ah I see .. Thanks man!
