### ISSUE TITLE
fatal error: Warning: Recursive call or synchronization error!: Variable.swift, line 41

### ISSUE THREAD

**Issue by thierrybucco** [ReactiveX/RxSwift#1202]
Hello,

I get this fatal error just after updated RxSwift (3.4.0). I am performing image manipulation in a concurrent dispatch queue then set value of Variable<UIImage> when user is scrolling a visual timeline. (see screenshot)

![img_0105](https://cloud.githubusercontent.com/assets/12764744/25143263/cc83fda4-2437-11e7-8d8b-50f3682aac0e.PNG)

If I change my DispatchQueue to be serial it fixed this crash. Maybe there is something I don't understand, could you give me some advices?

Thanks

Thierry

**Comment by kzaher** [comment]
Hi @thierrybucco ,

we've added this as a friendly warning, although I'm assuming that people won't find it very friendly :).

This is only a check for `DEBUG` mode. Rx won't crash in release mode but it's a sign that something is potentially being used in a wrong way.

For example, in this case probably value is being assigned simultaneously from multiple threads which is conceptual problem. What should that mean? It's an undefined situation if you ask me.

The simplest way to resolve this warning is to use some form of synchronization (since you have probably concurrent update problem).  e.g. `observeOn(MainScheduler.instance)` + disposing the subscription when new work starts and old one needs to be cancelled.

> `observeOn(MainScheduler.instance)` 

... will solve the crash, but you also need 

> disposing the subscription when new work starts and old one needs to be cancelled

... to fix the conceptual problem.

Hope this makes sense.

**Comment by thierrybucco** [comment]
Thanks a lot @kzaher.

**Comment by nazeehshoura** [comment]
Many kittens died because of this. Can we make this warning a log in the console instead of a crash.
And make it crash on the next release of Rx so we can be better prepared :)

**Comment by kzaher** [comment]
Hi @nazeehshoura ,

Yeah, sure.

**Comment by Alex-Alex77** [comment]
I also have this warning and crash once in a while. Is there something wrong with this code:
tableView.rx.didScroll.asDriver().drive(onNext: ....).disposed(by: disposeBag).
And what do you mean by "disposing the subscription when new work starts and old one needs to be cancelled"?
