### ISSUE TITLE
Does `disposed(by:)` really conform to API Design Guidelines?

### ISSUE THREAD

**Issue by hiragram** [ReactiveX/RxSwift#1211]
I want to discuss about `disposed(by:)` in `Disposable` which was recently added (#1079) as a substitute of `addDisposableTo(_ bag:)`.

In guideline, it says

> Prefer to name the nonmutating variant using the verb’s past participle (usually appending “ed”):

In this context, 

```swift
let a: Observable<Void> = ...
let bag = DisposeBag.init()

a.subscribe().disposed(by: bag) // 🤔
```

last line seems to return "Disposable, which has been already disposed by `bag`", but nothing will be returned.

I propose to rename `disposed(by:)` to `add(to:)` or `register(to:)`.

How do you think about that?

**Comment by kzaher** [comment]
Hi @hiragram ,

> last line seems to return "Disposable, which has been already disposed by bag", but nothing will be returned.

This is not correct. It will not do anything on disposable/subscription at that time -> nonmutating. It is a declaration that subscription **will** be disposed (terminated) by the dispose bag in future.

I understand why people would say that name is not ideal, but I haven't heard any better concise option IMHO. We had those discussions on Slack.

The purpose of the method is to describe in a declarative way how will the subscription be  handled -> it will be `disposed(by: disposeBag)` when dispose bag deallocates.

> add(to:) or register(to:)

The primary purpose of the API isn't to add it to some collection but to explain when will the resources/subscription be disposed. If somebody is familiar how disposeBag works, it should be clear what is the intention of that API.

Swift API guidelines are written with imperative APIs in mind, and this is a declarative part of the API. That's why they are called guidelines. We try to adhere to them when they make sense, and figure out how to best handle situations in which they don't.

I'm always open to suggestions. Maybe somebody will think of a better API for this.

**Comment by hiragram** [comment]
Hello @kzaher, thank you for your reply.

> This is not correct. It will not do anything on disposable/subscription at that time -> nonmutating. It is a declaration that subscription will be disposed (terminated) by the dispose bag in future.

Yes, I know they actually work as you say. So my opinion is that a mutating method should be named as `disposed`, and nonmutating method shouldn't.

> The purpose of the method is to describe in a declarative way how will the subscription be handled -> it will be disposed(by: disposeBag) when dispose bag deallocates.

OK, I agree with you. 
How about `willBeDisposed(by:)` ? As I wrote above, this usage of the word `disposed` does not conform to API Design Guidelines I think.

By the way, I know that your previous discussion is on Slack, but I couldn't reach these posts because there is a limit of number of search results. If you can find one, tell me the URL, please?

**Comment by kzaher** [comment]
Hi @hiragram ,

I could see us theoretically using `willBeDisposed(by:)` instead of `disposed(by:)`, although `disposed(by:)` seems shorter to me.

I guess we can open public voting for RxSwift 4.0 public API. I don't think we'll change again in 3.0 version.

**Comment by hiragram** [comment]
I may be confused with mutating and nonmutating.
I will update my comment later.
