### ISSUE TITLE
Request: subscribe where E: O.E

### ISSUE THREAD

**Issue by farzadshbfn** [ReactiveX/RxSwift#1257]
subscribing (or binding) is not possible in cases some models conform to some protocol.

let's say we have a ```swift protocol Model { }``` and a struct ```swift struct Value { }``` and later on an extension ```swift extension Value: Model { }```.

because of `subscribe` (and `bind(to:_)`) syntax:
```swift
func subscribe<O: ObserverType>(_ observer: O) -> Disposable where O.E == E { }
```

code below doesn't work:
```swift
Observable<Value>.just(...)
    .bind(to: rx.model }
    .disposed(by: disposeBag)
```
it should be written as below:
```swift
Observable<Value>.just(...)
    .map { $0 as Model }
    .bind(to: rx.model }
    .disposed(by: disposeBag)
```

Suggestion:
add following methods:
```swift
func subscribe<O: ObserverType>(_ observer: O) -> Disposable where E: O.E { ... }
func bind<O: ObserverType>(to observer: O) -> Disposable where E: O.E { ... }
```

**Comment by farzadshbfn** [comment]
This will solve the problem:
```swift
extension ObservableType {
    public func bind<O: ObserverType>(to observer: O) -> Disposable where O.E: E {
        return self.map { $0 as O.E }.subscribe(observer)
    }

    public func subscribe<O: ObserverType>(_ observer: O) -> Disposable where O.E: E {
        return self.map { $0 as O.E }.subscribe(observer)
    }
}
```

**Comment by kzaher** [comment]
Hi @farzadshbfn ,

Interesting idea. I think what you are asking for is something that is known as `covariance` of generic parameters.

This should really be a language feature that Swift unfortunately doesn't support.

I don't think that the code you've proposed is a valid Swift code :)

<img width="865" alt="screen shot 2017-05-18 at 18 19 17" src="https://cloud.githubusercontent.com/assets/1641148/26197898/91ab0b42-3bf6-11e7-91fc-66ea0e3b8b9e.png">

This should make you too sad in this case though :)

Ideally I would advise using value types (structs) for sequence elements. Using protocols has fewer compile time guarantees because reference types could also implement some protocol and there is bigger chance you could accidentally cause side effects.

**Comment by farzadshbfn** [comment]
I know, i am using value types most of the time too... and yeah you are right, swift does not support covariance in some cases

I'm aware of the consequences but sometimes it reduces the amount of code in some levels.
I was trying to avoid generic view controllers, but i guess that's the only way so thay i can move O.E: E where clause up to the extension.
P.s: srry for not highlighting, i'm answering on phone
