### ISSUE TITLE
UIImagePickerController+Rx.swift

### ISSUE THREAD

**Issue by d3020** [ReactiveX/RxSwift#1261]
When:
Installing RxSwift 3.4.1
and
Installing RxCocoa 3.4.1

I'm not seeing the UIImagePickerController+Rx.swift file included in the RxCocoa pods group. Should it be there or is this something I should expect to have to add manually? 

===

I'd like to know if this is correct thinking because I'm not sure. It looks like this file in particular needs to be added manually and is in a folder called "Extensions" in the example project. Is this right?

**Comment by kzaher** [comment]
Hi @d3020 ,

`UIImagePickerController+RxCreate` is an example how one could use `UIImagePickerController`. This is something we won't ship with RxCocoa because it's not clearly defined, it's not a simple UIKit extension, although it's extremely useful.

We could pull `UIImagePickerController+Rx.swift` delegate extensions inside RxCocoa, but let's do it for 4.0 because if we do it now, we'll probably break those applications that included raw `UIImagePickerController+Rx.swift` file.
