### ISSUE TITLE
How to use sentMessage with subclass?

### ISSUE THREAD

**Issue by onmyway133** [ReactiveX/RxSwift#1288]
Hi, I'm trying to use `sentMessage` with subclass. I have a class called

```swift
class ListController: UIViewController {
  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    // THIS IS AN OVERRIDDEN METHOD
  }

  func hello() {
    // THIS IS A METHOD FROM SUBCLASS
  }
}
```

And I use `sentMessage`

```swift
let list = ListController()

list.rx.sentMessage(#selector(ListController.hello)).subscribe(onNext: {
  print($0)
})

list.rx.sentMessage(#selector(ListController.viewDidAppear(_:))).subscribe(onNext: {
  print($0)
})

list.viewDidAppear(true)
list.hello()
```

I see that `subscribe` is not called at all. It seems that `sentMessage` does not work for subclass if
- it overrides the method 
- it introduces a new method

What I'm trying to do is https://github.com/onmyway133/blog/issues/55. I've just read this https://github.com/ReactiveX/RxSwift/pull/308 so maybe there's some clues there. 

I don't like swizzling, just want to see how it works with this case

**Comment by tarunon** [comment]
@onmyway133 Hello, I think this problem is caused on difference of method invocation between Swift and Objective-C.
Actually, `NSObject.rx.sentMessage` and `NSObject.rx.methodInvoked` is based on method swizzling, Swift method invocation based v-table and it's not affected on method swizzling.
If you want to use `objc_msgSend` way in swift, you can use `dynamic` modifier on your function.
```swift
class ListController: UIViewController {
  override dynamic func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    // THIS IS AN OVERRIDDEN METHOD
  }

  dynamic func hello() {
    // THIS IS A METHOD FROM SUBCLASS
  }
}
``` 
But in my opinion, it's not good that using `NSObject.rx.sentMessage` and `NSObject.rx.methodInvoked` a lot.
