### ISSUE TITLE
combineLatest resultSelector redundant?

### ISSUE THREAD

**Issue by alecthomas** [ReactiveX/RxSwift#130]
It seems that `combineLatest` could be simplified to exclude `resultSelector` given that `combineLatest(a, b, fab)` is exactly equivalent to `combineLatest(a, b).map(fab)`? Is this correct?

I did notice that the other Rx implementations also include this function though, so maybe consistency is a more pressing concern, or I'm missing something obvious.

**Comment by kzaher** [comment]
Hi @alecthomas ,

I understand why do you feel that `resultSelector` should be excluded. I'm not sure I can convince you that it's not excess function argument, but I can share reasoning why it's there, so maybe that will clear things up.

While I was working on this project I have tried to really think about which parts of Rx are general cross platform concepts, and which ones are just per platforms adaptations.

I'm not trying to say this is some kind of universal truth, but more explanation why things are the way they are.

* the name says `combineLatest`, and not `latestTuple`, so `combine` part is unclear without a way to specify how elements are combined.

* if we were to exclude `resultSelector` we would in a statistically convincing number of cases need to have `map` behind every `combineLatest` anyway because tuples aren't usually useful.

* writing `combineLatest(a, b, +)` is as clear, but more concise then `combineLatest(a,b).map(+)`.

* even though we try to make operators as cheap as possible, one operator still has better performance then 2, and less stack track footprint.

* this way is consistent with other Rx implementations.

* there is also a version of `combineLatest` that extends array of observables and resultSelector that accepts array of elements, so if we were exclude selector, we would make a different API for a function that shares the name.

There are maybe other reasons I can't think of right now, but these were enough for me.
Hope this clears things up :)

**Comment by alecthomas** [comment]
Thanks for the comprehensive answer, I can see that your reasoning is well thought out!
