### ISSUE TITLE
How can I make the table view cells disappear with animation?

### ISSUE THREAD

**Issue by Sweeper777** [ReactiveX/RxSwift#1303]
I am binding this `Variable<[String]>` to a table view's items. I made it so that when an item is tapped on, it disappears:

```
class MyTableViewController: UITableViewController {
    let model = Variable<[String]>(["Tom", "Dick", "Harry", "Donald", "Lucy", "Lily", "Olivia"])
    let disposeBag = DisposeBag()
    
    override func viewDidLoad() {
        tableView.delegate = nil
        tableView.dataSource = nil
        
        model.asObservable().bind(to: tableView.rx.items(cellIdentifier: "myCell", cellType: UITableViewCell.self)) {
            row, model, cell in
            cell.textLabel?.text = model
        }.disposed(by: disposeBag)
        
        tableView.rx.modelSelected(String.self)
            .subscribe(onNext: {
                name in
                if let selectedRowIndexPath = self.tableView.indexPathForSelectedRow {
                    self.tableView.deselectRow(at: selectedRowIndexPath, animated: true)
                }
                _ = self.model.value.remove(object: name)
        }).disposed(by: disposeBag)
    }
}

```

However, the table cells just disappear abruptly, without any animation. It does not even show the selection animation.

How can I do this with animation?

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
