### ISSUE TITLE
Revisit typed errors?

### ISSUE THREAD

**Issue by hfossli** [ReactiveX/RxSwift#1320]
We discussed typed errors here on github [a while back](https://github.com/ReactiveX/RxSwift/issues/650). Maybe you've discussed on slack as well. I thought maybe it is time to revisit this question.

**Unambiguous API**
The user of your API doesn't need to make assumptions. She/he will know what errors your API produces. So will your unit tests. 

**Let the compiler do the job**
Type safe languages have the benefit of letting the compiler do work that you normally have to unit test. Does `PushHandler` return any other error than `PushHandlerError`? No need to unit test mundane stuff like that if the compiler can tell you right away.

**Sequences that can't fail**
Some sequences can't fail and that is valuable information when dealing with them as it makes code less engineered and less complex.

~~

RAC has a [great writeup](https://github.com/ReactiveCocoa/ReactiveSwift/blob/533fb76d20ee336b562943a606efa693b3a5dc18/Documentation/BasicOperators.md#working-with-errors) on how working with typed errors is like . 

Would it be possible to change the API in such way that it is possible to opt-in to typed errors? 

I love typed errors, but hey, maybe that's just me :)

**Comment by hfossli** [comment]
About opting in to typed errors, would that maybe require Swift being able to have default values for parameter type information? I don't know if that exists, is a good idea or anything – just popped in to my mind... E.g. `class Observable<Element, ErrorType = Error>` so that it is possible to both write `Observable<String, MyError>` and `Observable<String>`?

Or is there other ways of opting in?

**Comment by freak4pc** [comment]
@hfossli that's a great point in general but I also feel like it's a "developer concern" and not necessarily a RxSwift concern. The "official" ReactiveX standard is failing on sequence error. 

I wouldn't be opposed to a type of Observable that can't fail / provides typed errors but I'm not sure it's exactly in the scope of this library ... 

Also, some people rely on ReactiveX-based implementations to work the same across platforms so having this "discrete" implementation that is only relevant to RxSwift could be highly confusing and needs to be well thought out IMO. 

In 99% of the cases these issues are resolved with using a Result type, which is just a "standard" part of RAC, really. RxSwift gives you the freedom of choosing how you want to model your results and doesn't "bind" (pun not intended) you into a specific format (for better or worse) 

Just me $0.02

**Comment by sergdort** [comment]
Hi, @hfossli !

I personally agains typed errors! :)

* they do not provide any value (in my opinion)
* introduce unnecessary mess (`flatMapError`, `mapError`, `attemptMap` , `NoError` and family)
* swift does not support typed throws , and even if it would I would not like RxSwift to have typed errors (look at RxJava)
* it gonna break cross language similarity

Also I feel like it violates duality math behind Rx

**Comment by sergdort** [comment]
Also in my opinion `Observable` based API are perfect example of `Open Closed Principle`, looking on API like
```
func getSomething() -> Observable<Something>
``` 
The data may come from cache, network, steaming connection or both. It allows to model you app without worrying that changes of platform will break something. Adding typed error will most likely break the client if you change type of the error or add another `case` to your `Error` enum

**Comment by hfossli** [comment]
Awesome feedback! Thanks for sharing your insight in to this matter. The scale seems to be in favor of not introducing typed errors. :-)

Theoretically speaking, is it possible to opt-in, do you think? If so, then how? And if so, is it still a bad idea even if it is opt-in?

**Comment by freak4pc** [comment]
I still feel it would provide too much divergence and that it doesn't belong in the "Main" Repo. I could imagine people installing a `RxResult` extension that would just add some Observable overrides to change some default behaviors or provide a new type, but I don't get a good feel for anything like this on the main repo (IMO)

**Comment by kzaher** [comment]
Hi @hfossli ,

I didn't have a lot of time to follow development around Swift 4.0 so maybe I'm wrong about this but it seems to me that Swift doesn't support parametrized error throwing.

Something like this isn't supported:

```
let lambda: (a: String, b: Int) throws MyError -> NormalResult = ....
```

If this was supported in Swift then we could probably find some way to incorporate typed errors in RxSwift.

If Swift supported something like `class Observable<Element, ErrorType = Error>` then we could definitely make everyone happy and it would be a no brainer.

As far as I can tell Swift unfortunately doesn't support parametrized error throwing or default generic parameters. I've heard some rumors but haven't seen anything concrete on this.

If somebody has some new informations please let us know.

When I need something strongly typed I don't model it as error but treat it as normal return value.

You can write `Single<MyResult>` where `MyResult` can be either a normal enum or `typealias MyResult = Result<String, MyError>`.

We can only introduce this feature if Swift natively supports it otherwise naming project RxSwift would be weird IMHO.

**Comment by freak4pc** [comment]
I think this can be closed, @hfossli Do you have anything you'd want to add here?

**Comment by hfossli** [comment]
Thank you all for your very valuable feedback! 

Sorry for the delay, but I just had to give result-enum a whirl and get some field experience from it. To me it doesn't make much difference using a result-enum. Let me illustrate using some basic example.

```swift
struct User {}

enum Result<Value, Error> {
    case success(Value)
    case failure(Error)
}

enum AuthenticationError {
    case badUsername
    case badPassword
    case networkError(underlying: Error)
}
```

#### Result-enum
```swift


func authenticate() -> Observable<Result<User, AuthenticationError>> {
    return Observable.just(.success(User()))
}

func login() {
    authenticate().subscribe(onNext: { (result) in
        switch result {
        case .success(let user):
            print("handle user \(user)")
        case .failure(let error):
            switch error {
            case .badUsername:
                print("handle bad password")
            case .badPassword:
                print("handle bad password")
            case .networkError(underlying: let underlying):
                print("handle network error \(underlying)")
            }
        }
    }, onError: { (error) in
        print("unknown error?") // or maybe fatalError()
    })
}
```


#### Plain
```swift
func authenticate() -> Observable<User> {
    return Observable.just(User())
}

func login() {
    authenticate().subscribe(onNext: { (user) in
        print("handle user \(user)")
    }, onError: { (error) in
        if let error = error as? AuthenticationError {
            switch error {
            case .badUsername:
                print("handle bad password")
            case .badPassword:
                print("handle bad password")
            case .networkError(underlying: let underlying):
                print("handle network error \(underlying)")
            }
        } else {
            print("unknown error?") // or maybe fatalError()
        }
    })
}
```

I think actually using result-enums makes it all a little worse as the cognitive load is increased IMO (when e.g. subscribing, mapping, bridging between plain observables and observables sending result-enum). 

For those interested I found some related discussions. In Java they have typed exceptions, but still RxJava chooses not to have any typed errors in its Observable class https://github.com/ReactiveX/RxJava/issues/5221.

**Let's revisit this topic if swift lang either gets typed errors in throwing functions or if it is possible to specify a default type for generics like `class Observable<Element, ErrorType = Error>`.**

Again, thank you for your valuable feedback! 🎉

**Comment by nikita-leonov** [comment]
@hfossli is default associated type can help with default error type? https://twitter.com/johnsundell/status/997183435759382529

**Comment by nikita-leonov** [comment]
ps nope :(

**Comment by kzaher** [comment]
@nikita-leonov 
Did Swift compiler gained some new features regarding typed error throwing?

**Comment by nikita-leonov** [comment]
@kzaher they didn't, but I believe the question was different. How to provide a typed errors option without introducing breaking change into the code base that is already built around stander ErrorType. So we were looking into an option **default generic arguments** like described in Generic Manifesto — https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md 

With such option it would be possible to provide an option to override default ErrorType, so old code will work unchanged and all people demanding typed errors will retrieve it too. Probably it is time to create some buzz in forums.swift.org and get ball rolling for it.

**Comment by kzaher** [comment]
Hi @nikita-leonov ,

the main issue isn't default generic arguments, that part has multiple non elegant solutions. Default generic arguments are just polish.

The main issue is will Swift compiler allow typed error throwing.

**Comment by nikita-leonov** [comment]
Can you clarify why `throwing` affects decision on Rx design? Most of `throws` use in Rx is only related to RxCocoa, but not Rx itself. Moreover in scenarios where `throws` is used in Rx which is very limited it can be replaced with `Result`. In the last statement in this issue it was said that it is either `typed throwing` or `default generic`. So I guess with one of those it is possible to move furthere. 

I also assume that `typed throwing` from Apple is just a confirmation that introducing typed errors in Rx is a right way to go that will make Rx more native to Swift. It is more an extra confirmation to justify a change, rather than an architectural need that limits an implementation.

**Comment by freak4pc** [comment]
I don’t think there’s any reason to replace anything with a Result type. That decision should be up to the user and I don’t feel like Rx should be opinionated in that way (like ReactiveSwift is). 

I think that in general any sense of typed throws that actually respects the throwing type is today between a hack and a non-existing language feature and agree with @kzaher that it would be better to re-examine this if Apple itself introduced *truly* types error throws.

Otherwise you’re not really becoming “more swifty” and mainly spending your time bridging the gap for non-existing language features.

**Comment by kzaher** [comment]
RxSwift should use default Swift error mechanism since the library is meant for Swift language users.

> Moreover in scenarios where throws is used in Rx which is very limited it can be replaced with Result

If Swift team decides to ship a built in Result type and proclaims that this is the default error handling mechanism, and if Apple is planning to migrate all of their existing APIs to conform to their new Result type, then yes, we will also migrate towards it.

> I also assume that typed throwing from Apple is just a confirmation that introducing typed errors in Rx is a right way to go that will make Rx more native to Swift.

What do you mean by this? Links?

> It is more an extra confirmation to justify a change, rather than an architectural need that limits an implementation.

I'm not sure what do you mean by this.

When I say parametrized typed error throwing, I mean something like this.

```swift
static func someMethod<T>() throws T {}
```

I was a bit out of the loop, so maybe I don't have the latest information. Is this coming?

**Comment by nikita-leonov** [comment]
Nope-nope. Sorry for miscommunication, it was all assumption, not a statement. I was saying that I assume you are looking for `typed throwing` as a justification for an effort and it is not an actual limitation of a language for to implement it. Based on your answers I think I am correct. 

Also your statement is more strict in compare with statement from @hfossli as he was saying that it is either one or another, `typed throwing` was not mandatory requirement. Anyway I think I understand a current state of things now. I think it is ok to have two FRP frameworks, one more strict (ReactiveSwift) another one is less strict (RxSwift) and let users choose what they want. Cheers. :)

**Comment by freak4pc** [comment]
RxSwift is more strict in regards to ReactiveX. ReactiveSwift chooses whichever way they want. Both are fine choices depending on the situation :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kzaher** [comment]
> Anyway I think I understand a current state of things now. I think it is ok to have two FRP frameworks, one more strict (ReactiveSwift) another one is less strict (RxSwift) ...

I don't think this sentence characterizes the spirit of this project correctly and there isn't a parallel between errors from RxSwift and ReactiveSwift. 

Both RxSwift and ReactiveSwift have something named error in their events, **but they aren't conceptually interchangeable**. 

You would use error in RxSwift as a short switch: 
* Something unexpected happened
* I don't know how to handle this, just send it to server and log it, I have no idea how this is happening (and yes, delete the logs because of GDPR after you've figured out what the hell is happening)
* But I also don't want to kill the entire app because of it. 

**It is not recommended to encode any business logic in errors, catch them and then parse the error information. This is anti-pattern IMHO.**

**I'm usually using resultish values as sequence elements because you want the compiler to notify you if you've forgotten to handle some case.**

There are some type safe properties that this project offers that some other projects don't:
* compile time guarantee that the sequence generates single, 0-1 or none elements (Single, Maybe, Completable)
* compile time guarantee that you won't have deadlocks and that you can safely reason about multi-operator compositions without worrying about data races, sharing strategy guarantees (Driver, Signal and other traits from RxCocoa)
* there are also guarantees that certain sequences won't error out (Driver, Signal and other traits from RxCocoa), but yes, there are no general guarantees regarding erroring out.

ReactiveSwift could also advocate that their Signal, Properties, etc... are the latest and coolest things ever.

> ... and let users choose what they want. Cheers. :)

Sure  😆  🥂 🥂 🥂 

There is just one tiny detail nobody is mentioning, so I'm going to mention it anyway. Maybe somebody will find this information useful.

There are actually 3 events in Observable (or 4 in RXS/SignalProducer) and for some reason everybody is forgetting about Completable event (or Completable/Interrupted in RXS case).

I can't be entirely sure why people are advocating for parameterized errors, but I'm assuming that they are probably advocating this because they want to be sure that they've handled all of their errors, and their user interface won't die because they've forgot to handle an error (that's one of the reasons why we have Driver/Signal in RxCocoa). 

BUT

Even if we parameterized Error type, **that still wouldn't be enough to guarantee that your user interface won't die**. Your sequence can Complete and you also need a guard against that.

This is not just theoretical concern, consider this code:
```swift
let iCanSometimesErrorOut: Observable<Int, Error>;
let iMSafeToBindToUI: Observable<Int, NoError> = iCanSometimesErrorOut
     .catchError(x => Observable.empty())
```

**Hint: If you've found this comment, more useful approach is maybe retry family of operators but be careful with them, because you could accidentally overwhelm your service and create a DDOS attack on your service if you don't properly design a retry strategy, so try to implement some binary [back-off retry strategy](https://github.com/NoTests/RxFeedback.js/blob/0f94f159e3176671798286c0061977fae72b2b09/src/index.ts#L232) to prevent these kinds of issues.**

This is perfectly safe to bind to user interface, but it doesn't prove compile time that your code is correct just because it has `NoError`. You UI will still die even if no error is thrown. Complete event is also a silent killer.

**I'm not trying to say that reminding the user that somebody hasn't handled the error properly isn't a nice handy thing (I find this really useful with Driver/Signal from RxCocoa), but that it doesn't provide you with guarantees that one would assume from the code itself.**

The case I've presented isn't theoretical. I've been watching people day after day people writing code like this (usually with Driver, but nothing in the interface would prevent people from doing the same thing with Observable if we added typed errors). If you are thinking the problem was people, I'm not that convinced, these were very capable people IMHO that I respect, but they just needed time like everyone else.

One could think, ok, let's add typed complete event.
```swift
let iCanSometimesErrorOutAndComplete: Observable<Int, Error, ()>;
let iMSafeToBindToUI: Observable<Int, NoError, NoComplete> = iCanSometimesErrorOut
     .catchError(x => Observable.never()) // <--- just change to never
```

This again won't work. One can just replace `empty` with `never` and you are back to square one. Your program type checked, your sequence will never complete, but your user interface is dead again because it won't ever receive any elements.

If errors regarding `.catchError(x => Observable.empty())` are common, it is reasonable to assume that errors regarding `.catchError(x => Observable.never())` would be common somewhere approx same order of magnitude.

But yes, we don't have NoError type in Observable, sorry ¯\\\_(ツ)\_/¯

**Comment by nikita-leonov** [comment]
I hold my breathe to see how Swift APIs will change with appearance of Result. Do we see a typed error handling in Swift as a reason to discuss this topic for RxSwift one more time?

**Comment by freak4pc** [comment]
There’s not much to hold breath for unfortunately. Swift is open source and we can see how their result type looks; it’s not different than most implementations and it doesn’t have typed errors.

**Comment by hfossli** [comment]
To me it seems to have typed error https://github.com/apple/swift-evolution/blob/master/proposals/0235-add-result.md or maybe i am missing something. 

The declaration is
```
public enum Result<Value, Error: Swift.Error>
```
Which allows to define the type, right?

**Comment by kzaher** [comment]
It looks like Swift 5 introduces `Result<Value, Error: Swift.Error>`.

This thing compiles:
```swift
struct Observable<Value, Completed, Error> { }
```
but it would be ideal if
```swift
struct Observable<Value, Completed = Never, Error = Never> { }
```
would also compile.

As I see it we could introduce something like

```swift
struct ObservableXXX<Value, Completed, Error> { }
```
and make
```swift
typealias Observable<Value> = ObservableXXX<Value, (), Error>
```

I think that if we did that it would be win/win situation because we would maintain backwards compatibility and provide more type safety options.

Once `Swift` adds default generic arguments, we could just make:
```swift
struct Observable<Value, Error = Never, Completed = Never> { }
```

1rst stage: First provide additional features and type safety together with more dynamic API.
2nd stage: Make a breaking change by effectively changing from:
```swift
struct Observable<Value, Completed = (), Error = Error> { }
```
to
```swift
typealias DynamicObservable<Value> = Observable<Value, Completed, Error>
struct Observable<Value, Completed = Never, Error = Never> { }
```

I think we could implement first stage for RxSwift 5.0. When should we make the second stage is hard to tell because there is a lot of legacy and educational code out there. It would be ideal if Swift 5.0 introduced default generic arguments and if we just made it all at once, but it seems like this is not the case.

For the second stage one could make a global rename of `Observable -> DynamicObservable`, so it's not a horrible breaking change.

Anyway, these are my thoughts.

**Comment by nikita-leonov** [comment]
@kzaher nice. I didn't expect `Completed` in the list for parametrization. Does it mean `Completable` can be expressed as `Observable<Never, Void, Error>`? Is there a plan to rethink all the traits in such way? 
As an alternative it is still possible to stick to `Observable<Value, Error>` and implement not completable as one more trait.

**Comment by kzaher** [comment]
> @kzaher nice. I didn't expect Completed in the list for parametrization.

If we are doing this, then we are doing this right. `Completed` event is no less important than any other. `Complete` communicates does the state machine have completed state. Is the state machine finite.

I actually mostly use 
```
Single<Value, Never>
Observable<Value, Never, Never> (wrapped in `Driver`)
``` 
All other combinations are rare IMHO.

> Does it mean Completable can be expressed as Observable<Never, Void, Error>?

I guess you can do `Observable<Never, Void, Error>` or `Observable<Never, Void, Never>` depending on your use case. Define it as you wish.

> Is there a plan to rethink all the traits in such way?

Yes, we would generalize all of them, not just `Observable`.

> As an alternative it is still possible to stick to Observable<Value, Error> and implement not completable as one more trait.

I don't think ignoring `Completed` makes sense. You will need to typealias `Observable`s anyway if you want to make your code sane. The most compelling purpose of introducing `Error` parameter is to be able to communicate that the state machine can never enter final error state. Final complete state is almost as bad if you want to play the type safety card. Read my posts above for rationale.

**Comment by hfossli** [comment]
Your proposal is very interesting and appealing to me. Being able to opt-in to compile-time guarantees about completed never being called etc should take some cognitive load away when reading and writing code. I do hope the cognitive load isn't burdened down by type declarations and semantics. What do you think?

PS: My opinions might not be representing the users of this project as I am not using Rx actively these days because of my current projects and constraints.

**Comment by sergdort** [comment]
@kzaher as I understand we want to have `Completed = Void | Never`. Am I correct?

**Comment by kzaher** [comment]
@sergdort Yes, these are the only values I've used.

**Comment by sergdort** [comment]
I just wonder if it would technically possible to define a type `Observable<String, Int, Error>`?

**Comment by kzaher** [comment]
Yes, it would be.

**Comment by freak4pc** [comment]
Would you actually want Completable to have something which isn't Never or Void? Kind of strange. 
Wouldn't it make sense to limit these?

**Comment by kzaher** [comment]
@freak4pc How would you limit them?

**Comment by nikita-leonov** [comment]
@kzaher I think this should be enough.

```
protocol CompletableToken {}

struct Completes: CompletableToken {}
struct NeverCompletes: CompletableToken {
	private init() {}
}

struct Observable<E, C: CompletableToken, F: Error> {}
```

`CompletableToken` still available for engineers to implement their own completion tokens, but I think it is higher barrier in compare with using raw generic. Also eventually we can use opaque result types proposal when it will land to hide `CompletableToken` constraint completely I guess.

**Comment by nikita-leonov** [comment]
ps I think opaque result types would not have with proper isolation of CompletableToken protocol, but I think there will be at some point proposal that address this anyway, as it is common to limit use cases of exposed code. The same way as we have `open` vs `closed` etc.

**Comment by kzaher** [comment]
Hi guys,

It has been a long time since I've responded here. Releasing 4.4.1 was a priority. I'm hoping that 4.4.1 is the last patch we need to release for 4.x version and that the next version will be directly 5.0. I guess this is the only major change for 5.x.

The plan for 5.x would be to first create a 5.x branch and create a prototype of generic `Observable<Value> = ObservableSource<Value, (), Swift.Error>`.

I'll try to do that this or next week, but can't make any promises. After that I guess it's a matter of porting all of the operators. 

>```swift
>protocol CompletableToken {}
>
>struct Completes: CompletableToken {}
>struct NeverCompletes: CompletableToken {
>	private init() {}
>}
>
>struct Observable<E, C: CompletableToken, F: Error> { /*...*/ }
> ```


@nikita-leonov I don't think this limits it to just `NeverCompletes` or `Completes`.

**Comment by freak4pc** [comment]
Should we rename `E`, `C` and `F` to - `Element`, `Completion: CompletableToken`, `Error: Swift.Error` ? That `F` doesn't make a lot of sense. 

By the way, if you want to do some division of work and give me some operators to migrate I'd love to help out and take some work off your hands. Let me know :)

**Comment by kzaher** [comment]
> Should we rename `E`, `C` and `F` to - `Element`, `Completion: CompletableToken`, `Error: Swift.Error` ? That `F` doesn't make a lot of sense.

We can take a look at `Result` terminology. I think they use `failure` terminology. I think error probably makes most sense although I would like to understand the rationale why did they name it `failure`.

Is there some difference between `error` and `failure`? `Exception` is probably the weirdest name since it's actually statistically the common case if you do fizz tests on some API :)

**Comment by freak4pc** [comment]
I think they named it failure because its a stateful enum case - "success" and "failure" are the enum cases. It was also a well-known community implementation in Swift and other languages specifically for the Result type.

**Comment by kzaher** [comment]
But why did they name it `failure` vs `error`? If they really wanted it to stand out they should have just used Haskell `Either` and `left`, `right`.

**Comment by freak4pc** [comment]
I think because error is a noun (like 'a ball') and failure is a state (like 'playing').

**Comment by kzaher** [comment]
Hm, I really need to learn english well before I start with german. It seems to me that you can make state out of both of them. 

Don't know, my brain just doesn't care about these things no matter how hard I try. I'm fine with (`failure` or `error`). `Error` is probably more consistent with our codebase, but if there are `failure` admirers out there, I'm all ears.

**Comment by freak4pc** [comment]
I prefer error as well. It represents the `Swift.Error` type anyways. I was mainly asking about the generic letter you assigned to it (`F`). I imagine you did this because `E` is for the element type, in which case it might make more sense to do `Error: Swift.Error` instead of `F: Swift.Error`. But alas, I don't mind that much :)

**Comment by kzaher** [comment]
That was not my code.

**Comment by freak4pc** [comment]
Sorry, didn't see the comment you copied it from.

**Comment by nikita-leonov** [comment]
@kzaher in way as I defined it, it limits to anything that implements `CompletableToken`, and I suggest that RxSwift will provide two default implementations of `CompletableToken` that will satisfy two major use cases of completes & never completes. IMHO it provide an extra constrain that informs engineers in way they will not make obvious mistakes. However it will be still possible to break it even in a proposed way.

**Comment by kzaher** [comment]
I'm playing with ideas for RxSwift 5.0 [here](https://github.com/ReactiveX/RxSwift/tree/rxswift-5.0-ideas). Didn't have much time to play with this, but hoping to get benchmarks running soon so we can estimate performance impact.

I'm trying to simplify the project structure while doing this, but there is bunch of code in the project :)

I'm publishing this just in case anyone is interested in the prototype and has early feedback.

Once benchmarks are running, we'll estimate the performance impact, optimize for the benchmarks and then port the rest of the project once we've profiled it. 

At least that's the plan.

**Comment by stephencelis** [comment]
> @nikita-leonov I don't think this limits it to just `NeverCompletes` or `Completes`.

You could use a closed class hierarchy instead of a protocol.

**Comment by nikita-leonov** [comment]
Yeah my fault, you are right @stephencelis . It should not be not a protocol, but a class with private `init`. So not `NeverCompletes` and `Completes` are implement it, but no one else outside of module can do so. Ugly trick, but what else we can do with the current state of the language?

**Comment by DevAndArtist** [comment]
I skimmed over this issue quickly as it's a topic I would like to track and provide feedback. @kzaher is there a reason you want not permit custom types for `Complete`? We don't support it now but I think it would make sense to extend this possibility for the future. Especially because we don't need `NeverCompletes` as it won't have any compiler support compared to `Never`.

If this was the *new* `Event` enum in RxSwift.

```swift
public enum Event<Element, Completion = Void, Failure: Error = Error> {
  case next(Element)
  case failure(Failure)
  case completion(Completion)
}
```

It can have strong compile time guarantees for switch exhaustiveness:

```swift
// enum is exhaustive
switch Event<Int, Never, Never>.value(42) {
case .next(let element):
  print(element)
}

// like in `Observable<Int> == Observable<Int, Error>`
switch Event<Int, Never, Error>.value(42) {
case .next(let element):
  print(element)
case .failure(let error):
  print(error)
}

// empty behavior
switch Event<Never, Void, Never>.completion(()) {
case .completion(_):
  print("completed")
}

// throw behavior
switch Event<Never, Never, Error>.failure(NSError()) {
case .failure(let error):
  print(error)
}

// never behavior
switch Event<Never, Never, Never>.value(fatalError()) {
}
```

**Comment by DevAndArtist** [comment]
Also if I'm allowed to bikesheed here a little, I can imagine that we could have two event types.

```swift
public enum Event<Element, Failure: Error = Error> {
  case next(Element)
  case failure(Failure)
}

public enum CompletingEvent<Element, Failure: Error = Error> {
  case event(Event<Element, Failure>)
  case completed
}
```

If you look closer here you realize that we just added support for `Completion` as `Void` or `Never`. In fact we can go even one step further, as `Event` is simply the same as `Result`. The Swift community will likely extend the type with a default for the generic type `Failure` to `Result<Success, Failure: Error = Error>`, which is the exactly what we want here as well.

I can imagine (aside from slightly different names) that RxSwift could adopt such `Result` type as its `Event` type, and provide a wrapper to restore completeness.

```swift
// new `Event`-like type which does never complete
enum Result<Success, Failure: Error = Error> {
  case success(Success)
  case failure(Failure)
}

// revamped `Event` type 
enum CompletingResult<Success, Failure: Error = Error> {
  case result(Result<Success, Failure>)
  case completed
}
```

What do you think?

**Comment by freak4pc** [comment]
Changing Event to conform to a Result type doesn't make sense. `Event` is a ReactiveX core concept (`next`, `error`, `completed`) and it doesn't make sense to change it just to "save a type definition" :) 

About completion - It doesn't make much sense to complete with an Element. It should be either `Void` or `Never` to my understanding.

**Comment by DevAndArtist** [comment]
I understand your position but I strongly feel this is a historical quirk of ReactiveX from Microsofts side. If you watch this [video](https://www.youtube.com/watch?v=looJcaeboBY) you get a basic idea where this originates from.

From my point of view `next` is really a bad name as any new `Event` is *the next event* even if it's `.completed`. The new event has a `value`, an instance of a failure type or it equals the completion state. `error` is debatable, but if you look closer Microsoft uses it because their type is called `Exception` and not `Error` which makes things easier for them to reason about. (For the error case I would personally adopt the semantic meaning from `Result` and rename it to `Failure`).

One thing that I just remembered is that the above examples would not make sense from a sub-type relation. For an enum sub-type you will likely **remove** cases but not add them. If Swift gets typed throws they will likely [assume that everything throws](https://forums.swift.org/t/pitch-genericizing-over-annotations-like-throws/20376/10), every function/method/closure/accessor would by default throw. However if you omit the throw, the compiler will interpret it as `throws(Never)` and you get the current behavior back.

That would make `Event` into something like this:

```swift
enum Event<Value, Failure: Error = Error> {
  case value(Value)
  case failure(Failure)
  case completion

  @available(*, deprecated, message: "Use `value` instead.")
  static func next(_ value: Value) -> Event {
    return .value(value)
  }

  @available(*, deprecated, message: "Use `failure` instead.")
  static func error(_ value: Failure) -> Event {
    return .failure(value)
  }

  @available(*, deprecated, message: "Use `completion` instead.")
  static var completed: Event {
    return .completion
  }
}
```

So in the general case you would assume that every `Observable` can emit values, error out and complete.

You can then create instances with stronger guarantees and partly remove some of these behaviors.

```swift
// this could be a subtype of `Event<Value, Failure: Error = Error>`
enum NotCompletingEvent<Value, Failure: Error = Error> {
  case value(Value)
  case failure(Failure)
}
```

We can add extensions for the conversions between these types.

---

> About completion - It doesn't make much sense to complete with an Element.

Nearly every programming language has the `main` function which completes with a value. It's debatable whether this should be the case for RxSwift but a more generic solution would require this. However I think we can go the sub-type relation here and just remove case from the sub-type.

---

> Event to conform to a Result

Nitpicking here a little, I get what you mean, but technically this is not correct.

**Comment by freak4pc** [comment]
Starting from the end - I meant "conform" in the actual meaning of the word (e.g. "shoehorn" the event type into a result even though it doesn't represent the same thing), not the technical sense of protocol conformance. 

About the rest - I respect your opinion but I personally highly disagree. I think you are misinterpreting what this project is about. It's not about reinventing Reactive Programming. It's about providing the ReactiveX standard in a great Swift-centric API that follows the same standard across all of its platforms, which is one of the biggest promises of Rx in general. 

RxSwift's purpose isn't to steer away from Rx (unless we're talking about some operators or method names, but definitely not core concepts), but to provide this Swift-centric implementation that is understandable, stable and expectable. This is different than ReactiveSwift, for example, in the sense they're making their own API without regards to Rx specifically or any other standard (for better or worse). 

What you call a "historical quirk" is basically a standard. It's like you'll make a browser that decides HTML is outdated and would decide to make its own markup language. It might be "nice", but it's not practical or a good move. 

In general, I personally find the `next`, `error`, `completed` standard very simple and basically it just "makes sense", to me. 

This entire post is my personal opinion. I don't represent Krunoslav's vision or anyone else's, but this is how I teach Rx to people (it's a platform-agnostic standard), and the thoughts you share here are a large deviation from that IMO.

**Comment by freak4pc** [comment]
About completion subtype, that could basically be fine, I think. But it would be something that needs to be investigated for RxSwift 6, probably.

**Comment by DevAndArtist** [comment]
By "historical quirk" I meant to say that Swift has it's own guide for the naming conventions and the debate around `Result` clearly shows that in many many other libraries `value` and `error` cases were dominant, but that does not justify anything from my point of view. What I was trying to say, basically I tend to be close to the language guidelines rather than other standards. It's true that RxSwift follows the standard, but I highly doubt that it isn't allowed to slightly do things differently to be closer to the language it's implemented in and follow the language standards. Apple does also provide Objective-C API's re-written to follow the Swift naming guidelines rather than sticking to the old Objective-C established standards. 

As you also said, this is just my personal opinion. ;)

**Comment by freak4pc** [comment]
I think if you're building a cross-platform thing, the language is secondary to the "thing" you're building :) Anyways, not for me to decide but I definitely see no real value in making that kind of change.

**Comment by hfossli** [comment]
I agree with @freak4pc. The reason I choose RxSwift over frameworks like ReactiveCocoa is because the terminology is consistent across ios and android. Our android devs can coordinate closely and «speak the same language» when discussing how to implement features. We had a lot of confusion going with ReactiveCocoa because they chose other terminology as suited. 

Is it fair to say this discussion steered away a bit from the original topic? 

I like your ideas presented in the first post @devandartist

**Comment by freak4pc** [comment]
This thread has some really interesting insights, but - it is 3 years old and Swift's default generics isn't around the corner. This could likely be a RxSwift 7 feature is Swift's features progress accordingly. When the time comes we can revisit this thread or open a new one that links to this one.

Thanks to everyone who participated and for the great ideas!
