### ISSUE TITLE
Sink's disposing

### ISSUE THREAD

**Issue by KazuyaTomita** [ReactiveX/RxSwift#1321]
Now I am reading the internal inplementation of `Producer.swift` and `Sink<O : ObserverType>`.   And when the `dispose()` method of Producer is called, `sink.dispose()` should be executed.
And in `dispose()` in Sink<O : ObserverType>, `_cancel.dispose()` is called.  And to me, `_cancel `seems to be `Producer`.  So, I assume there should be infinite loop.  What of my explanation is wrong?

Could anyone help?

**Comment by kzaher** [comment]
Hi,

The only thing I can say is that if you do
```
let disposable = Disposables.create { print("Will only be printed once") }
disposable.dispose()
disposable.dispose()
```
That's why there isn't stack overflow. The rest is up to reading the code.

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
