### ISSUE TITLE
How to install RxCocoa in Xcode9 by Cocoapods.

### ISSUE THREAD

**Issue by tuchangwei** [ReactiveX/RxSwift#1333]
I am sorry, but anyone know how to install Rxcocoa in Xcode9?
I have installed RxSwift and built successfully:
`pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git',:branch => 'swift4.0-xcode9'`

Thanks.

**Comment by tailec** [comment]
pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git',:branch => 'swift4.0-xcode9'
pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git',:branch => 'swift4.0-xcode9'

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
all who are interested in development of this project and watching it are being spammed by irrelevant information.
those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.
Thank you for understanding.

Regardless of that, there is no problem doing label.rx.subscribe(onNext: { text in ... , Please make sure you imported RxCocoa.
