### ISSUE TITLE
Rx pattern in form handling

### ISSUE THREAD

**Issue by hassanrazakhalid** [ReactiveX/RxSwift#1359]
I am facing some issue when using Rx in form handling. Consider scenario where in form,  user can undo changes or after modifying the form he can reset it to original state. For Example. Consider the solution below. The drawback to this is all the attributes will have to be redefined in ViewModel as well. Or other way is to define Rx Variables in User Model firectly like var nameVar: Variable("") in user but then modifying values directly like this will loose the old values. or i can implement Copy Protocol where again alot of boilerplate code. Is there any better approach to solve this kind of issue
```
class User {
 var name: String = ""
var age: Int = 0
//more attributes
}

class UserVM {
var nameVar: Variable<String?>("")
var ageVar: Variable<String?>("")

func mapWithModel(user: User) {
name.value = user.name
name.age = user.age
// Similary all the attributes
}

func cellforRow(tableViw: UITableView, indexPath: IndexPath) {
// Here we will subscripe all the variables to cells either one or two way using <-> 
//Depends on requirement
}
}
```

**Comment by sergdort** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
