### ISSUE TITLE
How can hide or show based on multiple button actions.

### ISSUE THREAD

**Issue by santhoshs5** [ReactiveX/RxSwift#1372]
I have five buttons in VC and four buttons maintains isSelected property 
if either of the four button's isSelected is true I need to show the fifth button
otherwise i Need to hide it.

How can I achieve this ?

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by haritowa** [comment]
I was just about to answer :D
