### ISSUE TITLE
Unable to check if downstream is completed

### ISSUE THREAD

**Issue by lucas34** [ReactiveX/RxSwift#1380]
Hi,

I would like to stop emitting / forwarding event when using take(Int)

Questions:
1. How to check if observer is completed inside Observable.create() callback ?
RxJava provide a observableEmitter.isDispose(). In RxSwift, isDisposed does is different downstream completed.

2. Why items are forwarded to downstream when it's already completed ?
In this following example map operator will be call 2 unnecessary times. Similar code in RxJava will call map operator only once. 

```swift
Observable<Int>.create { observer in
     let disposable = Disposables.create {
         print("disposed")
     }
     for i in 0...3 {
         if disposable.isDisposed {
             break
         }
         print("Emitting \(i)")
         observer.onNext(i)
     }
     observer.onCompleted()
     return disposable
 }.map { i -> Int in
     print("map \(i)")
     return i * 10
 }.take(1)
 .subscribe()
```
Will output 
```
Emitting 0
map 0
Emitting 1
map 1
Emitting 2
map 2
Emitting 3
map 3
disposed
```

**Comment by kzaher** [comment]
Hi @lucas34 ,

The idea is that when you generate something long lived, you generate it in chunks of work on some scheduler. You can define those cancelable chunks of work by using `scheduleRecursive` method.

You can check out how we use it internally. For example in `from` extension. If you don't want to use any specific scheduler but just want to be able to divide the work you can use `CurrentThreadScheduler.instance`.

> How to check if observer is completed inside Observable.create() callback ?
RxJava provide a observableEmitter.isDispose(). In RxSwift, isDisposed does is different downstream completed.

You can't and you should care about this. Use recursive scheduling and this will work automatically.

> Why items are forwarded to downstream when it's already completed ?
In this following example map operator will be call 2 unnecessary times. Similar code in RxJava will call map operator only once.

Because you didn't use recursive scheduling and you didn't actually return that `disposable` from subscribe block before generating those elements.

RxJava uses a bit different model.

**Comment by lucas34** [comment]
Thanks for the clarifications.
