### ISSUE TITLE
Observable still receiving events after being disposed in cell

### ISSUE THREAD

**Issue by maasim94** [ReactiveX/RxSwift#1393]
i and using RxSwift for form handling in collectionView and tableView. I am facing an issue. I have a singleSelectionList Component
I am creating DisposeBag every time while configuring to remove all previous subscribers. onDisposed method is called for both but i still receive duplicate onNext events. This works fine in that start but when i reload CollectionView or tableView i am facing this issue. Please let me know is there something i am doing wrong or is this bug in library.

```
var selectedIndex = Variable<Int?>(nil)

func configureRx(sender: RxRow<Int>) {

dateVarDisposable = DisposeBag()
        
        selectedIndex
            .asObservable()
            .subscribe(onNext: {[weak self] (index) in
                self?.selectRow(selectedIndex: index)
                }, onDisposed: {
                    
                    print("")
            })
            .addDisposableTo(disposableBag)
        
     sender.dataVariable.asObservable()
        .debug(self.stringTag, trimOutput: false)
        .subscribe(onNext: { (sender) in
            
            self.selectedIndex.value = sender
        }, onDisposed: {
//            print("disposed 1")
        })
        .addDisposableTo(disposableBag)
        
    }
```

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
