### ISSUE TITLE
itemSelected not work.please help me.

### ISSUE THREAD

**Issue by danwey** [ReactiveX/RxSwift#1402]
let items = Observable.just([
            "First Item",
            "Second Item",
            "Third Item"
            ])
        
        items
            .bind(to: tableView.rx.items) { (tableView, row, element) in
                let cell = tableView.dequeueReusableCell(withIdentifier: "Cell")!
                cell.textLabel?.text = "\(element) @ row \(row)"
                return cell
            }
            .disposed(by: disposeBag)

        //this code not work
        tableView.rx.itemSelected.map {
            $0.item
            }.subscribe(onNext: { (index) in
                print(index)
            })
            .disposed(by:disposeBag)

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
