### ISSUE TITLE
How to make a `DelegateProxy` for a pure swift delegate protocol using RxSwift 4.0?

### ISSUE THREAD

**Issue by ufosky** [ReactiveX/RxSwift#1442]
When I upgrade to swift 4.0, I also upgrade `RxSwift` to `4.0.0-rc.0`.The `DelegateProxy` now need 2 type params, One for `ParentObject` type and one for `Delegate` type.But in my case some delegate type isn't conform to `NSObjectProtocol`, it's just a pure swift protocol,how can I use it as a `DelegateProxy`?

**Comment by kzaher** [comment]
Hi @ufosky ,

can you give me some use case how you would use it? Delegate proxy relies on objc message dispatching for interception.

**Comment by RamwiseMatt** [comment]
I have run into a similar issue. I had previously written a DelegateProxy for for a delegate protocol that does not conform to NSObjectProtocol. To avoid using objc message interception, the DelegateProxy implements the delegate protocol and uses PublishSubjects to forward the message (this makes it a "pure swift" solution.) Unfortunately, this no longer works in the new DelegateProxy design. Example error: `Type 'JTAppleCalendarViewDelegate' does not conform to protocol 'NSObjectProtocol'` As the delegate protocol is part of another library, my only solution now is to manually fork that library and force conformance to NSObjectProtocol. That's a highly unattractive solution.

**Comment by RamwiseMatt** [comment]
After some more research, I've found it's not even a possibility for me to force NSObjectProtocol compliance on the delegate protocol, since it then still throws compile-time errors unless I mark the protocol with the `@objc` decorator. That's not an option, because these protocol methods rely heavily on structs, which cannot be marked with `@objc`. An example error is:

`Using 'JTAppleCalendarViewDelegate' as a concrete type conforming to protocol 'NSObjectProtocol' is not supported`

Given that `DelegateProxy` worked fine with swift protocols until `rxSwift 4.0.0-beta.0`, I'm sure there is some way to make this possible again, though I'm at a loss at the moment.

**Comment by kzaher** [comment]
Hi @ufosky ,

can you please explain what do you mean by 
> Given that DelegateProxy worked fine with swift protocols until rxSwift 4.0.0-beta.0

Can you please provide some example code?

**Comment by kzaher** [comment]
I've removed all of the constraints for objc in c9f478a.

The problem is that it still doesn't solve the issue completely, so I've reported a compiler bug here:
https://bugs.swift.org/browse/SR-6173

I would ideally like to resolve and test this before releasing 4.0, but considering we need to release 4.0.0 as soon as possible I would not want to hold 4.x because of this.

If Swift compiler team doesn't fix this issue soon there are some reeeeeealy ugly workarounds that one can do to support Swift delegates.

**Comment by tarunon** [comment]
Hi there,
We cannot use pure swift protocol in conditional type parameter. It's not supported on swift 4.0.

```swift
protocol Animal {}
protocol Cat: Animal {}
@objc protocol Plants {}

struct Pass<T> {}
struct Fail<T: Animal> {}

Pass<Animal>.self // OK
Pass<Cat>.self // OK
Fail<Animal>.self // Compile error: Using 'Animal' as concrete type conforming to protocol 'Animal' is not supported
Fail<Cat>.self // Compile error:Using 'Cat' as concrete type conforming to protocol 'Animal' is not supported
Fail<Plants>.self // OK, @objc protocol can concrete type conforming.
```

The architecture of DelegateProxy is based on the behavior of NSObject, Objective-C. 
If use Delegate(not NSObject) in DelegateProxy, there are no way to make work well some of methods like `forwardDelegate`, `sentMessage`, `methodInvoked`. If don't use these feature, I think it doesn't need to use DelegateProxy.
NSObject(NSObjectProtocol) is part of Objective-C, not pure swift. I think that's make sense add `@objc` keyword if need.

@kzaher 
If we remove every conditional from DelegateProxy.Delegate, we can support any Delegate(without `@objc`), but if Delegate is not NSObject, then `forwardDelegate`, `sentMessage`, `methodInvoked` does not work. And DelegateProxy code will get many type casting again 😢 
In my opinion, it make confusing, the Delegate(not NSObject) make not work some of features like `forwardDelegate`, `sentMessage`, `methodInvoked`. 
So I suggest revert #1442, and if we want to solve this issue, it's better that add one more feature for pure swift. (I'm not sure what should we support on pure swift, but I think it will not be Proxy.)

**Comment by tarunon** [comment]
Hi there,
We cannot use pure swift protocol in conditional type parameter. It's not supported on swift 4.0.

protocol Animal {}
protocol Cat: Animal {}
@objc protocol Plants {}

struct Pass<T> {}
struct Fail<T: Animal> {}

Pass<Animal>.self // OK
Pass<Cat>.self // OK
Fail<Animal>.self // Compile error: Using 'Animal' as concrete type conforming to protocol 'Animal' is not supported
Fail<Cat>.self // Compile error:Using 'Cat' as concrete type conforming to protocol 'Animal' is not supported
Fail<Plants>.self // OK, @objc protocol can concrete type conforming.
The architecture of DelegateProxy is based on the behavior of NSObject, Objective-C.
If use Delegate(not NSObject) in DelegateProxy, there are no way to make work well some of methods like forwardDelegate, sentMessage, methodInvoked. If don't use these feature, I think it doesn't need to use DelegateProxy.
NSObject(NSObjectProtocol) is part of Objective-C, not pure swift. I think that's make sense add @objc keyword if need.

@kzaher
If we remove every conditional from DelegateProxy.Delegate, we can support any Delegate(without @objc), but if Delegate is not NSObject, then forwardDelegate, sentMessage, methodInvoked does not work. And DelegateProxy code will get many type casting again 😢
In my opinion, it make confusing, the Delegate(not NSObject) make not work some of features like forwardDelegate, sentMessage, methodInvoked.
So I suggest revert bb83428, and if we want to solve this issue, it's better that add one more feature for pure swift. (I'm not sure what should we support on pure swift, but I think it will not be Proxy.)

**Comment by tarunon** [comment]
Oh,,, if some Delegate has struct/enum/generics function, it's cannot add `@objc` keyword.
```swift
protocol MyDelegate: NSObjectProtocol {
  func foo<A>(_ arg: A)
}
```

**Comment by RamwiseMatt** [comment]
@tarunon I think that you overestimate the amount of reliance there is on `methodInvoked` or `sentMessage`. I, and others, have been using DelegateProxy in combination with PublishSubjects to reproduce the same sort of behavior. There is no need to create a whole new set of classes to facilitate Swift delegates, because it's much more attractive to keep things under the same roof and to offer a uniform interface.

Beyond that, I don't currently see why you would need a lot of extra casts just because the DelegateProxy accepts `AnyObject` instead of `NSObject`. As you can see in the code now, there is simply an optional call to the `responds` selector, and that's all the casting that is required (I think).

The following should definitely work, but would definitely not if we revert as you propose:

```
import JTAppleCalendar
import RxSwift
import RxCocoa

extension JTAppleCalendarView: HasDelegate {
	public typealias Delegate = JTAppleCalendarViewDelegate
}

internal class RxJTAppleCalendarDelegateProxy
	: DelegateProxy<JTAppleCalendarView, JTAppleCalendarViewDelegate>
	, DelegateProxyType
	, JTAppleCalendarViewDelegate {
	
	internal init(parentObject: JTAppleCalendarView) {
		super.init(parentObject: parentObject, delegateProxy: RxJTAppleCalendarDelegateProxy.self)
	}
	
	internal static func registerKnownImplementations() {
		self.register { RxJTAppleCalendarDelegateProxy(parentObject: $0) }
	}
	
	internal lazy var didSelectPublishSubject = PublishSubject<(date: Date, cell: JTAppleCell?, cellState: CellState)>()
  
	// This is a method that is part of the JTAppleCalendarViewDelegate. 
	// The intent here is to forward any calls to this method.
	internal func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
		didSelectPublishSubject.on(.next((date: date, cell: cell, cellState: cellState)))
		
		(self.forwardToDelegate() as? JTAppleCalendarViewDelegate)?.calendar(calendar, didSelectDate: date, cell: cell, cellState: cellState)
	}
		
	deinit {
		didSelectPublishSubject.on(.completed)
	}
}
```

The fact that it doesn't currently work, even after the changes kzaher made, is apparently due to a Swift compiler bug. But this is a valid use-case and should not be ignored.

**Comment by ufosky** [comment]
I have use `DelegateProxy ` with pure swift protocol in RxSwift 3.x. It's use `PublishSubject` like the example given by @RamwiseMatt. But now I can't find any way to reach this in RxSwift 4.0.

**Comment by tarunon** [comment]
This behavior(maybe bug?) comes from Swift2, but still exist in Swift4. 
Here is first report. https://bugs.swift.org/browse/SR-55
I think they cannot fix it immediately.
Ideally DelegateProxy.Delegate should be as a NSObjectProtocol, but compiler not support it.
So we only can check it in runtime.

Maybe there are 2 tasks for fix this issue.
- Remove type conditional of `DelegateProxy.Delegate`, and check `NSObjectProtocol` conformance in runtime.
- Add one more feature like DelegateProxy for pure swift Delegate(not conform NSObjectProtocol).

## about `NSObjectProtocol` conformance

In my imagine, best way is a checking NSObjectProtocol conformance in DelegateProxyFactory, but we cannot check 2 protocols conformance using Type in Swift4.

```swift
protocol Animal {}
protocol Cat: Animal {}
class Dog: Animal {}

Dog.self is Animal.Type // true
Cat.self is Animal.Type // swift 3.2 true, swift 4.0 false
```
I reported it, https://bugs.swift.org/browse/SR-6191
We can check conformance only using value, not type. 
Maybe `castOptionalOrFatalError`/`castOrFatalError` is good.


## about Delegate that is not conform NSObjectProtocol 

It should not support `forwardToDelegate`, `sentMessage`, `methodInvoked` they need NSObjectProtocol feature.
If we remove DelegateProxy's conformance, maybe we can change behavior dynamical, and already work well.(Because it worked well in RxSwift 3)

**Comment by tarunon** [comment]
I try to make patch, it seems work well.
@kzaher Maybe I think this way is *reeeeeealy ugly workarounds* that you said. How do you think?

**Comment by kzaher** [comment]
@tarunon I think it could work.

**Comment by bobgodwinx** [comment]
@kzaher @tarunon I am a huge fan of `DelegateProxy` but in this case I would like to say we have a language limitation here and I think we should not implement this feature until we have a clear understanding of what `AnyObject` does under the hood because I ran into a similar problem I had to fall back to the imperative implementation for that. `AnyObject` is not guaranteed. Take a look at this:
`
/// When you use `AnyObject` as a concrete type, you have at your disposal
/// every `@objc` method and property---that is, methods and properties
/// imported from Objective-C or marked with the `@objc` attribute. Because
/// Swift can't guarantee at compile time that these methods and properties
/// are actually available on an `AnyObject` instance's underlying type, these
/// `@objc` symbols are available as implicitly unwrapped optional methods and
/// properties, respectively.
`

**Comment by kzaher** [comment]
@bobgodwinx This is kind of a tradeoff I guess.

I'm not in favor of any hacks.

I've tried to adapt the solution @tarunon proposed in the simplest way possible.

The current behavior seems like a good compromise to me. There are unfortunately a lot of combinations possible, but we can simplify them to two cases:
* protocol is a Swift protocol
* protocol is an ObjC protocol

If we have a delegate proxy that implements a Swift protocol, one needs to implement all delegate methods and forwarding manually because as far as I can tell Swift protocols can't have optional methods. 
That means that forwarding machinery won't be touched, and the only method as far as I can tell that will be called is `responds(to:)`. The good thing is that it will be called on every setting of delegate proxy forwarding delegate.
As far as I can tell, and unit tests seem to confirm that, it doesn't crash if the object is not inheriting from `NSObject`.
```
final class MockPureSwiftDelegate: PureSwiftDelegate {
    var latestValue: Int?

    func delegateTestIt(with: Int) {
        latestValue = with
    }
}
```
There is also a warning error generated in case somebody wants to use `messageSent` or `methodInvoked` with Swift delegates.

If protocol is an ObjC protocol, then everything works as before.

> I am a huge fan of DelegateProxy but in this case I would like to say we have a language limitation here and I think we should not implement this feature until we have a clear understanding of what AnyObject does under the hood because I ran into a similar problem I had to fall back to the imperative implementation for that.

Could you maybe provide some examples of the problems you've encountered and check can you reproduce them with current code in `develop` branch?

**Comment by bobgodwinx** [comment]
@kzaher Thanks for getting back. I am currently working now from the `develop` branch and I will let you if I come across any errors. However we can live this compromise. I took a look into the `Specs` it seem good but we need to add more. I might send you a PR with more `specs` for that as soon as I get my hands free.
