### ISSUE TITLE
Can't bind ObservableType to BehaviorRelay

### ISSUE THREAD

**Issue by biboran** [ReactiveX/RxSwift#1466]
**Short description of the issue**:

It's not possible to bind ObservableType to BehaviorRelay as it was possible to bind ObservableType to Variable. 

**Expected outcome**:

Since BehaviorRelay is considered a replacement for Variable, it should offer a hassle free migration. ObservableType should know how to bind itself to BehaviorRelay since that's the intention of `bind(to:)` method.  

**Self contained code example that reproduces the issue**:

```swift
//This doesn't compile
Observable.just(false).bind(to: BehaviorRelay(value: true))
//This still compiles
Observable.just(false).bind(to: Variable(true))
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
9.0.1
```

**Comment by kzaher** [comment]
Ok, we can add that API.

**Comment by dakeshi** [comment]
@kzaher Additionally, it needs to give a waring message. ex) Variable is deprecated. Renamed to BehaviorRelay.

**Comment by kzaher** [comment]
@dakeshi We've for now only put `Variable` in `Deprecated.swift` because it's meant to be deprecated in the following version.

We haven't marked it deprecated right now because I'm assuming people will have hard time migrating to 4.0 APIs, and unfortunately I'm assuming that there is a lot of `Variable` usage.

We wanted to help people for now by just informing them about the deprecation. It is possible we'll move `Variable` in `RxCocoa` in the following version and just do `typealias Variable = BehaviorRelay`. 

That would enable newcomers to find relays more easily and we would have some consistency with behavior and publish relays.

We still haven't decided how exactly we'll deprecate `Variable`, so this is just preparation for that move.

When the exact deprecation path is decided, we'll potentially add deprecation warnings if that API will be moved completely or in case of `typealias` we'll just perform the move to `RxCocoa` without deprecation warnings.

**Comment by dakeshi** [comment]
@kzaher Thanks for your detailed response. 

What I feel strange is `something which will be deprecated is placed in Deprecated.swift`
Your intension is`Variable` will be deprecated but someone could understand `Variable` is deprecated.

And how do developers or new comers know `Variable` will be deprecated?
From Issue? Release page description? or Slack channel?
To make clear and smooth transition, I think a document should update to provide this info.
It is very helpful to add how to handle some deprecation methods or your plan to handle this(migration guide would be a good name) you mentioned  in [docs](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md) or README file.

**Comment by kzaher** [comment]
I can't think of a better way of informing people some API **will** be deprecated than adding it to a file named `Deprecated.swift`. People don't read docs a lot as far as I can tell.

When migration path is decided it will get it's `availability` attribute and become deprecated.

**Comment by hmlongco** [comment]
If the current thinking is that Variable will be replaced by BehaviorRelay, will BehaviorRelay move to RxSwift from RxCocoa?

This would smooth migration as all of the current files that use Variable import RxSwift and not RxCocoa.

**Comment by RomuloBitten** [comment]
This same issue are occurring with me on RxSwift. I'm using version 5.1.1

**Comment by freak4pc** [comment]
Definitely unlikely since se have [bind to relay overloads since 2019](https://github.com/ReactiveX/RxSwift/blob/0efa6d1482ddaea12d63f4f17567daa4744c7420/RxRelay/Observable%2BBind.swift)

**Comment by RomuloBitten** [comment]
> Definitely unlikely since se have [bind to relay overloads since 2019](https://github.com/ReactiveX/RxSwift/blob/0efa6d1482ddaea12d63f4f17567daa4744c7420/RxRelay/Observable%2BBind.swift)

I'm experiencing this issue, or something similar.

```
let observable: Observable<[MyCustomObject]> = Observable.just(myObjectsList))
observable.bind(to: self.myCustomObjectList) // that line throws the error " Cannot invoke 'bind' with an argument list of type '(to: BehaviorRelay<[MyCustomObject]>)' "
```
