### ISSUE TITLE
BehaviorRelay is a part of RxCocoa shouldn't it be a part of RxSwift?

### ISSUE THREAD

**Issue by sandeeplearner** [ReactiveX/RxSwift#1502]
**BehaviorRelay is a part of RxCocoa, shouldn't it be a part of RxSwift**:

I was trying to access BehaviorRelay in my swift file, as I had already imported RxSwift. Could not access it and had no clue as to where to search for it. I finally realized that BehaviorRelay is a part of RxCocoa and not RxSwift

**Expected outcome**:
As all other subjects are a part of RxSwift BehaviorRelay should also be a part of RxSwift

**What actually happens**:
The statement that BehaviorRelay is a alternate to Variable confuses more, as Variable was a part of RxSwift. Its more instinct that BehaviorRelay must be a part of RxSwift. As documention isn't clear about it, creates a great confusion as to where to find it

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

`RxSwift (4.0.0)
`
**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [x] extremely hard, %0 - 2%

**Xcode version**:

```
  Version 9.1 (9B55)
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by kzaher** [comment]
Hi @sandeeplearner ,

No, `BehaviorRelay` is not a "standard" concept and it's more suited for stateful environments only.

We will be moving `Variable` out of `RxSwift` and probably making it just a typealias in `RxCocoa`. #1501

> As all other subjects are a part of RxSwift BehaviorRelay should also be a part of RxSwift

This is not a subject because it's not an observer.

**Comment by sandeeplearner** [comment]
@kzaher : 

> This is not a subject because it's not an observer.

Sorry am a noob in RxSwift. So did not really realize that it is a observer. I was confused by the statement that `BehaviorRelay` will be a alternate to `Variable`. I took it quite literally I thought as `Variable` was a subject `BehaviorRelay` will also be a relay. Thank you for informing 

> No, BehaviorRelay is not a "standard" concept and it's more suited for stateful environments only.

Sorry forgive me for my dumb question, but don't you think RxCocoa should have Rx implementation for Cocoa components only and have non-cocoa and language specific components in RxSwift? At least name is little intuitive in that way.

For example, lets consider Foundation and UIKit frameworks,
I would not go and search for `UITextField` in Foundation framework I know its a UIComponent hence should be a part of UIKit but on the other hand I would not look for `Array` in UIKit. 
 
That way figuring out where each component of programming lies becomes easy. Variable/BehaviorRelay can be used absolutely in isolation from UI components hence thought should be a part of RxSwift.

Just a thought :)

**Comment by kzaher** [comment]
Hi @sandeeplearner ,

> Sorry forgive me for my dumb question, but don't you think RxCocoa should have Rx implementation for Cocoa components only and have non-cocoa and language specific components in RxSwift? At least name is little intuitive in that way.

ideally, yes, I would agree with you. However there are some practical problems to consider:
* tooling support for packaging is quite bad in Xcode (compared to intellij or android studio) -> we'll receive complaints of type, do I really need to type 3+ times import XXX just to use this, already had in past.
* Carthage will build RxSwift additionally every time for each of the libraries inside this repo that depends on RxSwift (we've received plenty of complaints about this in the past even though this isn't an issue with the project itself)
* We'll probably receive more complaints of this form
> Could not access it and had no clue as to where to search for it.

... because we can't name those additional libraries in such a way that perfectly describes their content.
* we were discussing separating all traits into their own library, but couldn't find any practical benefits at the time
* at the time or writing I can't imagine somebody using `*Relay` server side with RxSwift or Linux and if they are using it in some mobile or desktop app, they already need to import RxCocoa, so what's the real benefit there? (maybe this will change in future)

But I never say never.

**Comment by hmlongco** [comment]
Agree with sandeeplearner in that Variable was defined in RxSWift, and its replacement (if any) should also be in RxSwift.

Variable (and BehaviorRelay) are most definitely NOT UI components. Yes, you can bind them to UI components (and that binding could be in RxCocoa) but the concept can definitely be used anywhere in model and service-level code.

Further, I also take exception to simply moving Variable AND BehaviorRelay to RxCocoa. While we do import RxCocoa in our financial app, we only do so in the ViewControllers and other UI-based elements that need it.

Models, ViewModels, and Service files have all used Variable, and since they all know nothing about UI elements, those files import RxSwift ONLY. Why require modification of dozens upon dozens of source files to import yet another module that supports UI elements they shouldn't even know about?

**Comment by Krisiacik** [comment]
Totaly agree with @hmlongco ..I ahve pretty much the same situation and component relatioships.
ViewModel components use RxVariables to store temporary mutable state.

**Comment by kzaher** [comment]
The purest approach would be to extract relays into `RxRelay` framework, `Driver` and `Signal` into `SharedSequence` framework and remove `Variable` completely.

I can understand the puristic approach, and separating concepts into their own self contained frameworks with small public API, but I would like to avoid creating, maintaining, importing and using two additional micro frameworks for puristic sake without any obvious benefits.

If I were to choose where to put relays, I would definitely pick RxCocoa for now because they are stateful convenience wrappers. They don't make any sense when using RxSwift in server side environment, they aren't cross platform and are just simple wrappers that one could recreate themselves if needed without even importing RxCocoa ... any yes, I understand what are the drawbacks of that approach and I'm not pretending there aren't any compromises.

**Comment by hmlongco** [comment]
Variables and Relays may not make any sense from a purist's perspective, but many people don't approach Rx in quite that fashion. Consider...

```
class TokenTracker {
    let tokens = Variable([String]())
    func trackToken(_ t: String) {
        tokens.value.append(t)
    }
}
```
Here I have a set of tokens that I'm managing, while at the same time automatically exposing changes to that set to any observers who may be interested in those changes.

It's not Rx from the purist's perspective, but it's pretty good Swift. Note that I quite literally can **not** make any changes to my token list without that change being broadcast. The code's bulletproof. Add another function to remove a token, and the code's still bulletproof.

Contrast with...

```
class TokenTracker {
    var tokens = [String]()
    let changed = PublishSubject<Bool>()
    func trackToken(_ t: String) {
        tokens.append(t)
        changed.onNext(true)
    }
}
```

Not only do I have to maintain state separately, but I have to remember to explicitly fire the changed event for each and every operation. I had to write twice as much code, and it's more fragile than the original.

I could be more Rx'y, I suppose....

```
class TokenTracker {
    var tokens = [String]()
    let addToken = PublishSubject<String>()
    private let disposebag = DisposeBag()
    init() {
        addToken.subscribe(onNext: { [weak self] (t) in
            self?.tokens.append(t)
        })
        .disposed(by: disposebag)
    }
}
```

Which effectively provides the same functionality, with even more overhead (DisposeBag), and with nearly 3x the code over the original version.

All of which boils down to three things: 

1) There's more than one way to use RxSwift.
2) Variable performs a useful function that's *not* solely tied to driving UI controls.
3) Swift is Swift.

Yes. The semantics differ on Swift. So what? Swift, as you may have noticed, is a different language than Java, JavaScript, C#, and the others.

**Comment by kzaher** [comment]
@hmlongco 

> It's not Rx from the purist's perspective, but it's pretty good Swift. Note that I quite literally can not make any changes to my token list without that change being broadcast. The code's bulletproof. Add another function to remove a token, and the code's still bulletproof.

Variable wraps `BehaviorSubject` not `PublishSubject`. I'm not sure what point did you try to make.

> The code's bulletproof.

No it's not. It's quite the opposite. If you call `trackToken` from multiple schedulers simultaneously that's undefined behavior since that's not a valid sequence (even though the program won't crash).

Please give me benefit of a doubt that I understand this subject :)))

> There's more than one way to use RxSwift.

Sure, but you can always improve each of those ways somehow. I'm trying to tell you how should you use RxSwift, I'm trying to explain what is the rationale why some APIs are they way they are at the moment and also what are the tradeoffs of some other solutions we've considered.

The way to be constrictive about this discussion is to provide some new insights and tradeoffs of already considered scenarios or suggest new scenarios and enumerate their tradeoffs.

> Variable performs a useful function that's not solely tied to driving UI controls.

Again, I'm not sure you've read my answers carefully. This is still a stateful environment you are describing, so yes, there are user controls somewhere near there. Chances you could use that code in server side stateless environment is 0 IMHO.

> Swift is Swift.

I agree with tautology.

**Comment by kzaher** [comment]
We'll address this in #1501 .
