### ISSUE TITLE
Issues with CurrentThreadScheduler while updating from RxSwift 2.0.0-alpha.2 to RxSwift 2.0.0-alpha.3

### ISSUE THREAD

**Issue by torstenlehmann** [ReactiveX/RxSwift#151]
Using `subscribeNext()` on an observable on main thread:
```
someObservable.subscribeNext { [weak self] in
    // do something
}.addDisposableTo(disposeBag)
```

I get console output:
`*** setObjectForKey: object cannot be nil (key: <RxSwift.CurrentThreadSchedulerKey: 0x600000000800>)`

It does not crash, but observation did not work also.

Maybe it's a problem in `Producer.swift`.

https://github.com/ReactiveX/RxSwift/blob/428cc453bbd4b3301efcd55c92585178ae17032f/RxSwift/Observables/Implementations/Producer.swift#L30-L41

In alpha.2 it exectues the code of then branch from alpha.3 (alpha.2 only had the code of then branch of alpha.3). In alpha.3 it executes the else branch.

**Comment by kzaher** [comment]
Hi :),

that's weird.

That line of code you are referencing looks actually correct to me :)

Is this the line where you see that warning?
https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/CurrentThreadScheduler.swift#L91

Can you help me answer a couple of questions because I cant repro it.
* Can you repro the same issue on develop branch?
* Can you send me call stack when that warning is being printed (assuming it happens when code hits [here](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Schedulers/CurrentThreadScheduler.swift#L91))
* Do RxExample apps run correctly in your case?
* Can you paste mi minimal code sample that causes that :)
* In what environment are you experiencing that issue?

I know list of questions is fairly long, but need a way to figure it out :)

**Comment by torstenlehmann** [comment]
You are fast! :+1: 

> Can you repro the same issue on develop branch?

yes

> Can you paste mi minimal code sample that causes that :)

There was more in the chain!

        Variable(1)
            .map { $0 == 0}
            .subscribeNext {
                print("someMappedVar: \($0)")
            }

Omitting the map operator makes the console output disappear.

**Comment by kzaher** [comment]
Hi @torstenlehmann ,

I've investigated behavior of the code you've pasted :) It's hard to tell at first glance, but the described behavior is actually correct :)

We've changed behavior of `Variable` in RxSwift 2.0 to be more ARC friendly.

From variable documentation

/**
Variable is a wrapper for `BehaviorSubject`.

Unlike `BehaviorSubject` it can't terminate with error.

Before variable is deallocated, `Completed` event will be sent to all observers.
*/

What happens is that `Variable` is getting deallocated before `subscribe` is being called.
-> Completes the sequence before subscription is being made.

We've added that behavior so that when you don't reference variable from anywhere anymore, it will release all resources :)

If you do
```
let variable = Variable(1)

variable.map { $0 == 0}
        .subscribeNext {
            print("someMappedVar: \($0)")
        }
```

If you look at it, if makes sense that if nobody has reference to change the variable from anywhere, that the sequence isn't completed :)

This also works as expected :)

```
BehaviorSubject(value: 1)
            .map { $0 == 1 }
            .subscribeNext {
                print("someMappedVar: \($0)")
            }
            .dispose()
```

We've added `Variable` to wrap the `BehaviorSubject` as a convenience because RxSwift has that ARC component also :)

Hope this makes sense :)

As far as for that terminal output, that isn't nice output indeed.

I will change `NSThread.currentThread().threadDictionary[CurrentThreadSchedulerKeyInstance]` to be `NSThread.currentThread().threadDictionary.removeObjectForKey(CurrentThreadSchedulerKeyInstance)`.

Can you tell me on which environment is that warning appearing so I can test fix for that warning?

I'm assuming this was just a short example doesn't really describe your original problem :), so back to square one :)

**Comment by torstenlehmann** [comment]
> Can you tell me on which environment is that warning appearing so I can test fix for that warning?

- OS X 10.10
- Xcode Version 7.0 (7A218)

> What happens is that Variable is getting deallocated before subscribe is being called.

I don't understand this point. Doesn't `subscribeNext()` blocks until current value of Variable is send? This would prevent deallocation of Variable until stack unwinds.

Why does it work without warning in Alpha 2?

Why does it only occur if I omit the `map` operator?

> I'm assuming this was just a short example doesn't really describe your original problem :)

Yes. My original problem holds a strong reference to Variable (as far as I can tell).

**Comment by kzaher** [comment]
@torstenlehmann,

> I don't understand this point. Doesn't subscribeNext() blocks until current value of Variable is send? This would prevent deallocation of Variable until stack unwinds.

Until `subscribeNext` call, you are declaring sequence, and nothing is holding reference to `Variable` as a container to `BehaviorSubject`, that's why it completes.

So when you subscribe, you get completed event immediately.

This is how you debug what's happening:

```
Variable(1)
            .map { $0 == 1 }
            .debug()  // <- prints events, or use `subscribe(print)` instead of `subscribeNext`
            .subscribeNext {
                print("someMappedVar: \($0)")
            }
            .dispose()
```

> Why does it work without warning in Alpha 2?

Warning has nothing to do with these changes, but with trampoline schedulers :) It's correlation, but not causation :)

Unfortunately, I don't get the same warning like you do

OSX 10.10.5 (14F27)
Version 7.0 (7A220)

But I think I how what would fix it, so I would please like your confirmation after I try to fix this warning that it does work on your system :)

> Why does it only occur if I omit the map operator?

`subscribeNext` retains reference to `Variable` while in the same stack frame immediately calling `subscribe` before it exists the stack frame.

That was kind of a weird way of using `Variables`, that's why you've ran into this. You would probably use `just` operator in that scenario.

```
just(1)
            .map { $0 == 0 }
            .subscribeNext {
                print("someMappedVar: \($0)")
            }
            .dispose()
```

This works fine in all cases.

@torstenlehmann my intentions to complete the sequence on dealloc where lead by good intentions, but I've accidentally created in that case what I hate, interface that looks similar, but behaves differently :(

I think I'll remove that `.Completed` behavior for now because it could confuse people. It even confused me initially when I've seen your code and had to think about it, which is not good :)

All that being said, I still don't know what is the original problem you are having :)

I can make those fixes, and you can try it out and we can see if that helps :)

**Comment by torstenlehmann** [comment]
Thanks for your detailed answer! I could not grasp every detail of it because I'm new to RxSwift. I understand your intention to further improve automatic resource management. For the beginner it is best that there is one pattern that works all the time. I think the dispose bag is already sufficient by now?

> All that being said, I still don't know what is the original problem you are having :)

This one presents my problem in detail. Looking forward to your answer. :)

## Without map operator

```swift
import Cocoa
import RxSwift

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
    
    let variable = Variable(1)
    
    func applicationDidFinishLaunching(aNotification: NSNotification) {
        variable
            .subscribeNext {
                print("value: \($0)")
        }
        
        print("still alive")
    }
    
}
```

**Console Alpha 2:**

```
value: 1
still alive
```

**Console Alpha 3:**

```
value: 1
still alive
```

For me both alphas work as expected in this case.

## With map operator

```swift
import Cocoa
import RxSwift

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {
    
    let variable = Variable(1)
    
    func applicationDidFinishLaunching(aNotification: NSNotification) {
        variable
            .map { $0 == 1 }
            .subscribeNext {
                print("value: \($0)")
        }
        
        print("still alive")
    }
    
}
```

**Console Alpha 2:**

```
value: true
still alive
```

**Console Alpha 3:**

```
value: true
*** setObjectForKey: object cannot be nil (key: <RxSwift.CurrentThreadSchedulerKey: 0x608000002960>)
```

Alpha 3 does not work as expected for me. "still alive" is not printed, although Variable is kept as stored property.

**Comment by kzaher** [comment]
@torstenlehmann ,

I've made a branch for you that tries to fix that warning.

`feature/fix_current_thread_scheduler`.

Could you please try to see if that works properly :) I still can't repro it, but I'm assuming what's causing the issue :(

**Comment by torstenlehmann** [comment]
results using commit 152d7ea378d2e890aaff34b4244c4d9247ac7467:

**Console without map operator**

```
value: 1
still alive
```

**Console with map operator:**

```
Before removing object
After removing object
value: true
Before removing object
After removing object
still alive
```

Seems to work :+1:

**Comment by kzaher** [comment]
Great, then I'll remove those test prints and push this to develop. 

Wanted to be sure we have understanding what's happening in case this didn't work :)

**Comment by torstenlehmann** [comment]
For my own understanding:

What exactly is removed before value is posted?

**Comment by kzaher** [comment]
This was piece of code 
```
set {
   print ("Before removing object")
            let threadDictionary = NSThread.currentThread().threadDictionary
            if let newValue = newValue {
                threadDictionary[CurrentThreadSchedulerKeyInstance] = newValue
            }
            else {
                threadDictionary.removeObjectForKey(CurrentThreadSchedulerKeyInstance)
            }
    print("After removing object")
        }
```

I've named those prints wrong, more proper name should have been "before setting current thread scheduler", "after setting current thread scheduler".

I wanted to be sure that if there was that print out again, it was appearing between those two prints.

The first batch is when we register instance of "CurrentThreadScheduler" temporarily for current thread.
The second batch after is called when "CurrentThreadScheduler" is unregistered from current thread.

"CurrentThreadScheduler" is also called trampoline scheduler and it enables generate operators to work seamlessly.

This enables unbounded generate operators to work correctly with termination operators, so you can do.

```
repeatElement(0).take(3).subscribeNext { ... }
```

Hope this clears things :) I'll try to additionally document all of this.

**Comment by kzaher** [comment]
Fix for this has just been released :)
