### ISSUE TITLE
tableview + webview.delegate,cell Button click event

### ISSUE THREAD

**Issue by bianxu** [ReactiveX/RxSwift#1516]
*If you still want to report issue, please delete above statements before submitting an issue.*

**Short description of the issue**:

tableview + webview.delegate = self，cell Button click event

**Expected outcome**:

Button click on a trigger event once

**What actually happens**:

Click the button to trigger the event two times

**Self contained code example that reproduces the issue**:

```swift
  code goes here

 let tableView = UITableView.init(frame: .zero, style: .plain)
        tableView.delegate = self
        tableView.dataSource = self
        self.view.addSubview(tableView)
   _webView.frame = CGRect.init(x: 16, y: 0, width: Width - 32, height: 1)
        self.view.addSubview(_webView)
        _webView.delegate = self
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
///
cell.phoneButton?.rx.controlEvent(.touchUpInside).subscribe({
                (event) in
                print("tel")
            }).disposed(by: disposeBag)
///
}

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 4.0.0

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

9.1

**Installation method**:
  - [ ] CocoaPods

**Comment by biboran** [comment]
It will trigger as many times as the cell is dequeued. You have to define a disposeBag in your cell and either bridge the tap with a `Subject` or expose a `DisposeBag`. Take a look at [this answer](https://stackoverflow.com/a/41099315/6407425).

**Comment by bianxu** [comment]
The problem remains, DisposeBag is added to the cell；if webleView.delegate = nil,no problem； if =true，Click on the two times。。。

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
