### ISSUE TITLE
Request a question about the flatMapLatest request network

### ISSUE THREAD

**Issue by ETmanwenhan** [ReactiveX/RxSwift#1524]
Disconnect the network, the first request failed, then the click button will not send the network request? How to solve this problem, help me!

```swift
/// 登录逻辑
    func login() {
        
        //校验
        let validPhone : Observable<Bool> = number1.rx.text.orEmpty.map{ text in text.count > 5 }
        let validPsw : Observable<Bool>   = number2.rx.text.orEmpty.map{ text in text.count > 5 }
        
        //控制按钮
        let validBtn: Observable<Bool> = Observable.combineLatest(validPhone, validPsw){ validPhone, validPsw in validPhone && validPsw}
        validBtn.bind(to: btn.rx.isEnabled).disposed(by: disposeBag)
        
        //输入内容
        let input :Observable<(String,String)> = Observable.combineLatest(number1.rx.text.orEmpty, number2.rx.text.orEmpty){ (name, psw) in (name, psw) }
        
        //发起登录
        btn.rx.tap.withLatestFrom(input)
            .do(onNext: { _ in
                    SVProgressHUD.show(withStatus: "处理中...")
                }, onError: { error in
                    SVProgressHUD.showError(withStatus: error.localizedDescription)
                }, onCompleted: {
                    SVProgressHUD.dismiss()
                    Loger.log(msg: "onComplete")
                })
            .flatMapLatest(viewModel.login)
            .debug()
            .subscribe(onNext: { [weak self] user in
                    SVProgressHUD.dismiss()
                    Loger.log(msg:user)
                    self?.router.pushReg()
                }, onError: { error in
                    SVProgressHUD.showError(withStatus: error.localizedDescription)
            })
            .disposed(by: disposeBag) 
  
    }


```

```swift
 public func login(phone:String, password:String) -> Observable<User?> {
        
        Loger.log(msg: "phone:\(phone) password:\(password)")
        
        let psw = "123456"
        return Model().request(UserAPI.login(phone:"13500000001", psw:psw), Msg<User>.self).map{$0.obj as? User}
     
    }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift (4.0.0)

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
Xcode 9.2
```

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  - [x] no

**Level of RxSwift knowledge**:
  - [x] I have a small code base

**Comment by CepheusSun** [comment]
in this case when this request failed, the error event would be emitted, and then this  observable would been disposed, so when you tap the button again there is no event been emittd

**Comment by ETmanwenhan** [comment]
@CepheusSun  How to solve the problem?

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
