### ISSUE TITLE
[ASK] What is different from FlatMap and DoNext

### ISSUE THREAD

**Issue by alfian0** [ReactiveX/RxSwift#1542]
Hi, I still learn Reactive Programing and I still confusing about some API on RxSwift. When I read documentation FlatMap and DoNext give same return Observable but I still confusing about right implementation, when I need use FlatMap and when I use DoNext ? some article says that DoNext for side effect like save something that mean FlatMap and DoNext have different trait ? Can some one explain me about this ?

**Comment by MarcSteven** [comment]
“Side effects are any change to the state outside of the current scope. For example, consider the last piece of code in the example above. connectUIControls() probably attaches some kind of event handler to some UI components. This causes a side effect, as it changes the state of the view: the app behaves one way before executing connectUIControls(), and differently after that.”
FlatMap is combine operation ,you must remember “remember that side effects can be performed with the do(onNext:) operator”.
The FlatMap operator transforms an Observable by applying a function that you specify to each item emitted by the source Observable, where that function returns an Observable that itself emits items. FlatMap then merges the emissions of these resulting Observables, emitting these merged results as its own sequence.

This method is useful, for example, when you have an Observable that emits a series of items that themselves have Observable members or are in other ways transformable into Observables, so that you can create a new Observable that emits the complete collection of items emitted by the sub-Observables of these items.

Note that FlatMap merges the emissions of these Observables, so that they may interleave.

**Comment by alfian0** [comment]
Oh I know, I just read this article
[Learn & Master ⚔️ the Basics of RxSwift in 10 Minutes](https://medium.com/ios-os-x-development/learn-and-master-%EF%B8%8F-the-basics-of-rxswift-in-10-minutes-818ea6e0a05b)
on flatMap we can transform Observable to new Observable form but on doOn(next: ) we can't transform current Observable / **no effect on the actual subscription**, it's just like we hold side effect until we subscribe the observable

thanks for the answer @MarcSteven 👍, I miss at read the doc

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
