### ISSUE TITLE
Feature request: zipLatest operator

### ISSUE THREAD

**Issue by entropious** [ReactiveX/RxSwift#1585]
Was searching for this operator, but found nothing for RxSwift. Behavior is described here- https://stackoverflow.com/questions/38190722/does-my-ziplatest-operator-already-exist But i will copy description here in case link will  become unavailable:

```
zip
aa--bb--cc--dd--ee--ff--------gg
--11----22--33--------44--55----
================================
--a1----b2--c3--------d4--e5----

combineLatest
aa--bb--cc--dd--ee--ff--------gg
--11----22--33--------44--55----
================================
--a1b1--c2--d3--e3--f3f4--f5--g5

zipLatest
aa--bb--cc--dd--ee--ff--------gg
--11----22--33--------44--55----
================================
--a1----c2--d3--------f4------g5
```

It differs from withLatestFrom because for zipLatest it doesn't  matter which observable emits element first.

RxJava implementation can be found here - https://github.com/akarnokd/RxJava2Extensions#flowablesziplatest

**Comment by kzaher** [comment]
Hi @entropious ,

what would be the practical use case for such an operator?

**Comment by entropious** [comment]
Hi. Well, it will be difficult to describe, but i will try =) I need to asynchronously resolve deep links via branch.io and process them only after user registration/authentication. So there are two observables: resolved deep links (nil if opened by direct launching) and Observable<Void> (let call is OV) which indicates that this deep link can be processed (after login and on app start/UIApplicationWillEnterForeground if user is loggedin). So there are different cases:
- several deep links can be opened while user is not loggedin (i need latest)
- OV can emit element before deep link is resolved
Right now i resolved this problem with ugly workaround via combineLatest and resubscribing each time element is emmited to drop latest values.

**Comment by kzaher** [comment]
Hi @entropious ,

Like you've noted
> Well, it will be difficult to describe

It will also be difficult for your coworkers to figure out how your system should behave from an obscure operator.

I would say that a good rule of thumb would be that operator should represent some commonly known sequence operation and it should be possible to describe its functionality by using a simple sentence.

I don't think that one should use operators to model business logic but only to wrap it, handle transient states, connect side effect mechanisms and adapt their interfaces.

How to solve this situation with Rx? 

You can model business logic as a pure function wrapped inside `scan` operator and `merge` operator that merges the events from those 2 observables.

Maybe you can also simplify your problem in some way.

In any case, I am against adding operators with complex behaviors to this codebase because:
* they create huge amount of noise
* increase size of library
* increase maintenance burden
* aren't useful to a lot of people
* they represent Rx as something completely obscure and complicated
* encourage people to try to combine operators to model business logic
* ...

**Comment by entropious** [comment]
Found solution here - https://stackoverflow.com/questions/46602541/rxjs-lossy-form-of-zip-operator. Implemented zipLatest with RxSwiftExt like this:
`Observable.combineLatest(O1, O2){ ... }.take(1).repeatWithBehavior(.immediate(maxCount: UInt.max))`
Not an obvious solution, didn't think that `repeat` operator could be used as alternative to resubscribing. At first tried built-in operator `Observable.repeatElement(Observable.combineLatest(O1, O1){ ... }.take(1))`, but application stuck - probably some infinite loop.
As for the questions: i'm using MVVM architecture and all buisness logic is contained in stateless reactive ViewModel. I don't think making its statefull will make it mush more simple. Buisness logic can be complicated, but zipLatest behavior is not - it's quite obvious. As you can see, people ask about "lossy zip" from time to time, i'm not the first. Maybe this thread will make it easier for them to find solution =) Anyway, thank you for you time =) Problem solved.

**Comment by kzaher** [comment]
It is my opinion that using Rx in this way will make your life complicated in the long run, but it's your life, so I'm fine with it :)

You haven't made your problem magically stateless by using those operators, you've just made your state/business logic implicit (inside the operators) vs explicit.

Good luck :)
