### ISSUE TITLE
Feature request: `driveOnMainScheduler()`

### ISSUE THREAD

**Issue by DevAndArtist** [ReactiveX/RxSwift#1586]
I have a use-case where I need to hop to the main thread before calling the methods from the `drive` family. In my application there is a `CentralManager` (Bluetooth) which operates at a background thread. While scanning it can find `Peripheral` objects which then will be wrapped into a custom type. The custom type however has a reactive cache (our own implementation) which is used to convert cached `Data` from peripheral characteristics to a destination type while the destination type will be a `Driver`. This the conversion cannot error out. While initialization we the custom type itself will subscribe to a specific set of such cached types. That last operation uses a `drive` method and will crash since the initialization happened on the same thread as the `CentralManager` is running on. 

Since `drive` will crash if not called on the main thread there are a few workarounds out there. 
  1. Falling back to `asObservable` and using:
     ```swift
     driver
       .asObservable()
       .subscribeOn(MainScheduler.instance) 
       .subscribe(onNext: ...)
     ```

   2. Wrap the `drive` method with `DispatchQueue.main.async { ... }`

That is a rare case, however the general `Observable` has already a solution for such issues `subscribeOn`. I propose to add `driveOnMainScheduler` operator which then can be added before `drive` to hop back to the main thread in such cases.

---

Personally I always had an assumption that `drive` will hop to the main thread automatically if it's necessary. Therefore if `driveOnMainScheduler` solves the issue with `sharedReplay`, wouldn't it be good to check whether or not `drive` was called on the main thread, and if not, then to inject that behaviour implicitly?!

**Comment by kzaher** [comment]
Hi @DevAndArtist ,

> I propose to add driveOnMainScheduler operator which then can be added before drive to hop back to the main thread in such cases.

The problem with this approach is that adding that operator would be confusing since we can't encode it nicely in Swift type system (although we could theoretically add a bunch of additional APIs to do that).

In case you want a variant of shared sequence that works on some background scheduler, you can create your own specialization.

`Driver` is meant to be used from the `MainScheduler` only.

I think that you are probably using Rx and `Driver`s as a form of direct substitute for promises, and that's what is actually causing your problems. 

I can definitely understand why you are having troubles figuring out how to use Rx effectively with Bluetooth stack since that was at first a head-scratcher for me also, but unfortunately this isn't a proper channel to discuss that and unfortunately I don't have the time.

To wrap this up.
I think that your problem can be redesigned in a conceptually simpler way. If that fails, then I guess you can probably use one of your solutions.

I would rather not include these extensions in this repo at the moment since they encourage using the API and concepts in an unintended way.
