### ISSUE TITLE
How could I release a SerialDisposable without adding it to a DisposeBag?

### ISSUE THREAD

**Issue by rodrigorsa** [ReactiveX/RxSwift#1589]
**Short description of the issue**:

How could I release a SerialDisposable without adding it to a DisposeBag? I mean since my object is going to be released why does not SerialDisposable have a deinit to release its disposable?

**Self contained code example that reproduces the issue**:

```swift
class MyClass {
  private let serialDisposableA = SerialDisposable()
  private let serialDisposableB = SerialDisposable()
  private let serialDisposableC = SerialDisposable()

  private let disposeBag = DisposeBag()
  
  init() {
    // Here we need to add each one to a DisposeBag
    serialDisposableA.disposed(by: disposeBag)
    serialDisposableB.disposed(by: disposeBag)
    serialDisposableC.disposed(by: disposeBag)
  }

  public func doSomethingA() {
    serialDisposableA.disposable = ...
  }

  public func doSomethingB() {
    serialDisposableB.disposable = ...
  }

  public func doSomethingC() {
    serialDisposableC.disposable = ...
  }
}
```

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [x] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  9.2
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**Comment by kzaher** [comment]
Hi @rodrigorsa ,

because:
* semantics of `Disposable`s aren't "I keep this alive", but "I can potentially cancel this sequence prematurely before termination if wanted"
* one can't use use language/environment specific feature (deterministic deallocation) in construction of platform agnostic computation abstraction (how would that work in javascript or java?).
* if `Disposable`s would dispose on deinit, then just subscribing to something that completes or errors out after a finite time would behave unintuitively. E.g. `_ = createPostRequest().subscribe(onNext: { result in print(result) })` would never print anything.
* => IMHO, it would make things a lot worse, not better.
