### ISSUE TITLE
Ambiguous reference to member 'map(_:atKeyPath:using:failsOnEmptyData:)

### ISSUE THREAD

**Issue by canny09** [ReactiveX/RxSwift#1610]
I wrote a ``Single`` extension to mapping JSON which get from the http request response to model in Swift 3 like this, and it work fine.
```Swift
extension Single {
    // json -> model
    func mapModel<T: HandyJSON>(type: T.Type) -> Single<T> {
        // Error Message: Ambiguous reference to member 'map(_:atKeyPath:using:failsOnEmptyData:)'
        return self.map { response -> T in 
            
            let jsonDict = response as? [String : Any]
            guard let model = T.deserialize(from: jsonDict, designatedPath: "data") else {
                throw BlockyError.unKnown
            }
            return model
        } as! Single<T>
    }
}
```
But today, I convert the project to Swift 4, and then get a error message in above by complier. 
Why does it can't recognize the ``map<R>(_ transform:)`` function?
How to deal it?

I use cocoa pods 
```
pod 'RxSwift',    '~> 4.0.0-rc.0'
pod 'RxCocoa',    '~> 4.0.0-rc.0'
```

Xcode 9.2   Swift 4.0

Thanks for help!

**Comment by canny09** [comment]
I read the ``single.swift``, and then try to update my code like this:
```Swift
extension PrimitiveSequenceType where TraitType == SingleTrait {
    // json -> model
    func mapModel<T: HandyJSON>(type: T.Type) -> Single<T> {
        return self.map { response -> T in

            let jsonDict = response as? [String : Any]
            guard let model = T.deserialize(from: jsonDict, designatedPath: "data") else {
                throw BlockyError.unKnown
            }
            return model
        }
    }
}
```
Just replace the ``single`` with ``PrimitiveSequenceType ``, and then build successful and work correctly. 
Although work fine, but why? Who can explain this? 😳😳 Why extension ``Single`` will get the error message, and Xcode can not automatically recognize the map method?

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
