### ISSUE TITLE
Can I assign CollectionViewB's Int to CollectionViewA?

### ISSUE THREAD

**Issue by karta88821** [ReactiveX/RxSwift#1619]
**Short description of the issue**:

 I have recently practiced using the MVVM+RxSwift architecture, but I have some problems with implement the interaction between two collectionView. 
Suppose I want to do a product selection system. I have a `CollectionViewA` (model has a default `var selectedId = 0 `) ,used for the type of product (like coffee, cake). `CollectionViewB` is the corresponding product after selecting the category (such as strawberry cake, chocolate cake, and model contains `id`). After selecting the product, you can assign `id` to `selectedId`.

**Expected outcome**:

  Tap `CollectionViewA`'cell  -> Show corresponding product(in `CollectionViewB`) -> Tap `CollectionViewB`'cell -> assign `id` (in `CollectionViewB.rx.modelSelected(Product.self)`) to `CollectionViewA`'s `selectedId` (in `CollectionViewA.rx.modelSelected(Category.self)`) -> Other cells and so on

**What actually happens**:

I am using the code below, but I don't know how to implement in this subscribe closure.

**Self contained code example that reproduces the issue**:

```
 Observable.zip(CollectionA.rx.modelSelected(Category.self), CollectionA.rx.itemSelected)
       .subscribe(onNext:{ model, indexPath in
          // TODO: Get prodcutId here
        })
        .disposed(by: disposeBag)

```
```
class Category {
    var selectedId: Int = 0
    .
    .
    .
}

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

```
Using RxCocoa (4.1.2)
Using RxSwift (4.1.2)
```

**Platform/Environment**

  - [x] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro

**Xcode version**:

```
  Version 9.2 (9C40b)
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
