### ISSUE TITLE
UIActivityIndicatorView hidden ？

### ISSUE THREAD

**Issue by 350541732** [ReactiveX/RxSwift#1636]
i am a newer of Rxswift . i write a demo about login .everything goes well but the UIActivityIndicatorView!
when i run my demo,the signingOutlet: UIActivityIndicatorView! is not hidden . i do not know why
my code like this；
        signedIn = input.loginTap.withLatestFrom(usernameAndPassword)
            .flatMapLatest{ pair in
                return  API.sign(pair.username, password: pair.password)
                        .observeOn(MainScheduler.instance)
                        .catchErrorJustReturn(false)
                        .trackActivity(signInIndicator)
                
            }
            .flatMapLatest{ loggedIn -> Observable<Bool> in
                return Observable.just(true)
                                 .delay(1, scheduler: MainScheduler.instance)
       }
        .share(replay: 1, scope: SubjectLifetimeScope.forever)
class CrewLogDefaultAPI: CrewLogAPI {
    static let shareInstance = CrewLogDefaultAPI()
    
    func sign(_ username: String, password: String) -> Observable<Bool> {
        let signInResult = arc4random() % 5 == 0 ? false : true
        return Observable.just(signInResult)
                 .delay(1, scheduler: MainScheduler.instance)
    }
}
        viewModel.signedIn
                 .bind(to: signingOutlet.rx.isAnimating)
                 .disposed(by: disposeBag)
![Uploading 54A273610B95A488B165DEFBF1741317.png…]()

**Comment by kzaher** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
