### ISSUE TITLE
Why is simulateProcessingDelay true by default in TestScheduler?

### ISSUE THREAD

**Issue by gobetti** [ReactiveX/RxSwift#1641]
Hi! Yesterday I removed a `DispatchQueue` instance property I had in a class which I adapted to work with `SchedulerType`s (being able to inject a `TestScheduler` into it) so instead of calling stuff like `myQueue.async { ... }` I started calling `myScheduler.schedule(()) { _ in ... }`

So far so good, however most of my unit tests suddenly failed - actually only and all the ones that had a comparison of expected vs. actual events, and the reason was that the time at which the events were expected to happen, suddenly didn't match anymore the actual events times. For example, everywhere I expected an event at time X, it would now arrive at time X+2.

After a fair amount of time trying to discover where the virtual time was being incremented, I found that the reason is inside the `TestScheduler` itself, because it has a `simulateProcessingDelay` parameter which is true by default. I actually love the fact that RxTest allows us to do that kind of simulation, but I was wondering if that is really the most usual user case? Also, if somebody's interested on simulating that, wouldn't they prefer to be able to choose _how much_ to increment instead of true/false? Anyway, it all works great and this is just a question that would help me to better understand RxTest, I think :)

Thanks in advance!

**Comment by kzaher** [comment]
Hi @gobetti ,

`TestScheduler` is adapted to running unit tests for single operators. You can use **exact time** checks for entire systems, but I wouldn't say that's common case because it's extremely brittle and you are relying on time operator implementation details.

It is enabled by default to enable differentiation between events scheduled immediately and before some time. That enables indirect tests of the operator implementation details.

It is also more realistic since when you schedule something immediately it is realistic that some minute amount of time will elapse until it is executed..

**Comment by gobetti** [comment]
Thanks, I understand it is more realistic, but in a unit test scenario, until now it has only caused me trouble so I thought that enabling that simulation would be the exception instead of the default. Closing question, thanks again!
