### ISSUE TITLE
Implement mergeDelayError operator

### ISSUE THREAD

**Issue by JakeSc** [ReactiveX/RxSwift#1652]
**Short description of the issue:**

See https://github.com/ReactiveX/RxSwift/issues/1191. As TomasLinhart says:
> I also would like to see this operator in RxSwift. It exists in RxJS and RxJava, and it is useful in cases where you want to execute the array of observables, and you don't care if they succeed.

> One of the examples could be syncing images in the background. If some images are not sent it shouldn't prevent other images from sending. The failed can try to be sent next time.

No mergeDelayError operator.

> merge-delay-error is like merge, but will emit all items from all of the merged Observables even if one or more of those Observables terminates with an onError notification while emissions are still pending.
> cf. http://reactivex.io/documentation/operators/merge.html

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.0

**Platform/Environment**

[x] iOS

**Level of RxSwift knowledge:**

[ ] just starting
[ ]  I have a small code base
[x] I have a significant code base

**Comment by kzaher** [comment]
Hi @JakeSc ,

I can't comment why that operator is shipped by default in RxJS and RxJava, but I haven't seen any explanation that would convince me we should ship this operator by default.

> I also would like to see this operator in RxSwift. It exists in RxJS and RxJava, and it is useful in cases where you want to execute the array of observables, and you don't care if they succeed.

If you don't care if they succeed then you would just do `catchError` for each request. Even then that use case is really far fetched because I can't see how that implementation would work for production code.

> One of the examples could be syncing images in the background. If some images are not sent it shouldn't prevent other images from sending. The failed can try to be sent next time.

Again, it's not realistic for `mergeDelayError` to be used in that scenario. The operator interface can't provide you with information which image sending failed, and it is even more questionable why would someone group results/errors/operations of unrelated image uploads. It is also beyond my comprehension why would some image upload system be designed in such a way that upload error of some image is delayed until all of the other images are uploaded.
