### ISSUE TITLE
[Discussion] Adding `scan(into:)` to mirror `reduce(into:)`

### ISSUE THREAD

**Issue by freak4pc** [ReactiveX/RxSwift#1667]
Swift Standard Library includes two flavors of reduce
`reduce(_ initialResult: accumulator)`
and 
`reduce(into: updater:)`

Where the latter lets you directly mutate the accumulated value without creating a mutable `var`. 

This seems like an easy to add "overload" for RxSwiftExt, but then I thought this could also be highly useful for RxSwift core possibly and wanted to see if you'd be open to add it so we have `scan(seed)` and `scan(into)` reflecting `reduce(seed)` and `reduce(into)` in stdlib.

Sample implementation: 

```swift
extension ObservableType {
    public func scan<A>(into: A, updater: @escaping (inout A, E) throws -> Void)
        -> Observable<A> {
        return scan(into) { acc, element in
            var mutableAcc = acc
            try updater(&mutableAcc, element)
            return mutableAcc
        }
    }
}
```

Example usage regular scan:

```swift
Observable
    .of(1, 3, 5, 7, 8)
    .scan([Int]()) { acc, element in
        var mutableAcc = acc
        mutableAcc.append(element)
        return mutableAcc
    }
```

Example usage scan into:
```swift
Observable
    .of(1, 3, 5, 7, 8)
    .scan(into: [Int]()) { acc, element in
        acc.append(element)
    }
```

**Comment by DevAndArtist** [comment]
I like the idea but the implementation above is wrong, since you're just wrapping around the non-inout operator which just creates some more convenient API but does not mirror the `reduce(into:_:)` function from the stdlib, which was included to enhance performance.

Instead we'd need something like this (not tested):

```swift
extension ObservableType {
    public func scan<A>(into initial: A, accumulator: @escaping (inout A, E) throws -> Void) -> Observable<A> {
        return InoutScan(source: self.asObservable(), initial: initial, accumulator: accumulator)
    }
}

final fileprivate class InoutScanSink<ElementType, O: ObserverType> : Sink<O>, ObserverType {
    typealias Accumulate = O.E
    typealias Parent = InoutScan<ElementType, Accumulate>
    typealias E = ElementType
    
    fileprivate let _parent: Parent
    
    init(parent: Parent, observer: O, cancel: Cancelable) {
        _parent = parent
        super.init(observer: observer, cancel: cancel)
    }
    
    func on(_ event: Event<ElementType>) {
        switch event {
        case .next(let element):
            do {
                try _parent._accumulator(_parent._accumulate, element)
                forwardOn(.next(_parent._accumulate))
            }
            catch let error {
                forwardOn(.error(error))
                dispose()
            }
        case .error(let error):
            forwardOn(.error(error))
            dispose()
        case .completed:
            forwardOn(.completed)
            dispose()
        }
    }
    
}

final fileprivate class InoutScan<Element, Accumulate>: Producer<Accumulate> {
    typealias Accumulator = (inout Accumulate, Element) throws -> Void
    
    fileprivate let _source: Observable<Element>
    fileprivate var _accumulate: Accumulate
    fileprivate let _accumulator: Accumulator
    
    init(source: Observable<Element>, initial: Accumulate, accumulator: @escaping Accumulator) {
        _source = source
        _initial = initial
        _accumulator = accumulator
    }
    
    override func run<O : ObserverType>(_ observer: O, cancel: Cancelable) -> (sink: Disposable, subscription: Disposable) where O.E == Accumulate {
        let sink = InoutScanSink(parent: self, observer: observer, cancel: cancel)
        let subscription = _source.subscribe(sink)
        return (sink: sink, subscription: subscription)
    }
}
```

**Comment by freak4pc** [comment]
Hey @DevAndArtist 
Of course we would need an entire new Sink etc. - the implementation above was only to present a MVP of how it would work so it could be approved by @kzaher before implemented with a full test suite.

Thanks for the feedback though !

**Comment by DevAndArtist** [comment]
@freak4pc if there is no `reduce(into:accumulator)` yet, we should add one if we're going to add `scan(into:accumulator)` because it will add the same performance boost even if it emits after the original observable completes, it will at least reduce unnecessary copies.

**Comment by kzaher** [comment]
Hi,

I'm not sure that this optimization makes sense in the case of `scan` operator. We send each intermediate result from scan as new element through sinks.

This means that if that element is cached somewhere, these optimizations don't bring anything to the table.

In the case of `reduce`, we control intermediate result lifetime until the end, so it might make more sense to apply the optimizations there.

I'm not sure how much useful would this operator be though, and I'm not sure how useful is `reduce` operator anyway. I don't remember there was ever a situation where I've used it. A long time ago it seemed like a good idea to include it, but if I could return in past, I wouldn't include it by default probably since I've never actually used it.

On the other hand, I always use `scan`. And yes, if I were to implement reduce now, I would just implement the `reduce(into:accumulator)` version. The one we currently have is not optimal because of the way Swift handles values types.

My current though is that maybe we should either deprecate the current `reduce` operator and implement `reduce(into:accumulator)`, or wait for next version and just change the interface.

Maybe deprecating the current `reduce` version and implementing `reduce(into:accumulator:)` makes most sense. And ditching the current `reduce` operator in 5.0 version since it's probably very rarely used.

**Comment by freak4pc** [comment]
I think we should definitely add a `reduce(into:accumulator:)`. As for `scan(into:)`, it's merely syntactic sugar so you don't have to add the two extra lines inside the reduce block. It doesn't provide _any_ sort of optimizations (as opposed to reduce) because of the way scan emissions work (which you outlined above).

**Comment by kzaher** [comment]
If we are going to do this, then we should change the current implementation for `scan` so it uses the optimized form and maintain an existing public interface by creating a convenience method.

In this way we should increase the chances of reducing the unnecessary copying :)))

In all, these are minor changes, don't bloat our codebase too much and are really common, so let's add them in this repo.

**Comment by kzaher** [comment]
Yeah, but shouldn't it be something like?

```swift
public func scan<A>(_ seed: A, accumulator: @escaping (A, E) throws -> A)
    -> Observable<A> {
    return Scan(source: self.asObservable(), seed: seed) { acc, element in
        // Not sure if there's a nicer way to do this "fallback"
        acc = try accumulator(acc, element)
    }
}
```

**Comment by freak4pc** [comment]
you can't pass the original accumulator "as is" because it's `inout`, so you have to make a copy of it to "hack" around this.

**Comment by kzaher** [comment]
```swift
let accCopy = acc
acc = try accumulator(accCopy, element)
```
?

**Comment by freak4pc** [comment]
Yup, that should work. We'd still need to return that same `acc` as the closure expects a return value. 

So this, I think: 

```swift
let currentAcc = acc
acc = try accumulator(currentAcc, element)
return acc
```

**Comment by kzaher** [comment]
Oh, this should be

```swift
@escaping (inout A, E) throws -> ()
```

```swift
[1].reduce(into: <#T##Result#>, <#T##updateAccumulatingResult: (inout Result, Int) throws -> ()##(inout Result, Int) throws -> ()#>)
```

right?

**Comment by freak4pc** [comment]
Oh ! That's a fair point. Good catch :)
