### ISSUE TITLE
How to Define an Observable for Auto Loading

### ISSUE THREAD

**Issue by yoshinorisano** [ReactiveX/RxSwift#170]
Hi,

I want to create a twitter like client using RxSwift, and realize an auto loading feature,
which automatically loads tweets before we scroll down completely the tweet list.
This is a well-known pattern, isn't it?

Here is bottom line: If we have an API somthing like the following, how we can define an Observable for the auto loading feature just mentioned above?

The latest 20 tweets:
Request: /api/list.json?offset=0&size=20
Response:
{
    "data": [...],
    "next": 20   // Indicates that next offset is 20.
}

The next 20 tweets:
Request: /api/list.json?offset=20&size=20
Response:
{
    "data": [...],
    "next": 40
}

I want to define an Observable, subscribe it, and finally map the changes to a UITableVIew to render the tweets.

```swift
let rows: Observable<[TweetViewModel]>
```

Thanks in advance :)

**Comment by kzaher** [comment]
Hi @yoshinorisano ,

we get that question quite a lot actually :) I think there is a lot of options. 

I would probably solve that using recursion.

Would you be interested in contributing an example to RxExample project that demonstrates that?

Twitter API is probably off the table because it needs to be authenticated, but GitHub repository search API looks more promising for RxExample project.

If you can help me to add that to RxExample or some similar public paginating API, I can write that part of Rx code that you are asking for :)

In that way I can share a solution with you and answer any future questions :)

**Comment by yoshinorisano** [comment]
@kzaher 
Thanks!
Yeah, I want to contribute to it :)
Please wait for a while.

**Comment by kzaher** [comment]
Hi @yoshinorisano ,

I've tried to answer this question here:

https://github.com/ReactiveX/RxSwift/blob/develop/RxExample/RxExample/Examples/AutoLoading/GitHubSearchRepositoriesViewController.swift#L90

and here

https://github.com/ReactiveX/RxSwift/blob/develop/RxExample/RxExample/Examples/AutoLoading/GitHubSearchRepositoriesViewController.swift#L97

Everything other than that is just correctly parsing the GitHub response :)

I've had to add some code to correctly handle API usage limits and parse next links :(, but don't think the noise is horrible :)

**Comment by yoshinorisano** [comment]
@kzaher 
I've built and run the code.
This is what I expected!
Thank you so much :)

I'm looking into the more details of the code!

**Comment by kzaher** [comment]
This is just been released :)

**Comment by vietstone** [comment]
Sorry, but where is this code placed now?

**Comment by kzaher** [comment]
https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/GitHubSearchRepositories/GitHubSearchRepositoriesViewController.swift
