### ISSUE TITLE
Rxswift's flatMap operator works differently as it is in Swift

### ISSUE THREAD

**Issue by 0xF0D0** [ReactiveX/RxSwift#1712]
**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

Currently, RxSwift's `flatMap` operator does not perform as `Swift`'s 'flatMap' does.

Since Swift chose to split older flatMap's functionality to new `compactMap` and `flatMap`,

I'm just wondering why don't RxSwift adopt the change?

IMHO, RxSwift's and Swift's `flatMap` operating differently can cause quite confusing moments.

What do you think about this matter?

**Comment by freak4pc** [comment]
Hey @0xF0D0. 

Rx's `flatMap` is not directly inspirted by Swift's `flatMap`. `flatMap` is an operator [defined in the ReactiveX standard](http://reactivex.io/documentation/operators/flatmap.html) and shared among all implementations of Rx (on all languages). 

There is no correlation between Swift's `compactMap` and `flatMap` situation to what Rx's `flatMap` aims to solve, since they work on entirely different data types and solve very different things.
