### ISSUE TITLE
More fine-grained `VirtualTimeScheduler` when using `TestScheduler`

### ISSUE THREAD

**Issue by freak4pc** [ReactiveX/RxSwift#1723]
This is more of a question than an Issue, but really a bit of both.
Is it possible to test scheduled events using a `TestScheduler` in a finer measurement? 

Many of the calculations inside `TestSchedulerVirtualTimeConverter`, `VirtualTimeUnit` etc only seem to use regular `Int`s, meaning - if you have any events that are faster than a single second, there isn't a really good way to test if events are emitted in the correct time. Also seems 0.5 is added to the ratio of the interval vs. its resolution, I imagine this is to attempt to solve the "rounding" of the Integer.

In my example I have a Metronome, and I'm interested to test that the "beats" are being emitted properly separated from each-other based on the selected time signature. 

I tried messing around with creating my own `VirtualTimeConverter` and `VirtualTimeScheduler` but I think this would also require making the time converter an associated type of the Test Scheduler. So, pretty complex in general :) 

If you have any ideas or just general thoughts around this, I'd love to hear them.

Thanks!

**Comment by freak4pc** [comment]
I just noticed `HistoricalScheduler` that might be helpful but i'm not 100% sure if its usable / applicable in a testing scenario.

**Comment by kzaher** [comment]
Hi @freak4pc ,

I'm not sure what do you mean, `TestScheduler` has optional `resolution`.

```
/**
     Creates a new test scheduler.
     
     - parameter initialClock: Initial value for the clock.
     - parameter resolution: Real time [NSTimeInterval] = ticks * resolution 
     - parameter simulateProcessingDelay: When true, if something is scheduled right `now`, 
        it will be scheduled to `now + 1` in virtual time.
    */
    public init(initialClock: TestTime, resolution: Double = 1.0, simulateProcessingDelay: Bool = true) {
        _simulateProcessingDelay = simulateProcessingDelay
        super.init(initialClock: initialClock, converter: TestSchedulerVirtualTimeConverter(resolution: resolution))
    }
```

**Comment by freak4pc** [comment]
Yes, but both `VirtualTimeIntervalUnit` and `VirtualTimeUnit` on `TestSchedulerVirtualTimeConverter` are of type `Int`.

You calculate the virtual time by adding 0.5 and than casting to `VirtualTimeIntervalUnit` (Int) which, to my understanding, bets rid of any precision:

```
/// Converts real time to virtual time.
///
/// - parameter time: `Date` to convert to virtual time.
/// - returns: Virtual time corresponding to `Date`.
public func convertToVirtualTime(_ time: RxTime) -> VirtualTimeUnit {
    return VirtualTimeIntervalUnit(time.timeIntervalSince1970 / _resolution + 0.5)
}
```

Am I misunderstanding how this works? In my metronome example all events are always spaced by a unit of "1", which is not a good way to check if the spacing is correct according to the actual time selected.

**Comment by kzaher** [comment]
I'm still unsure what is the actual complaint.

> Many of the calculations inside TestSchedulerVirtualTimeConverter, VirtualTimeUnit etc only seem to use regular Ints, meaning - if you have any events that are faster than a single second, there isn't a really good way to test if events are emitted in the correct time.

You can chose arbitrary precision in a manner I've described, can't you?

Are you complaining that time is float an ticks are ints? I don't think this matters.

```swift
 3> (3 * 0.3) == 0.9 
$R1: Bool = false
```

You can always test up to a certain precision anyway.

```swift
  4> abs((3 * 0.3) - 0.9) < 0.01 
$R2: Bool = true
```

There is no such thing as a infinite precision decimal point in Swift. I guess you can potentially create some kind of rational form that preserves the precision perfectly.

If you are asking why is that 0.5 there, it is there for rounding, yes. I guess should have used some built in method, but old habbits take a long time to die. Yes, it probably fails for negative numbers :)

**Comment by freak4pc** [comment]
I just want to make sure - if I want to test something that emits events relatively momentarily, and the "spacing" is actually important for me, would I just reduce the resolution to a very low number? That's the expected solution you're referring to ?

**Comment by freak4pc** [comment]
Ok great. I've been able to get some more well-spaced events from a ticket-metronome.

Can you explain more or less how the conversion from millisecond / second is done ? For example, testing a metronome I'm getting

```
next(first) @ 5
next(regular) @ 10
next(regular) @ 15
next(regular) @ 20
next(first) @ 25
next(regular) @ 30
next(regular) @ 35
next(regular) @ 40
etc...
```

The spacing is of `5` virtual units, but I'm not sure what's the conversion that causes _whatever amount of seconds_ be converted to `5` in this case.

**Comment by freak4pc** [comment]
The main issue with the ticks being floats is when - in a repetitive manner, you're getting things not properly divisible, and the rounding causes a side-effect where the tests needs to be written for the code instead of the other way around. 

For example: 

Running some code:

```
next(first) @ 125
next(regular) @ 250
next(regular) @ 375
next(regular) @ 500
```

Running the same code when the ticks are divided by half 
```
next(first) @ 63 // should be 62.5, but rounded
next(regular) @ 125
next(regular) @ 188 // should be 187.5, but rounded
next(regular) @ 250
```

That means the only way to get properly-divisble values is bringing the resolution way-way down; in this case `0.0001`.

**Comment by kzaher** [comment]
@freak4pc The primary purpose of testing scheduler is testing operators. 

It seems to me that your core issue is that you expect float equality testing to be possible. This is not standard practice. This is the reason why `XCTAssertEqualWithAccuracy` exists. You should never compare floats with equality operator, which is what you want to do at the moment.

This is the reason why all of our unit tests work with integer intervals. Multiplying integers results in integers.

> Long-term, I believe the event times on the TestScheduler should be moved to a Float/Double so you don't need to do any rounding at all. 

I didn't see any rationale why do you see that using `float`/`double` would solve anything.

> It doesn't make sense this being the default behavior, and it requires the developer to "tinker" with the resolution until you get to a common denominator.

If you want to deprecate `init` form with default resolution with the one that requires specifying resolution and update all unit tests. I would be fine with that. 

But I don't think we'll ever have Float/Double for ticks since it doesn't solve anything IMHO.

**Comment by freak4pc** [comment]
@kzaher Not sure why is the definition that this is the primary purpose. As of today there is no other way to assert some observable emitted things at the time you expected them to emit. 

My point was the times could have more accuracy and use `XCTAssertEqualWithAccuracy` internally for the time stamps. 

I'll keep using the regular but I feel like there's more to be desired in terms of testing higher-accuracy emissions. 

Thanks anyways!

**Comment by kzaher** [comment]
> @kzaher Not sure why is the definition that this is the primary purpose.

Because it is designed to **precisely** simulate time and scheduling. When testing operator behavior we need to somehow differentiate between cases when somebody calls schedule method to execute some lambda (it will be scheduled at current `tick + 1`) or schedule it immediately (it will be executed at `tick`).

If one wants to test some small system with realistic timings, and not test integer tick like timings, this is supported by effectively dividing his operation timings with scheduler resolution, and thus effectively reducing this test to test with again integer timings. `resolution` is the denominator.

How you do it?

Choose time resolution/precision you are interested in. This step is needed to divide your timings from float to hopefully integers. Usually it is reasonable to use milliseconds (0.001) here. If your product owner requires exactly 30.0007 sec network timeouts, you probably have an unrealistic product owner since there is no way iOS will wake up your device after mathematically exactly that time has elapsed. In that case you can set your interval to something like 0.000001 (microseconds) or lower, but you probably have bigger problems in your life if you are doing this.

> As of today there is no other way to assert some observable emitted things at the time you expected them to emit.

Again, this is not realistic. You can't choose to check at the precise time since you are dealing with finite precision arithmetic. `0.3 * 3 != 0.9`. And even if you could, it doesn't have any sense to depend your business success on relying iOS will schedule some event after exactly 0.34840348347 sec.

But if you ignore all of what I've said, nothing is stopping anyone from using 0.000000001 as precision and then create their own `XCTAssertAnythingTheyWant`.

> My point was the times could have more accuracy and use XCTAssertEqualWithAccuracy internally for the time stamps.

I hope you will realize that this is not such a simple change as changing the data type from float to integer. It has far-reaching consequences.

Could all of this be redesigned? Probably. Would the complete redesign have some drastic positive change in people's lives? I doubt it.

**Comment by freak4pc** [comment]
> Could all of this be redesigned? Probably. Would the complete redesign have some drastic positive change in people's lives? I doubt it.

I think the gist is really this :) The value to "fixing" this would probably benefit only a few very unique use cases. 

Appreciate your consideration!
