### ISSUE TITLE
Single Trait flatMap

### ISSUE THREAD

**Issue by 0xF0D0** [ReactiveX/RxSwift#1724]
**Short description of the issue**:

I found out that current `Single` trait's flatMap returns `Single`.

I've got curious though, because even when source observable emits once, emitted observable can emit any number of elements right?

If I'm misunderstanding the concept, it's very welcome to be corrected. Thank you.

**Expected outcome**:

Single's flatMap returns Single

**What actually happens**:

I think it should return just observable, since nobody knows how many elements will be emitted from the observable.

  _what actually happens goes here_

**Self contained code example that reproduces the issue**:

```swift
let mySingle = Single<Int>.just(1)

mySingle.flatMap { value -> Observable<Int>
    //Currently, the output only accepts single like Single<Int>
    //But I thought at this point, we should be freed to emit multiple elements
}

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Any
```

**Comment by kzaher** [comment]
Hi @0xF0D0 ,

Can you please write a code example that you either:
* expect it to compile
* it doesn't compile
* demonstrates some unexpected behavior

I can't understand your question.

**Comment by 0xF0D0** [comment]
My question is "why single's flatMap only returns single?".

It's the code of single's flatMap:
```
public func flatMap<R>(_ selector: @escaping (ElementType) throws -> Single<R>)
        -> Single<R> {
            return Single<R>(raw: primitiveSequence.source.flatMap(selector))
    }
```
As you see return type is `Single` which means the returned observable only emits one element.

But what if the case like figure below happens?
![image](https://user-images.githubusercontent.com/7742751/44434422-01705400-a5e6-11e8-8a41-3d147ee9e5df.png)

Situations like output of each elements emits two elements cannot be handled by current single's `flatMap`

**Comment by 0xF0D0** [comment]
So basically what i'm proposing is why we woudn't add something like this:
```
public func flatMap<R>(_ selector: @escaping (ElementType) throws -> Observable<R>)
        -> Observable<R>
```

**Comment by pietrocaselani** [comment]
This operator is also available on [RxJava](http://reactivex.io/RxJava/javadoc/io/reactivex/Single.html#flatMapObservable-io.reactivex.functions.Function-)

**Comment by kzaher** [comment]
Hi @0xF0D0 ,

the reason why we don't have it is because you can just do `asObservable().flatMap` and then you have both `flatMap` and any other `Observable` operator.

We've only added the overloads provide additional compile time information, like maybe, single and completable.

You can always drop from anything to `Observable` by just doing `asObservable`.

**Comment by pietrocaselani** [comment]
Hi @kzaher 
From my understanding, there are two completely distinct behaviors between

```swift
func methodThatReturnsAnObservableThatEmitsMultipleItems(text: String) -> Observable<Int> {
    return doSomething(text: text)
}

mySingle.flatMapObservable { textString in
    return methodThatReturnsAnObservableThatEmitsMultipleItems(textString)
}
//Now, mySingle is an observable that emmits multiple items, and depending on how doSomething is implemented, this observable may never complete
```

```swift
func methodThatReturnsASingle(text: String) -> Single<Int> {
    return doSomething(text: text)
}

mySingle.flatMapObservable { textString in
    return methodThatReturnsASingle(textString).asObservable()
}
// Now, my single is an observable, but only emits one item and completes.
```

The operator `asObservable` for me, is just to make the compiler happy, and `flatMapObservable` is an operator that allows composition between a stream that emits only on an item to a stream that emits many items and may or may not complete.
Does that make sense?

**Comment by 0xF0D0** [comment]
To me, doing `flatMap{...}.asObservable()` looks boilerplate.
IMO, in the first place, `flatMap -> Single<R>` shouldn't be the default flatMap operation, since it restricts other conversion as @pietrocaselani said.

How about splitting `flatMap` into `flatMapSingle` & `flatMapObservable`?

**Comment by sergdort** [comment]
Hi, guys, I think @kzaher point that the main library does not need these (unnecessary) overloads, so that we can keep it smaller, more maintainable and provide core functionality.

And if you really want to have these overloads you can easily achieve this just by adding extension method to the `Single` ¯\_(ツ)_/¯

**Comment by 0xF0D0** [comment]
@sergdort I do agree with you and @kzaher's idea to maintain the library small.

I was just wondering why `flatMap -> Single<R>` had to be the default though... since it provides less functionality

**Comment by freak4pc** [comment]
@0xF0D0 Because you are using Single to begin with :) 

If you have a Single(1) and you do `map { $0 * $0 }`, you would still expect to get a Single so you retain uniformity. You'd be confused getting an `Observable` when mapping a `Single`, and that case would definitely be the same for `flatMap`ing a `Single` and getting back an `Observable` all of a sudden - it doesn't make much sense.

Adding `asObservable()` is a tad explicit - but that's not necessarily a bad thing. `Single` makes a specific promise, and the fact you're explicitly "converting" it to an `Observable` potentially helps other readers of your code understand assumptions you're making about that sort of composition. 

As mentioned above, if you have a strong urge to move away from `asObservable()`, creating your own extension would be a fairly minor task to have. We can also consider adding to `RxSwiftExt`.

**Comment by 0xF0D0** [comment]
@freak4pc Thanks for the kind reply :)

It really scratched my back 👍 

I'll close this issue since my all curiosity have solved.
