### ISSUE TITLE
How do you wrap target-action pattern into an Observable?

### ISSUE THREAD

**Issue by isaac-weisberg** [ReactiveX/RxSwift#1736]
**Short description of the issue**:

 I am having a tough time figuring out the following "how to".

```swift
class SavePhotoManager {
    func save(photo: UIImage) -> Completable {
        return Completable.create { completable in
            UIImageWriteToSavedPhotosAlbum(photo, self, #selector(imageSaveCompletion(image:error:contextInfo:)), nil)
        }
    }

    @objc func imageSaveCompletion(image: UIImage, error: Error?, contextInfo: UnsafeRawPointer) { 
        // produce the onCompleted event
    }
}
```

Should I retain the `completable` passed in the closure in create call and call it once in `imageSaveCompletion`?

**Expected outcome**:

 Completable should complete if `imageSaveCompletion` completes with `error == nil`, or error out if `error != nil`.

**What actually happens**:

Nothing because I have not written the implementation because I am not sure which approach is valid?

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 `4.2.0`

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  9.4.1
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by isaac-weisberg** [comment]
@freak4pc I am terribly sorry.

**Comment by freak4pc** [comment]
No worries :) all good, I’m sure someone will be able to help you on Slack.

**Comment by isaac-weisberg** [comment]
Just in case if anyone would be interested, it's the contextInfo we can utilize to pass the Completable handler and call it with `.completed` or `.onError(Error)`. Whatever gets passed as a last parameter to `UIImageWriteToSavedPhotosAlbum` (in Swift 4.1.x), gets passed as contextInfo in the handler.
