### ISSUE TITLE
Add operator take to SharedSequenceConvertibleType

### ISSUE THREAD

**Issue by kzumu** [ReactiveX/RxSwift#1761]
Hi.
I want to use `take` operator in Driver.
In order to do it, it need to implement `take` operator to `SharedSequenceConvertibleType`.
I think that we can add this operator to `SharedSequenceConvertibleType`, because other operators also known as `delay`, `startWith`, `skip` are already implemented.

Do you think it’s worth to adding this operators?
If so, I am able to do this and open a pull request.

Thanks!

**Comment by freak4pc** [comment]
TBH I'm not entirely against, even though - practically speaking, a Driver is usually the "final stop" and doesn't get additional processing (again, usually, there are exceptions to this and different preferences). 

However, since we do offer other operators on SharedSequence, I think it would be weird to avoid adding `take` or other operators that are highly common. 

Can't make a decision on this, but that's where my opinion stands more or less. Would have to defer to @kzaher for final word.

**Comment by kzumu** [comment]
@freak4pc 
Thanks. I could understood your words.
I submitted PR, so if @kzaher say Okay, please merge it.
ref: #1786

**Comment by freak4pc** [comment]
Closing this, we can discuss in the PR. Thanks!
