### ISSUE TITLE
Help with UISegmentedControl+Rx.swift

### ISSUE THREAD

**Issue by DuM4ll3** [ReactiveX/RxSwift#1763]
Hi,

I'm trying to use the _titleForSegment(at index:)_ function as described [here](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/UISegmentedControl%2BRx.swift#L39) with a **bind** operator such as: 
```
anObservableOfStrings
.bind(to: segmentedControl.titleForSegment)
```
but the closest example I could find is [this](https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Examples/APIWrappers/APIWrappersViewController.swift#L74) which is not exactly what I'm looking for.

I thought that it could be as similar as using the _UIPickerView.rx.itemTitles_ [like so](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/UIPickerView%2BRx.swift#L85).

Sorry for the ignorant request but can someone show me how to properly use this property?
Thanks!

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by DuM4ll3** [comment]
Sorry, this makes totally sense!
Thanks for the explanation :)
