### ISSUE TITLE
RxExample memory leaks in xCode 10 Memory Graph Debugger

### ISSUE THREAD

**Issue by FloMZzz** [ReactiveX/RxSwift#1773]
**Short description of the issue**:

When running RxExamples (e.g. Adding Numbers), I got memory leak reports in xCode Memory Graph Debugger. 

Steps to reproduce:

1. Download or clone the latest revision of RxSwift (0df62b4d562f8620d4b795b18e4adf0b631527a1 for me)
2. Just run RxExample in xCode
3. Go to "Adding Numbers"
4. Play a little with values there
5. Return back to the list of examples
6. Press Memory Graph Debugger icon and see 5 memory leaks reported (see the screenshot attached).

**Expected outcome**:

No memory leaks reported.

**What actually happens**:

Multiple memory leaks appear.

**Platform/Environment**

  - [*] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [*] easy, 100% repro

**Xcode version**:

```
10 (10A255)
```

Is it a bug in RxSwift/RxExample, or is it a bug in xCode?

**Comment by FloMZzz** [comment]
![2018-10-16 20 15 11](https://user-images.githubusercontent.com/19997249/47034831-16e6a200-d181-11e8-86c9-36b141c6ea95.png)

**Comment by Maru-zhang** [comment]
After my test, if you use iOS11.* simulator, it's all work fine. The "memery leak" only happen in lastest simulator. But if you use iOS12 simulator, the `UITextField` will not be released after `NumberViewController` release(mabe because of storyboard, if you use code, that's all fine), and next time you navigate to `NumberViewController`, the `UITextField` in last `NumberViewController` will be released.

**Comment by kzaher** [comment]
Since it looks like UIKit is performing some internal optimizations, I've removed that code because it can't work with the current implementation of UIKit.
