### ISSUE TITLE
Xcode report an error 'Ambiguous reference to member 'asObservable()'',it why?

### ISSUE THREAD

**Issue by BianTaoGit** [ReactiveX/RxSwift#1785]
**Short description of the issue**:

something happens when use RxSwift and RxCocoa,xcode error 'Ambiguous reference ',it's strange, how should I do to solve the problem?

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
` let loginFinished: Driver<LoginResult>
        loginFinished = loginTaps
            .asObservable()
        .withLatestFrom(Observable.combineLatest(userName.asObservable(), password.asObservable()))`

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 use_frameworks!
  pod 'RxSwift', '4.3'
  pod 'RxCocoa', '4.3'
  pod 'Moya/RxSwift', '11.0'

**Platform/Environment**

  -  iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**: 
10.0

**Installation method**:
CocoaPods

**I have multiple versions of Xcode installed**:
 no



**Short description of the issue**:

something happens when use RxSwift and RxCocoa,xcode error 'Ambiguous reference ',it's strange, how should I do to solve the problem?

**Self contained code example that reproduces the issue**:

```swift
  code goes here
  
` let loginFinished: Driver<LoginResult>
        loginFinished = loginTaps
            .asObservable()
        .withLatestFrom(Observable.combineLatest(userName.asObservable(), password.asObservable()))`

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 use_frameworks!
  pod 'RxSwift', '4.3'
  pod 'RxCocoa', '4.3'
  pod 'Moya/RxSwift', '11.0'

**Platform/Environment**

  -  iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**: 
10.0

**Installation method**:
CocoaPods

**I have multiple versions of Xcode installed**:
 no

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

This sort of code works well 99% of the time - if you have a reproducible project where there's a clear bug, let me know and I'll re-open this issue. Otherwise, please use other, more appropriate support channels :) 

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
