### ISSUE TITLE
Weird behavior of flatMap

### ISSUE THREAD

**Issue by hoangelec** [ReactiveX/RxSwift#1793]
I have this snippet of code: 

```
            let obString = Variable("One")
            let bag = DisposeBag()
            let publisher = Variable(false)
            publisher.asObservable().flatMap({ (value) in
                return obString.asObservable()
            })
                .debug("String subscription")
                .subscribe(onNext: { (string) in
                    print("String value " + string)
                }).disposed(by: bag)
            print("+++++++++++++++++++")
            publisher.value = false // (1)
            print("+++++++++++++++++++")
            obString.value = "Two" //(2)
```
And here's the ouput: 

2018-11-02 15:07:19.947: String subscription -> subscribed
2018-11-02 15:07:19.950: String subscription -> Event next(One)
String value One
+++++++++++++++++++
2018-11-02 15:07:19.950: String subscription -> Event next(One)
String value One
+++++++++++++++++++
2018-11-02 15:07:19.950: String subscription -> Event next(Two)
String value Two
2018-11-02 15:07:19.950: String subscription -> Event next(Two)
String value Two
2018-11-02 15:07:19.950: String subscription -> isDisposed

What got me confused is, there are 2 "Event next(Two)" being emitted, while it should be only one. 

Can someone please help me explain if this is a bug or not?

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
