### ISSUE TITLE
Mix combineLatest and zip

### ISSUE THREAD

**Issue by RazvanBengaGemini** [ReactiveX/RxSwift#1796]
I have two sources of streams that I want to listen to. The requirements are:

1. If any of them emits, give me the last value from the second.
2. If both of them emit at the same time, don't call the subscribe two times.

Is there any way I can achieve this? Thank you

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
