### ISSUE TITLE
UIBarButtonItem rx tap will called when UIViewController dealloc

### ISSUE THREAD

**Issue by linshizai** [ReactiveX/RxSwift#1802]
<img width="915" alt="screen shot 2018-11-15 at 17 29 27" src="https://user-images.githubusercontent.com/13580181/48543227-10705500-e8fc-11e8-91c6-02e0b71452a2.png">

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
