### ISSUE TITLE
How to merge the result of multiple async requests

### ISSUE THREAD

**Issue by adimango** [ReactiveX/RxSwift#1808]
I have a question about the merging of a **chain of async requests**.
Given 2 simple functions as below:

```
private func getTransactions() -> Observable<[Transaction]> {
   //api call
    ...   
    return Observable.just([])
}

private func getTransactionsDetails(_ id: String) -> Observable<[TransactionDetails]> {
   //api call 
    ...   
    return Observable.just([])
}

```

How can i write a function that **returns the transactions details for the given array of transaction ids**?

```
func allTransactionsDetails() -> Observable<[TransactionDetails]> {
        return getTransactions()
            .flatMap({ transactions in

               // this only returns the details for the first transaction
                return getTransactionsDetails(transactions.first.id)
            })
    }
```

Is there any clean way to do it using RxSwift?

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
