### ISSUE TITLE
Strange behavior from...behavior subjects with the share operator

### ISSUE THREAD

**Issue by dannyhertz** [ReactiveX/RxSwift#1820]
**Short description of the issue**:

Using the share operator on a stream that originates from a BehaviorSubject has some non-obvious behavior (replay logic seems to be stripped away).

**Expected outcome**:

I would expect the "replay 1" behavior of a behavior subject to be maintained after sharing but it seems like perhaps the default replay param of 0 takes precedent? Strange because doing the same with an Observable.just(VALUE) behaves as expected.

**What actually happens**:

Only a single subscription seems to be fired with a share() operator being used.

**Self contained code example that reproduces the issue**:

```swift

let dogs = BehaviorSubject(value: "Rex")

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

// "Rex" is printed three times as expected

let dogs = BehaviorSubject(value: "Rex").share()

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

// "Rex" is printed only one time, which is unexpected

let dogs = Observable.just("Rex")

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

// "Rex" is printed three times as expected

let dogs = Observable.just("Rex").share()

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

dogs.subscribe(onNext: {
    print($0)
})

// "Rex" is printed three times as expected

```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.4

**Platform/Environment**

  - [x ] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [x ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
10.1
```

**Installation method**:
  - [ x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [ x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x ] I have a significant code base

**Comment by freak4pc** [comment]
Hey @dannyhertz ! I agree this behaviour might be seem a bit odd at first but it makes sense :) 
I'm answering out of my own knowledge here but I'm sure Krunoslav might be able to extend more information later on, hopefully.

Basically `share(replay: 0, scope: .whileConnected)` (which is the default) creates a PublishSubject-like effect on whatever you put it on, in that - only future emissions will be played, but there will be no replay, since you state `replay: 0` in the share operator. `BehaviorSubject` doesn't actually have a sharing strategy at all, just a replay strategy. 

It means that - a BehaviorSubject replays its latest value, but if you share with a replay of 0, you are, in essence, overriding that replay strategy. The subscribers share the same stream which has a replay of 0, so even if the source has a replay of 1, it would be overridden - which makes sense, overall.

**Comment by kzaher** [comment]
Hi @dannyhertz ,

Like @freak4pc says, this behavior seems correct to me. It doesn't matter how deceiving code might look like.

`BehaviorSubject` is a sequence that will replay element immediately upon subscription to it.

`share` is an operator that will share a subscription to its originating sequence for its subscriptions with `replay: 0`.

Please use `BehaviorSubject(value: "Rex").debug("behavior subject").share().debug("after share")` to better understand what is happening here.

**Comment by dannyhertz** [comment]
I understand why the share (with replay 0) behaves as it does (printing once), but I don’t understand how your explanation makes sense with the .just() behavor. Shouldn’t sharing a .just (with the default of replay 0) print the same values as the shared BehaviorSubject?

**Comment by freak4pc** [comment]
@dannyhertz To my knowledge it's because `just()` is quite different - basically every subscribe(r) gets its own entirely new stream, so sharing basically does nothing to it since there's nothing to share but a single emission and then immediately a complete event - 

With share or without share, you'll probably see the same thing:

![image](https://user-images.githubusercontent.com/605076/50385773-b1181880-06e3-11e9-8b05-3640e0d8bc6b.png)

This is because `share()` shares resources - but in this case these are entirely separate resources. There's nothing to replay - its as if you would share a function that returns new Observables - you're getting a new one every time so sharing doesn't make a difference:

![image](https://user-images.githubusercontent.com/605076/50385781-094f1a80-06e4-11e9-9a84-494ba82bc727.png)

Which is different if, for example, you compare it to flatMapping into a "just" and sharing that - now you're actually sharing a single resource, so all subscribers will be getting the same emissions: 

![image](https://user-images.githubusercontent.com/605076/50385803-5af7a500-06e4-11e9-99e2-e878b884edad.png)

Hope this helped clear up some of this.
Shai.
