### ISSUE TITLE
No mergeDelayError operator

### ISSUE THREAD

**Issue by marciogranzotto** [ReactiveX/RxSwift#1824]
**Short description of the issue**:

  As mentioned on #1652 and #1191, there's no `mergeDelayError` operator, even though it ships by default in other Rx implementations.

 @kzaher commented that he doesn't see an use case for this operator. I do have one that I depend a lot on it.
I'm communicating with an embedded device that supports several types of transports. On the app side, I need to send a message on every transport and just get one response for one of them.
I only care for errors if no transport succeded.

Here's the Kotlin implementation

```kotlin
    fun <T> mergeAndGetFirst(observables: List<Observable<T>>): Single<T> {
        return Observable.mergeDelayError(observables)
            .firstOrError()
    }
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

 4.0

**Platform/Environment**

  - [ x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**Comment by kzaher** [comment]
Hi @marciogranzotto ,

Have you solved your problem without this operator?

**Comment by marciogranzotto** [comment]
@kzaher no. It seems that no other set of operators can be used to achieve the same behavior

**Comment by kzaher** [comment]
Hi @marciogranzotto ,

The purpose of operators in this library isn't to cover every possible behavior out there, but the provide the implementations for common behaviors.

I can't comment why the other maintainers chose to maintain this operator.

When you can't find any existing operators to fit your use case first default to **`scan`** because it is probably one of the most general operators out there and you can use it to encode your custom state machine.

If that doesn't work and you need to implement your state machine that uses other observables you can always **write your own operator**, use [RxFeedback](https://github.com/NoTests/RxFeedback.swift) or something else you prefer.

Having said that, I think you can hack your use case by using existing operators. Something like:

```swift
observables
  .map { $0.materialize() }
  .toArray()
  .map { events in
     guard let value = events.compactMap { $0.value }.first else { throw someKindOfError }
     return value
  }
```

If you want to dispose other subscriptions immediately on first element then you can do some kinds of combination of 

```
observables
  .map { $0.materialize() }
  .filter { $0.value != nil }
  .elementAt(0)
  .doSomeKindOfElementTransformationOrThrowError
```

**Comment by marciogranzotto** [comment]
Just if anyone has the same problem, this is what I did to make it work, based on @kzaher response.

```swift
Observable.merge(observables.map { $0.materialize() })
            .filter { $0.element != nil }
            .elementAt(0)
            .map { $0.element! }
            .asSingle()
```

**Comment by marciogranzotto** [comment]
Actually, that does not work if all observables throw errors.
Here's the updated version:
```swift
extension Observable {
    public static func mergeAndGetFirst<T>(_ observables: [Observable<T>]) -> Single<T> {
        return Observable<Event<T>>.merge(observables.map { $0.materialize() })
            .toArray()
            .map({ (events) in
                guard let event = events.compactMap({ (event) -> T? in
                    event.element
                }).first else {
                    throw CompositeError(events.compactMap { event in event.error })
                }
                return event
            })
            .asSingle()
    }
}

public class CompositeError: Error {
    public var errors: [Error] = []

    init(_ errors: [Error]) {
        self.errors = errors
    }
}
```
