### ISSUE TITLE
canMoveRowAt of UITableViewDataSource

### ISSUE THREAD

**Issue by adamsmaka** [ReactiveX/RxSwift#1827]
I'm using RxSwift (RxCocoa) to populate my tableView cells

    viewModel.cellsDriver.drive(tableView.rx.items) { ... }

This way I have no access to tableView's dataSource's method

    func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool
But I need to specify which rows are movable for 

    tableView.rx.itemMoved

How can I restrict which rows should not be able to drag around without using RxDataSources?

**Comment by kzaher** [comment]
Hi @adamsmaka ,

What do you mean? You can implement functionality equivalent to the one in RxDataSources yourself. There is an overload which takes your custom data source.

This doesn't look like an issue with the project itself but more of a "how do I do XXX" question. 
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:
* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
