### ISSUE TITLE
Set custom logging function for .debug() operator

### ISSUE THREAD

**Issue by ashender** [ReactiveX/RxSwift#1828]
**Short description of the issue**:

 Observable.just(1).debug().subscribe....

debug() operator prints debug information using system print() function

**Expected outcome**:

 I want to be able to redirect this logging output to custom logger, such as Cocoa Lumberjack or any other.

**What actually happens**:

  Logs printed to system output and there is no way to redirect them. It is not possible to create my own DebugSink as Sink and Producer classes are internal to RxSwift framework

**Self contained code example that reproduces the issue**:

```swift
  Observable.just(1).debug().subscribe()
 
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

4.4.0

**Platform/Environment**

  - [ ] iOS
 
**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
 10.1
```

**Comment by freak4pc** [comment]
You can make your own logging on the do(on) block as a side-effect. This isn’t the purpose of the debug operator which is solely used for debugging purposes of your stream while developing. 

Also, consider further if this makes sense to you - to log an entire event chain this way - instead of specific emissions or events. 

Shai.
