### ISSUE TITLE
How to use rxswift refresh one tableView or collectionView cell?  Because I only need to update one or a few cell.

### ISSUE THREAD

**Issue by codepgq** [ReactiveX/RxSwift#1847]
```
roomVM.items
            .bind(to: collectionView.rx.items) {[weak self] (collectionView, row, element) in
                let indexPath = IndexPath(row: row, section: 0)
                let cell = collectionView.dequeueReusableCell(
                    withReuseIdentifier: RoomCell.identifier,
                    for: indexPath) as! RoomCell
                cell.config(element)
                return cell
            }
            .disposed(by: bag)
```

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
