### ISSUE TITLE
explain where auto complete not work

### ISSUE THREAD

**Issue by salah-mohammed** [ReactiveX/RxSwift#1884]
rx code inside ViewModel  and ViewModel  class exists in  Viewcontroller class 

<img width="306" alt="screen shot 2019-02-20 at 5 11 23 pm" src="https://user-images.githubusercontent.com/12451477/53101701-fa91b200-3532-11e9-95e0-b11051bcc038.png">
<img width="847" alt="screen shot 2019-02-20 at 5 11 51 pm" src="https://user-images.githubusercontent.com/12451477/53101704-fa91b200-3532-11e9-96e9-0c5f7083bcda.png">

rx code  exists in  Viewcontroller class 

<img width="840" alt="screen shot 2019-02-20 at 5 13 09 pm" src="https://user-images.githubusercontent.com/12451477/53101722-00879300-3533-11e9-8007-dd2baf54dbbf.png">
![Uploading Screen Shot 2019-02-20 at 5.13.33 PM.png…]()

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://rxswift-slack.herokuapp.com/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by salah-mohammed** [comment]
yes , I understand  this .
