### ISSUE TITLE
Type inference problem

### ISSUE THREAD

**Issue by wwdc14** [ReactiveX/RxSwift#1893]
**Short description of the issue**:

  Where is the syntax wrong?

**Expected outcome**:

I hope it can automatically deduce the model type

**What actually happens**:

  But I pass two different names of the structure, it will throw an error❌
  Two structures of the same name, compiled through✔️

**Self contained code example that reproduces the issue**:
[![5B8A021D3C72AE20AE0E6DCDF6D542E2.jpg](https://i.loli.net/2019/03/06/5c7f3d804a096.jpg)](https://i.loli.net/2019/03/06/5c7f3d804a096.jpg)
[![E96DB18A611B5EEFE6BA8689F87F5E5F.jpg](https://i.loli.net/2019/03/06/5c7f3d8053400.jpg)](https://i.loli.net/2019/03/06/5c7f3d8053400.jpg)

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**

  Xcode version 10.1 (10B61)

**Installation method**
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [x] just starting
  - [ ] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
