### ISSUE TITLE
Update UIProgressView progress in a UILabel using Rx?

### ISSUE THREAD

**Issue by khunshan** [ReactiveX/RxSwift#1966]
I am currently doing this. 
```
    @IBOutlet weak var progressLabel: UILabel!
    @IBOutlet weak var progressView: UIProgressView!
    let progressSequence = BehaviorRelay<Float>(value: 0.0)
    let disposeBag = DisposeBag()
    
    override func awakeFromNib() {
        super.awakeFromNib()

        progressSequence.bind { (value) in
            self.progressLabel.text = "\(Int(value))%"
        }.disposed(by: disposeBag)
        
        progressSequence.asObservable().bind(to: progressView.rx.progress).disposed(by: disposeBag)
```

I have to use additional BehaviorRelay to achieve this. Is there a better and simpler approach?

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
