### ISSUE TITLE
Recursive observables alternatives? Is there a better solution?

### ISSUE THREAD

**Issue by epatey** [ReactiveX/RxSwift#1981]
I have a pretty simple pagination helper that's generic and works well. The problem I have is that it uses recursive `Observable`s which leads to a holding the entire chain of `Observable`s alive until the final page has been retrieved. 

```swift
static public func getPages<Token, Result>(pageGetter: @escaping (_ token: Token?) -> Single<PageResult<Result, Token>>) -> Observable<Result> {
    return intGetPages(pageToken: nil, pageGetter: pageGetter)
        .map { $0.content }
}

private static func intGetPages<Token, Result>(pageToken: Token?, pageGetter: @escaping (Token?) -> Single<PageResult<Result, Token>>)
    -> Observable<PageResult<Result, Token>> {
        return pageGetter(pageToken)
            .asObservable()
            .flatMap { tuple -> Observable<PageResult<Result, Token>> in
                if let nextPageToken = tuple.nextPageToken {
                    // Goes recursive here. Oh the pain.
                    return intGetPages(pageToken: nextPageToken, pageGetter: pageGetter)
                        .startWith(tuple)
                } else {
                    return Observable.just(tuple)
                }
            }
}
```

If, for example, there are 100 pages, the last page will have to cascade up through 100 chained/recursive `Observable`s before it reaches the consumer.

I'm trying to figure out if there's a way I can compose the code such that tail call optimizations are made, and memory consumption doesn't grow with the number of pages.

**Comment by epatey** [comment]
I got the following to work but I had to rely on a bit of side-effect code and a `PublishSubject`. 

```swift
static public func getPages<Token, Result>(pageGetter: @escaping (_ token: Token?) -> Single<PageResult<Result, Token>>) -> Observable<Result> {
    return Observable.deferred {
        let nextPageTokenSubject = PublishSubject<Token?>()
        return nextPageTokenSubject
            .concatMap { (pageToken: Token?) -> Single<PageResult<Result, Token>> in
                pageGetter(pageToken)
                    .do(onSuccess: {
                        if let nextPageToken = $0.nextPageToken {
                            nextPageTokenSubject.onNext(nextPageToken)
                        } else {
                            nextPageTokenSubject.onCompleted()
                        }
                    })
            }
            .map { $0.content }
            .do(onSubscribed: { nextPageTokenSubject.onNext(nil) })
        }
}
```

This works for me, but I'm still curious if there's a way to avoid the imperative `do(onSuccess:` and subject stuff.

Notes:
- I had to use `deferred` in order to get a dedicated subject for each subscriber.
- `concatMap` was needed instead of `flatMap` to ensure the proper order.

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
