### ISSUE TITLE
What is the meaning of asObservable

### ISSUE THREAD

**Issue by m17603048828** [ReactiveX/RxSwift#1987]
What is the meaning of asObservable ????
I see the source code of asObservable! It just return self!,
I do not know  What is the meaning of asObservable 
请问：asObservable 就是返回self 有什么意义，或者特别的用法？？

`    public func asObservable() -> Observable<E> {
        return self
    }
`

**Comment by freak4pc** [comment]
It's a protocol conformance for `ObservableConvertibleType`. 

Regardless,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.

**Comment by m17603048828** [comment]
OK
