### ISSUE TITLE
Unable to use rx data source classes for UICollectionView and UITableView

### ISSUE THREAD

**Issue by marlowcharite** [ReactiveX/RxSwift#199]
For whatever reason I can't get my file to see the Rx data source classes even though I import RxCocoa. Is there something that I'm missing?

EDIT: I build through Carthage

**Comment by kzaher** [comment]
Hi @marlowcharite ,

Datasources files are located [here](https://github.com/ReactiveX/RxSwift/tree/master/RxDataSourceStarterKit).

We've tried to explain why we don't distribute them using RxCocoa project in README.md in that directory :)

I'm still trying to figure out what is the best way to distribute them.

**Comment by marlowcharite** [comment]
@kzaher does it make sense to have it be built separately ? I personally like the idea of just importing the modules I need where I need instead of copying the files into the project and having them brought in everywhere

**Comment by kzaher** [comment]
@marlowcharite totally agree :)

This is just intended as a temporary solution. 

I'm hoping that this could help people start some independent datasource projects for RxCocoa.

That could easily be a huge project on itself. There are so many use cases for which those data sources should be optimized that adding this to RxCocoa project could unnecessary extremely bloat the codebase.

On the other hand, I couldn't just say to people "hey, you can theoretically do this yourself", since the necessary update algorithm [isn't quite trivial](https://github.com/ReactiveX/RxSwift/blob/master/RxDataSourceStarterKit/Differentiator.swift#L212) :)

I've decided to code up a pretty generic solution that works, but I think it still needs some real final polish (adding documentation, etc).

Hope this makes sense :) We'll for sure try to solve this in future in some more maintainable way :) I'm still not sure what is the best way to do this :)

**Comment by marlowcharite** [comment]
Sounds good to me.

**Comment by carlosypunto** [comment]
En la hija km un lío también también hlklr BBN km VB he CFC
