### ISSUE TITLE
Extend BehaviorRelay

### ISSUE THREAD

**Issue by geor-kasapidi** [ReactiveX/RxSwift#1996]
Hi! BehaviorRelay has no value setter, so if Element is a complex type and we need update some property, we need to do something like this:

```swift
var value = relay.value
value.property = newValue
relay.accept(value)
```

To make updates more comfortable (and pseudo atomic), i wrote small extension:

```swift
extension BehaviorRelay {
    public func accept(_ f: (inout Element) -> Void) {
        var x = value
        f(&x)
        accept(x)
    }
}

...

relay.accept {
     $0.value = newValue
}
```

If this API is OK for you, I can make a PR - this extension saves a lot of my time :)

**Comment by isaac-weisberg** [comment]
I would like to quickly point out that whenever your architecture supposes that the object is the same and its mutable, it certainly goes against one of the primary FRP concept - functional purity. The need for this indicates that your architecture features some flaws.

We had the same case in some legacy code at work just recently, a subclass `BehaviorRelayX` with the same `accept(_:)` method. Looking down into the whole family of bindings occurring there revealed that this decision was only there just because it was too expensive (in terms of code writing time) to create a new value to be properly propagated into this reactive primitive.

In these situations there is just not that much changing inside the object. And this indicates that this complex type needs to be stripped down and the abstraction - decoupled into several reactive states, possibly incorporated into separate business logic units (presenters/controllers/view models).

It maybe useful for working with bad architecture but it certainly has no place in Reactive Extensions.

**Comment by hmlongco** [comment]
@isaac-weisberg "I would like to quickly point out that whenever your architecture supposes that the object is the same and its mutable, it certainly goes against one of the primary FRP concept - functional purity."

From my perspective, "functional purity" a a concept is fine, except that it's often at odds with most modern software development in that applications have state and exist primarily (if not solely) to manipulate that state. 

A BehaviorRelay in most RxSwift applications exists as a "source of truth" for some aspect of that state, say the information that exists for a user who logs into the app. It's expected to maintain that state (e.g. the current value) and to dispense that value to its subscribers, both those that exist now and those who may exist in the future. 

To keep the user information elsewhere is to, in effect, have two "sources of truth", the current state of the relay and the separately maintained value, and that too is generally considered to be a "bad thing".

If the user has, to continue the example, an enrollment flag and if the user can enroll at some point in the app, then we need to mutate that state and notify all of the current subscription chains that the change has occurred.

```
    func enrollUser() {
        user.accept { $0?.enrolled = true }
    }
```

And that's where this type of feature shines. I say type of feature because the implementation really could benefit from some sort of recursive lock or queue such that the update function is being called atomically.

That said, I doubt that a typical developer's code would be atomic if you were doing this on your own in some "classic" approach, say, recreating an entire non-mutable struct in order to flip a single value and then pushing that struct onto a publisher. 

(Let's not get into the whole argument on whether or not such a structure should be "mutable" in the first place. Most of the rules against that sort of thing came from other languages that lack Swift's copy-on-write value semantics.) 

All software has tradeoffs and we're often called to deal with "bad architectures" like a monolithic User struct we obtain from an API that's not under our control. Yes, it may be possible to create "several reactive states" but as you also point out yourself, it can also be too expensive (in terms of code writing time, debugging, maintenance, and so on) to create that code.

```
    lazy var currentEnrollmentStatus = Observable<Bool>
        .merge(sharedUser.map { $0.enrolled }, updatedEnrollmentStatus)
        .share(replay: 1, scope: .forever)

    private lazy var updatedEnrollmentStatus = PublishSubject<Bool>()

    private var user = BehaviorRelay<User?>(value: nil)
    private lazy var sharedUser = user.compactMap { $0 }

    func enrollUser() {
        updatedEnrollmentStatus.onNext(true)
    }
```

Our tools exist to support us and if a concept like "functional purity" starts to demand that I write 5x as much code to obtain it, then I have to start questioning the value of the concept.

Or at least determine if it is, after all, more a "guideline" than a rule. ;)

**Comment by freak4pc** [comment]
Hey all, we've argued this topic endlessly already :)

It's not something we plan on adding into RxSwift but should be easy enough making your own subclass of BehaviorRelay to do this if you're adamant enough. Thanks!
