### ISSUE TITLE
Adopt few Combine operators

### ISSUE THREAD

**Issue by MortyMerr** [ReactiveX/RxSwift#2007]
I understand that this repo doesn't aim to embed all operators from Combine. But IMO absence of Combine operators might be confusing for new users, which want to try being reactive before iOS 13.0
Of course "add operator because there is a similar one in Combine" is a bad reason, but they might quite useful. Here is a list, which can be appended with new Combine release. Even if we that repo doesn't want to adopt them - it will be good to see "No" explicit. 

- [ ] [`func replaceNil(with: T)`](https://developer.apple.com/documentation/combine/publisher/3204749-replacenil) - which is already implemented in https://github.com/RxSwiftCommunity/RxOptional but in a less performant way. I think that might be quite useful even if we have `.compactMap` already.

- [ ] [`func mapError(transform:)`](https://developer.apple.com/documentation/combine/publishers/maperror) - yes, we don't have typed errors in RxSwift, but sometimes there is a need to catch an error and replace it with another. I saw a few times implementation with `catchError` and throwing new inside of it. `.mapError` would be more descriptive.

- [ ] [`func output(at:) / func output(in:)`](https://developer.apple.com/documentation/combine/publishers/output) - `enumerated().skipWhile()` might be useful, but don't provide exactly same behaviour. 

- [ ] [`func measureInterval()`](https://developer.apple.com/documentation/combine/publishers/measureinterval) - might be quite tricky, but looks useful for building stream of events based on the frequency of upstream

- [ ] `max/min` operators, which is always added to [reactiveX](http://reactivex.io/documentation/operators/max.html)

- [ ] [`func contains(_ :)`](https://developer.apple.com/documentation/combine/publishers/contains)

- [ ] [count](https://github.com/RxSwiftCommunity/RxSwiftExt/pull/190/files) - maybe rethink solution about placing it to RxSwiftExt?

- [ ] [last(where:)](https://developer.apple.com/documentation/combine/publisher/3204716-last)

- [ ] [allSatisfy](https://developer.apple.com/documentation/combine/passthroughsubject/3204581-allsatisfy?changes=latest_minor)

As always I am really interested in your opinion and ready to contribute :)

**Comment by freak4pc** [comment]
I want to start with saying thanks for your work on this. 
My personal opinion is that we shouldn't add an operator **just because** it's part of Combine if it doesn't make sense to us. This is a large project and I think we should be careful with adding new operators without a good enough reason.

## Operators that I think might be a good fit: 

- count - it could be useful and it's basically an alias of `.toArray().map { $0.count }`

- contains - could also be useful in a way. right now the way to do this is some variation on `takeUntil(_:predicate:)` and mapping that result to a boolean

- allSatisfy - I think this _could_ useful, especially in the purpose of aligning with Swift's offering on Collection

## Operators I don't think are really useful: 

- replaceNil doesn't seem to provide any other value against `.map { $0 == nil ? x : y }` to my understanding

- min/max was already discussed and there was not enough community interest to add

- mapError don't really make sense in the context of Rx's contract specifically - how do you imagine it? 

- measureInterval - since we don't have a concept of demand/backpressure - this would be hard to implement and I'm also finding it hard to 

- last(where:) - I'm failing to see enough usecases for this to included in the core repo

- output: Again this is a case where it seems theoretically fun but I don't see good enough use cases that can't be achieved with enumerated + take/skip operators. 

Of course would love to hear other people's opinions.

**Comment by MortyMerr** [comment]
> My personal opinion is that we shouldn't add an operator just because

Of course, I fully agree with that.

> replaceNil doesn't seem to provide any other value against 

It's just shorter. And more important it allows capturing from properties without reference cycle
```swift
class Foo {
  private let defaultValue: String
  ...
  func bind() {
    observable.compactMap { $0 ?? self.defaultValue }.disposed(by: disposeBag) // reference cycle here
    observable.replaceNil(with: defaultValue).disposed(by: disposeBag) // ok
  }
}
```
Yes i can add capture list and it will be ok, but `replaceNil` makes it much more simplier.

`mapError` is suitable when I want to replace global scope of networks error to my own errors. Maybe, you will criticize that approach, but:
```swift
request.mapError { networkError -> Error in
   guard let error = networkError as? MoyaError else { return networkError }
   switch error.code {
   case someCode:
      return MyError.somethingWentWrong
   case anotherCode:
      return MyError.notBugButFeature
    default:
       return MyError.what
}
```

Please tell me what do you think. Maybe there is a better approach?
Fully agree with your point about other operators, will open PR soon

**Comment by freak4pc** [comment]
```
.map { $0 ?? b }
.replaceNil(with: b)
```

Is it really shorter? Regarding captures and reference-semantics, even if you do `.replaceNil(with: self.something)` you are capturing.

About `mapError` - its not about criticizing, it just doesn't seem like something generic enough to including in the repo. It would be the same as catchError to my understanding.

**Comment by MortyMerr** [comment]
> Is it really shorter? 

:) Not much shorter, nevertheless shorter, yes. 
>  Regarding captures and reference-semantics, even if you do .replaceNil(with: self.something) you are capturing.

Am I? Swift copy references when passes to methods, so it's completely safe to use `.replaceNil(with: self.property)`

> t just doesn't seem like something generic enough
Ok :)

**Comment by kzaher** [comment]
We aren't going to even start considering any combine based changes before Combine is released and baked into the iOS for obvious reasons.

**Comment by Vladlex** [comment]
> It's just shorter. And more important it allows capturing from properties without reference cycle
> ```
>     observable.map { $0 ?? self.defaultValue }.disposed(by: disposeBag) // reference cycle here
> ```

So why do you capturing `self` instead of `defaultValue`?
```
   observable.map { [defaultValue] $0 ?? defaultValue }.disposed(by: disposeBag) // no ref cycle now
```

**Comment by maxydey** [comment]
Doesn't it make sense to create separate repo for all Combine-cmpatability related extensions, like RxSwiftExt?
RxSwift if first of all Rx, and then Swift. The main repo should be as close to other Rx implementation as possible, that's it's main value

**Comment by freak4pc** [comment]
Not so much @maxydey - the fact the operator comes from Combine or RAC or whatever is really irrelevant. We just need to define which of these operaors are actually useful and make decisions upon that. 

Yes, we keep implementations as close to Rx, but still provide specifics around Swift language features, as it is RxSwift, after all.

**Comment by freak4pc** [comment]
Closing this in the meanwhile. I think we'll start pulling ideas based on community demand in various threads with the RxSwift 6 initial beta, as well as some ideas that were already added.
