### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by LGCooci** [ReactiveX/RxSwift#2008]
I just use the demo of RxSwift 5.0
<img width="803" alt="image" src="https://user-images.githubusercontent.com/51438812/59192653-c6133600-8bb5-11e9-93c2-14bdf866f6e5.png">

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/51438812/59192450-0d4cf700-8bb5-11e9-9863-dd25ab146c1d.png">

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
