### ISSUE TITLE
Bidirectional binding issue

### ISSUE THREAD

**Issue by pradeepvoleti** [ReactiveX/RxSwift#2045]
**Short description of the issue**:

I am doing Bidirectional binding between TextInput(UITextField) and BehaviorRelay(Model String). And subscribing both to observe the changes in textfield and model. 

In a scenario where I keep breakpoints in the subscribe closure and tap backspace once on text in UIText field, both the subscriptions are called twice and two letter are removed from textfield. If I don't keep the breakpoints both subscriptions are called once and only one letter is removed.

Note:
1. Not sure if this is an issue of RxSwift or not and 
2. This wont happen in realtime usage but want to know if I am doing any thing wrong.

**Expected outcome**:

In above setup on clicking backspace once only one letter needs to be removed.

**What actually happens**:

In above setup on clicking backspace once two letters are being removed.

**Self contained code example that reproduces the issue**:

```swift
import UIKit
import RxSwift
import RxCocoa

class ViewController: UIViewController {

    @IBOutlet weak var field: UITextField!
    let model = NameModel()
    let bag = DisposeBag()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        (field.rx.textInput <-> model.name).disposed(by: bag)
        
        field.rx.text.subscribe { (event) in
            print("Field event")
        }.disposed(by: bag)
        
        model.name.asObservable().subscribe(onNext: { (event) in
            print("Model event")
        }).disposed(by: bag)
    }
}

struct NameModel {
    var name = BehaviorRelay(value: "First")
}
// For bidirectional binding I'm using Operators.swift class from RxSwift Example project.
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift - 5.0
RxCocoa - 5.0

**Platform/Environment**

  - [ ] iOS

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [ ] easy, 100% repro

**Xcode version**:

```
10.2
```

**Installation method**:
  - [ ] CocoaPods

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
