### ISSUE TITLE
Debounce condition

### ISSUE THREAD

**Issue by zdnk** [ReactiveX/RxSwift#2050]
Hello,
I have sequence that generates `String?` I would like to pass it in the chain right away if it is `nil`, but debounce if it is anything else.

Example code:
```swift
      control.rx.text
            .distinctUntilChanged()
            .skip(1)
            .flatMap { string in
                return self.validate(field: field, input: string)
            }
            .map { errors -> String? in
                return errors?.errors.first?.message
            }
            .debounce(.seconds(1), scheduler: ConcurrentDispatchQueueScheduler(queue: .global()))
```

This code debounces all values.
What would be the right way to achieve the described solution?

**Comment by freak4pc** [comment]
You can debounce or not inside a flatMap based on the input.

Regardless,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
