### ISSUE TITLE
PublishSubject as PropertyWrapper

### ISSUE THREAD

**Issue by gringoireDM** [ReactiveX/RxSwift#2073]
With 5.1 version swift got empowered with `propertyWrapper` language feature.
Thinking about common patterns where propertyWrapper could be used I started to think about `PublishSubject`.

```swift
class Foo {
    var bar: Observable<Int> { _bar.asObservable() }
    private let _bar = PublishSubject<Int>()
}
```

This example is a classic common pattern that with property wrapper would reduce the amount of boilerplate the users has to write to reach this goal.

Having

```swift
@propertyWrapper
public final class PublishSubject<Element>
    : Observable<Element>
    , SubjectType
    , Cancelable
    , ObserverType
    , SynchronizedUnsubscribeType {

    ...
    public var wrappedValue: Observable<Element> { self.asObservable() }
    ...

}
```

we can rewrite `Foo` in this way.

```swift
class Foo {
    @PublishSubject var bar: Observable<Int>
}
```

The compiler will synthesise the private var `_bar` which will be a private publish subject. The compiler will stop the users from defining bar to be anything different than an `Observable`.

unfortunately, `@propertyWrapper` can't be defined as extensions, so a support to PropertyWrapper has to be done in RxSwift and it can't be done on a third party.

What do you think?

If you like the idea I can open a PR.

**Comment by gringoireDM** [comment]
Similarly BehaviourSubject and BehaviorRelay can have property wrappers too:

```swift
@propertyWrapper
public final class BehaviorSubject<Element>
    : Observable<Element>
    , SubjectType
    , ObserverType
    , SynchronizedUnsubscribeType
    , Cancelable {

    ....
    public var wrappedValue: Observable<Element> { self.asObservable() }
    public var projectedValue: Element {
        get { try! self.value() }
        set { self.onNext(newValue) }
    }
    ....
}
```

so that 
```swift
class Foo {
    var bar: Observable<Int> { _bar.asObservable() }
    let _bar = BehaviorSubject(value: 0)
    var $bar: Int { 
        get { try! _bar.value() }
        set { _bar.onNext(newValue) }
    }
}
```

would simply become

```swift
class Foo {
    @BehaviorSubject(value: 0) var bar: Observable<Int>
}
```

**Comment by freak4pc** [comment]
Saw your PR on this - first of all its best to wait for feedback on something this drastic _before_ making a PR. Even though I appreciate your work, obviously :) 

From a technical perspective this is nice, but it reminds me of #1639 where I personally had a very strong thought against hiding such implementation details. 

The fact people don't know `@Published` probably uses a CurrentValueSubject under the hood is strange to me, but here its even worse because this code base specifically had changes to remove `.value` setters, to get rid of the notion that "a stream can have a value". Streams don't have a value, only a snapshot in some specific time point. Having `Variable` before that worked with regular setters created a lot of confusion and abuse of how RxSwift can be best used. 

So, I'm torn. 

From one side - technologically this advancement of using property wrappers is really nice. BUT, it creates a massive hiding of implementation details which means reduced "technical responsibility" of how to compose things and make them work together (e.g. understand what these subjects actually do in some sense). 

All of this is speaking of Beahvior* - I don't really see how this fits Publish* stuff since they don't have a "current" notion at all (Event-based, not state-based).

Appreciate your work, and your thoughts on this :)

**Comment by gringoireDM** [comment]
Well my PR came for free after trying to see if it was possible before proposing. :D It doesn't have to be approved. :) If we like it, we can use it. otherwise I don't mind. :)

**Comment by freak4pc** [comment]
Sure thing :) anyways just to keep things focused, let's move the discussion to the PR itself so we don't have two parallel discussions.
