### ISSUE TITLE
need a subject that never completes and without an initial value

### ISSUE THREAD

**Issue by mesheilah** [ReactiveX/RxSwift#2106]
I am aware that the `BehaviorRelay` is a wrapper around `BehaviorSubject`,  it completes by itself when gets deallocated and we don't have to call onCompleted manually. However, I can't find a way to create a subject that never completes (or at least completes by itself like BehaviorRelay) but without an initial value. 
I don't want to add some ugly workarounds like skip(1) to  as it distorts my code.

p.s. `ReplaySubject` with bufferSize of 1 will not satisfy my requirement in that it has to complete somewhere in the code.

**Comment by freak4pc** [comment]
Sounds like you need a PublishRelay, unless you also won’t want a replay in which case it doesn’t make much sense.

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
