### ISSUE TITLE
Adding share to the Single

### ISSUE THREAD

**Issue by NohEunTae** [ReactiveX/RxSwift#2172]
**Short description of the issue**:

One of the great examples of using Single is to apply it to the network requests.
Also, another great example of using share method is to prevent duplicate calls that reaches from those network requests.
Usually whileConnected attribute/option is recommended to be applied when using share method.
However, in my opinion, there might be a problem when applying it properly to the Single. The problem is, in Single, the complete attribute is set automatically after the connection succeeds, that means the connection is off.
So the way to solve this problem is to convert Single to Observable which ignores Single’s terminate options and returns that converted Observable.

**Expected outcome**:

Performing work ...
Performing work ...

**What actually happens**:

Performing work ...
Performing work ...
Performing work ...
Performing work ...

**Self contained code example that reproduces the issue**:

```swift

import RxSwift

var disposeBag = DisposeBag()
let shareResult = Single.deferred { () -> PrimitiveSequence<SingleTrait, Void> in
    print("Performing work ...")
    return Single.just(())
}.asObservable().share(replay: 1, scope: .whileConnected)

shareResult.subscribe().disposed(by: disposeBag)
shareResult.subscribe().disposed(by: disposeBag)
disposeBag = DisposeBag()

shareResult.subscribe().disposed(by: disposeBag)
shareResult.subscribe().disposed(by: disposeBag)
disposeBag = DisposeBag()
       
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

RxSwift 5.5.1

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
11.3.1
```

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Interesting thought. Adding a share(replay:) for Single would be quite some work given the nature of what you mentioned (e.g. the fact it would immediately disconnect on completion). 

I'll try taking a look, but right now bug fixes etc are the main priority. If you have some ideas and want to take a crack at a PR i'd love to help out :)

**Comment by funct7** [comment]
I believe this is comes from two misunderstandings:

- **A misunderstanding of how `asObservable()` works**: Casting a `Single` to an `Observable` through `asObservable()` doesn't really change the nature/contract of the original stream that is `Single`, which is to complete the stream upon emitting exactly one value.
- **A misunderstanding about `whileConnected`**: The reason that `observableFactory` was called twice even though `shareResult` was subscribed to twice before the `DisposeBag` instance was replaced seems to stem from the fact that the stream is already completed. In other words, the second subscription to `shareResult` only looks like it's happening "while connected," but it's not. The first subscription already ended.

In fact, the exact same behavior can be reproduced with an `Observable`:

```swift
var disposeBag = DisposeBag()
let shared = Observable<Int>
    .create { observer in
        print("Performing work ...")
        observer.onNext(42)
        observer.onCompleted()
        return Disposables.create()
    }
    .share(replay: 1, scope: .whileConnected)

shared.subscribe().disposed(by: disposeBag)
shared.subscribe().disposed(by: disposeBag)
disposeBag = DisposeBag()

shared.subscribe().disposed(by: disposeBag)
shared.subscribe().disposed(by: disposeBag)
disposeBag = DisposeBag()
```

Also, if you delay the emission of the original example, you get the shared behavior that you expected:
```swift
var disposeBag = DisposeBag()
let shareResult = Single.deferred { () -> PrimitiveSequence<SingleTrait, Void> in
    print("Performing work ...")
    return Single.just(()).delay(.milliseconds(10), scheduler: MainScheduler.instance)
}.asObservable().share(replay: 1, scope: .whileConnected)

shareResult.subscribe().disposed(by: disposeBag)
shareResult.subscribe().disposed(by: disposeBag)
print("replacing dispose bag")
disposeBag = DisposeBag()

shareResult.subscribe().disposed(by: disposeBag)
shareResult.subscribe().disposed(by: disposeBag)
print("replacing dispose bag")
disposeBag = DisposeBag()
```

In conclusion, the result of the example is not because the `Single` stream wasn't shared, but because the second subscription happens after the stream completed, and `SubjectLifetimeScope.whileConnected` means that the stream will be shared while there is at least one subscription AND the stream hasn't completed.

Maybe the two points I mentioned should be made clear in the documentation. (I also learned them the hard way)

### A solution to share the result of a `Single`
And I'm just going to post a solution to [the question](https://github.com/ReactiveX/RxSwift/pull/2198#issuecomment-658228035) that was asked in #2198 for future readers:

```swift
var disposeBag = DisposeBag()
let shareResult = Observable.create { observer in
    Single.deferred { () -> PrimitiveSequence<SingleTrait, Void> in
        print("Performing work ...")
        return Single.just(())
    }.subscribe(onSuccess: observer.onNext)
}.share(replay: 1, scope: .whileConnected)

shareResult.subscribe().disposed(by: disposeBag)
shareResult.subscribe().disposed(by: disposeBag)
disposeBag = DisposeBag()

shareResult.subscribe().disposed(by: disposeBag)
shareResult.subscribe().disposed(by: disposeBag)
disposeBag = DisposeBag()
```

What the OP wanted is to have the result of a network call shared across different subscriptions while connected, so one could just wrap the whole thing inside an `Observable` while ditching the call to complete the stream.

**Comment by freak4pc** [comment]
This is a 4 year old thread 😱
