### ISSUE TITLE
`ifEmpty` does not seem to work on ReplaySubject

### ISSUE THREAD

**Issue by Nickersoft** [ReactiveX/RxSwift#2177]
**Short description of the issue**:

I'm trying to use `withLatestFrom` on to combine the latest value from a ReplaySubject with a source observable. Because when my view is initialized the subject theoretically has an empty stream, I'm attempting to use `.isEmpty(default: [])` to provide an initial value so my observable stream runs on first load. However, despite using `isEmpty`, the stream still seems to be terminated due to the fact the ReplaySubject isn't omitting anything.

**Expected outcome**:

On first load, using `ifEmpty` on a ReplaySubject should return a default value and allow `withLatestFrom` to continue the observable stream.

**What actually happens**:

The stream gets terminated because `withLatestFrom` doesn't omit anything.

**Self contained code example that reproduces the issue**:

The below code outputs nothing when it seemingly should output `"Hello World", []`

```swift
let mySubject = ReplaySubject<[String]>.create(bufferSize: 1)
let disposeBag = DisposeBag()

Observable
    .just("Hello World")
    .withLatestFrom(mySubject.ifEmpty(default: []), resultSelector: { ($0, $1) })
    .subscribe(onNext: { print($0, $1) })
    .disposed(by: disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**
5.1.0

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 11.4.1 (11E503a)
```

**Installation method**:
  - [ ] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules
  - [x] Swift Package Manager

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by dimitris-c** [comment]
This isn't an issue with ReplaySubject. 

The sample code above outputs nothing because there is no event produced from the ReplaySubject. 
Please also note that `ifEmpty()` will get called when the source observable emits empty, such as `Observable.empty()`. It's not a check on the associated value within a given stream.

If you have more questions, you can join the slack channel. http://slack.rxswift.org

**Comment by freak4pc** [comment]
Hey @Nickersoft - I think you misunderstood the operator.
`ifEmpty` will switch to a second observable if the first one is already completed and didn't emit anything (both terms must be correct). Your subject doesn't fill that condition here.

Aas @dimitris-c (thank you!) mentioned - usually "how to" questions should go into Slack or Stack Overflow, since we're trying to keep the repo bug-oriented.

See also: 
http://reactivex.io/documentation/operators/defaultifempty.html

Thanks!
