### ISSUE TITLE
CollectionView

### ISSUE THREAD

**Issue by Odyflame** [ReactiveX/RxSwift#2276]
**Short description of the issue**:

I'm practicing RxSwift and doing some task with searchBar and CollectionView. 
when i run the app, collectionview show giphy files.
but when i input some text in searchBar, collectionView doesn't reload any data. so there's empty cell when searchBar has text. 
when i change collectionview with tableview, it works! 
i think it is an issue and i post here..

```swift
  code goes here

  let _ = gifSearchBar.rx.text.orEmpty
            .throttle(.milliseconds(500), scheduler: MainScheduler.instance)
            .flatMapLatest { (query) -> Observable<[GIFViewModel]> in
                
                guard let model = self.gifDataViewModel else { return .just([]) }
                if query.isEmpty {
                    return model.fetchGifViewModels().catchErrorJustReturn([])
                }
                print("search..")
                return model.searchGifViewModels(keyword: query)
            }.bind(to: gifCollectionView.rx.items(
                    cellIdentifier: SearchCollectionViewCell.reuseIdentifier,
                    cellType: SearchCollectionViewCell.self)) { row, gif, cell in
                
                print("cell..")
                
                cell.configure(gif: gif)
            }.disposed(by: disposeBag)
```

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _version or commit here_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode version goes here: 12.3
```

:warning: Fields below are optional for general issues or in case those questions aren't related to your issue, but filling them out will increase the chances of getting your issue resolved. :warning:

**Installation method**:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [x] I have a small code base
  - [ ] I have a significant code base

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
