### ISSUE TITLE
How do I test an observable that doesn't completes?

### ISSUE THREAD

**Issue by m-makhovyk** [ReactiveX/RxSwift#2314]
I have a method that observes changes in Realm database (I'm using RxRealm)
```
class CartManager {
      func getCartData() -> Observable<CartData> {
          let cartItems = realm.objects(CartItemEntity.self)
          return Observable.array(from: cartItems)
              .map { 
                   // some transformations here
              }
      }
}
```
I want to test that when I insert  object into database, observable emits event. But since this observable doesn't completes I can't use `.toBlocking.toArray()` because it never exits. What is preferred way to test case like this?

**Comment by freak4pc** [comment]
Hi,

this doesn't look like an issue with the project itself but more of a "how do I do XXX" question.
Please ask these kinds of questions in our slack channel http://slack.rxswift.org/ or some other more appropriate communication channel.

We are asking this because:

* we can't scale development of this project if people are reporting false issues and we are spending lot of time answering those directly instead of working on this project.
* all who are interested in development of this project and watching it are being spammed by irrelevant information.
* those who want to know what are currently unresolved serious issues are having a harder time figuring it out because list is spammed by non issues, so the real issues are masked.

Thank you for understanding.
