### ISSUE TITLE
Bag seems to be a combination of Dictionary and ContiguousArray, why?

### ISSUE THREAD

**Issue by peckermax** [ReactiveX/RxSwift#2352]
In the comment of Bag.swift, the time complexity of insertion and deletion is written to be O(n). And there are some points make me confused. 
 1. To best of my knowledge, for ContiguousArray, the time complexity of insertion is O(1) unless resizing happens.
 2. ContiguousArray and Dictionary have similar performance for insertion and deletion. But the elements are all stored in Dictionary when the number of elements exceeds 30.
 3. How to obtain the capacity 30.

Could you please give me a hand with this? Thanks.

**Comment by freak4pc** [comment]
Hey, I'm sorry but we don't usually provide this kind of support (what is the complexity of code X) - since it isn't a feature or a bug. The code is open source and each individual can analyze and pick what works.

Sorry if this seems a bit harsh but we're trying to focus on Issues related to bugs specifically and not more "academic" support requests, since the contributor's time is limited eventually.

Perhaps the Slack channel can assist: http://slack.rxswift.org

**Comment by peckermax** [comment]
> Hey, I'm sorry but we don't usually provide this kind of support (what is the complexity of code X) - since it isn't a feature or a bug. The code is open source and each individual can analyze and pick what works.
> 
> Sorry if this seems a bit harsh but we're trying to focus on Issues related to bugs specifically and not more "academic" support requests, since the contributor's time is limited eventually.
> 
> Perhaps the Slack channel can assist: http://slack.rxswift.org

Thanks for your reply.
