### ISSUE TITLE
KVO enum type enhancement and context

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#236]
AVPlayer has an enum property. it's an integer enum type AVPlayerStatus.

So I must write in this format to observe

            _ = self.player.rx_observe("status").subscribeNext{ (value: Int?) -> Void in
                guard let value = value else {
                    print("not found")
                    return
                }
                guard let status = AVPlayerItemStatus(rawValue: value) else {
                    print("not found")
                    return
                }

or use .map operator map an Int? to AVPayerItemStatus?

instead of subscribe the AVPlayerItemStatus enum type directly

            _ = self.player.rx_observe("status").subscribeNext{ (status: AVPlayerItemStatus?) -> Void in
                guard let status = status else {
                    print("not found")
                    return
                }

This is because NSNumber cannot use "as" operator to transform to an Int enum type

    class KVOObservable<Element>{
        ...
    func subscribe<O : ObserverType where O.E == Element?>(observer: O) -> Disposable {
        let observer = KVOObserver(parent: self) { (value) in
            if value as? NSNull != nil {
                observer.on(.Next(nil))
                return
            }
            observer.on(.Next(value as? Element))    //!!! This line should be extended for raw enum values.
        }

--------------------------
Another issue is, is it better to add context in KVC?
in _RXKVOObserver.h

        @implementation _RXKVOObserver
        [self.target addObserver:self forKeyPath:self.keyPath options:options context:nil];//!!! better for adding a context?

--------------------------
is it better to move rx_observe into RxSwift instead of RxCocoa? 

Because rx_observe is for NSObject (Foundation framework) instead of Cocoa Touch (UIKit framework)

**Comment by kzaher** [comment]
Hi @frogcjn :)

I have done some investigations regarding your request.

For us to be able to include something like 
```
_ = self.player.rx_observe("status").subscribeNext{ (status: AVPlayerItemStatus?) -> Void in
            guard let status = status else {
                print("not found")
                return
            }
```

We would need to have `AVPlayerItemStatus` conform to some protocol type. Even though `AVPlayerStatus` is declared as `AVPlayerStatus: Int` it does not conform to `IntegerType` or any other protocol that we could use to automate this.

The closest thing that we can do to support this is to define our own protocol and extension inside of RxCocoa:

```
public protocol EnumConvertibleFromInt {
    init?(rawValue: Int)
}

extension NSObject {
    public func rx_observe<T: EnumConvertibleFromInt>(_ keyPath: String, options: NSKeyValueObservingOptions = [.New, .Initial], retainSelf: Bool = true) -> Observable<T?> {
        return rx_observe(keyPath, options: options, retainSelf: retainSelf)
            .map { (value: NSNumber?) in
                guard let value = value else {
                    return nil
                }

                return T(rawValue: value.integerValue)
        }
    }
    ....
```

... and then you would need to do in your code

```
extension AVPlayerStatus : EnumConvertibleFromInt {
}
```

... before be able to do 

```
_ = self.player.rx_observe("status").subscribeNext{ (status: AVPlayerItemStatus?) -> Void in
            guard let status = status else {
                print("not found")
                return
            }
```

I couldn't find any protocol that `AVPlayerItemStatus` or any other enum that has backing `Int` conforms to. 

Any suggestions or ideas here?

---------------

As far as for second part of question I understand what is causing the confusion. There are multiple possible interpretations of project names. This is how I see responsibilities of those two projects:

* RxSwift - pure reactive minimal core. It contains only implementation of 
    * basic interfaces
    * operators
    * schedulers
    * general purpose subjects
... everything else that isn't in the service of concept should be somewhere else.

* RxCocoa - integrations with cocoa environment (both Cocoa and Cocoa touch).

I would like to look at RxSwift project as something that makes sense on other platforms also (like Linux). And yes, I understand that we are using some classes and functions currently in it that are specific to `Foundation` like `NSRecursiveLock`, dispatch queues, `OSAtomicCompareAndSwap32` .... , but those should have some kind of equivalents on other platforms. 

And yes, I currently don't have a clear plan how to port this to Linux since I have no idea what will Swift team come up with when they open source it.

That being said, I'm guessing that using `NSObject` KVO APIs makes most sense in only Apple ecosystem, so that's why it's in RxCocoa project.

Hope this makes sense.

**Comment by frogcjn** [comment]
swift has a RawRepresentable protocol, and its RawValue == Int, This is for the int enum type.
So the enum int type automatically conform to RawPresentable protocol with its RawValue == Int
the enum string type is the same situation with its RawValue == String

**Comment by kzaher** [comment]
Thnx, this makes this a lot simpler :)

I knew there was some protocol I was missing, but couldn't find it :)

**Comment by frogcjn** [comment]
And there is also an OptionSetType, that provide options. This is also an RawRepresentable.
so I think just to implement RawRepresentable is OK for both enum and optionSet type in system framework.

Swift's protocol system is huge and not easy to master. When I want to write a protocol with type constraint, it is a nightmare.

**Comment by kzaher** [comment]
Improvements for `RawRepresentable` and KVO were just released.
