### ISSUE TITLE
Need better explanation / examples for Driver

### ISSUE THREAD

**Issue by fpillet** [ReactiveX/RxSwift#275]
Documentation for `RxCocoa` Units is incomplete and could use some work. `Driver`, in particular, could use some additional explanation as well as concrete use cases to better help understand what it's good at and what advantages it has.

**Comment by carlosypunto** [comment]
While we improve Driver's documentation, think this:

```
let intDriver = sequenceOf(1, 2, 3, 4, 5, 6)
    .asDriver(onErrorJustReturn: 1)
    .map { $0 + 1 }
    .filter { $0 < 5 }
```

is as:

```
let intObservable = sequenceOf(1, 2, 3, 4, 5, 6)
    .observeOn(MainScheduler.sharedInstance)
    .catchErrorJustReturn(1)
    .map { $0 + 1 }
    .filter { $0 < 5 }
    .shareReplay(1)
```

**Comment by carlosypunto** [comment]
And for subscriptions use `drive` instead `subscribe`

**Comment by fpillet** [comment]
Thanks, Carlos. I'm looking forward to seeing improved documentation (helps quickly get up to speed with the framework). I have a strong RAC2/Obj-C experience, just trying to remap my habits to RxSwift!

**Comment by carlosypunto** [comment]
Welcome!

**Comment by kzaher** [comment]
Yep yep, I'll try to document why/how soon :)

In my GTD list :)

**Comment by IanKeen** [comment]
+1 for this, im currently using PublishSubject for pretty much everything because I'm unsure about what characteristics each Observable brings to the table :)

**Comment by kzaher** [comment]
Yeah, it's just a tiny builder/dsl for `Observables`. I think this should help me and others a lot with ensuring you can safely bind values to UI.

This is totally optional, but makes compiler think instead of me about boring things and warn me when I've forgot to handle unexpected errors, or binding from background thread or doing something I should have when dealing with UI applications.

Hoping people will like it :)

It's already there, tested and working, just need to document it, that's the final step.

**Comment by kzaher** [comment]
We've added explanation in `Units.md`. Also added parallel example (GitHub signup) using both vanilla observables and Driver. Unit tests are included. I think this we can close this now :)

We can reopen it if necessary.

**Comment by vanitaladkat** [comment]
Units.md seems to removed from latest version of RxSwift. Unable to find . can you update?

**Comment by Thiryn** [comment]
Units are Traits now : see [Traits.md](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Traits.md).
