### ISSUE TITLE
delegateAssociatedObjectTag should be open in Swift 3

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#282]
`_forwardToDelegate` might be dealloc, and there is an `EXC_BAD_ACCESS` happened in 

`respondsToSelector` function of class `_RXDelegateProxy`
```objective-C
[self._forwardToDelegate respondsToSelector:aSelector]
```

**Comment by frogcjn** [comment]
I believe the reason is `forwardToDelegate` is an `assign` property, if we change it to `weak` property, it will work fine with dealloc pointer.

**Comment by frogcjn** [comment]
Also see
http://stackoverflow.com/questions/26553924/what-is-the-difference-in-swift-between-unownedsafe-and-unownedunsafe

`assign` for object pointer in objective-C is similar behavior of `__unsafe_unretained`

**Comment by kzaher** [comment]
Hi @frogcjn ,

yeah, I think we could change this behavior to be something more user friendly :)

This shouldn't happen in a well behaved code :) that means that `_forwardToDelegate` was deallocated before the delegate proxy.

If this happened during if you were using `rx_setDataSource` or `rx_setDelegate`, you probably didn't add result disposables to `disposeBag` (I think we need to add unused warnings there also :) 

Could you share the code example that was causing this?

I think that it's not only sufficient to change the type of the property from `__unsafe_unretained` to `weak`, but to also add observing when is `_forwardToDelegate` deallocated, and in that case dispose that result disposable automatically.

If that wouldn't happen, I think you could end up in a state where table view asks for `UITableViewCell`, and none can be returned because `_forwardToDelegate` is deallocated.

**Comment by frogcjn** [comment]
when viewAppear, I just use:
`.rx_delegate.observe(...).addDisposeTo(controlDisposeBag)`

when viewDisappear:
`controlDisposeBag = DisposeBag()`

**Comment by frogcjn** [comment]
I found the problem in my code.
I need to override delegate associate object tag, for more than one proxy.
For example, `UISearchController` has a `delegate` and a `searchResultsUpdater`
so this two property proxies should have different tags. So I just need add this lines into my Proxy class.

```swift
var searchResultsUpdaterAssociatedTag: UInt8 = 0

class RxSearchControllerResultsUpdatingProxy{
    override class func delegateAssociatedObjectTag() -> UnsafePointer<Void> {
        return identity(&searchResultsUpdaterAssociatedTag)
    }
}
```swift

**Comment by kzaher** [comment]
@frogcjn :+1:

**Comment by frogcjn** [comment]
New Issue in Swift 3, because I override `delegateAssociatedObjectTag`, but `delegateAssociatedObjectTag` is public not open.

**Comment by kzaher** [comment]
Hi @frogcjn ,

I've made them `open`. 

https://github.com/ReactiveX/RxSwift/commit/8eb345853f58a8869f8a3651447f1fb6ae090487

Closing this one.
