### ISSUE TITLE
Consider releasing 2.0.0

### ISSUE THREAD

**Issue by ashfurrow** [ReactiveX/RxSwift#287]
I'm using this RxSwift in production, and I think a lot of people here are to :wink: Is there any reason to keep it prerelease? It's affecting people's decision to use the library: 

https://twitter.com/dannolan/status/669349456211415040

**Comment by bontoJR** [comment]
Fair question, as far as I remember the pre-release was to await Swift being Open Source and available on *nix platforms before moving forward. Considering that there's no real schedule about this and that the **feeling** is that it won't make it by the end of the year, I agree that a `2.0.0` release should be considered.

**Comment by kzaher** [comment]
Hi guys :),

**I would first like to say that there is nothing unstable in beta versions as far as I'm aware of, and they are shippable to app store.** Even alpha releases were totally shippable, otherwise I would warn people when they've said they are planning to ship it to app store.

Before every release we run full unit tests on all configurations / os versions, automation and integration tests. This process is automated and lasts somewhere around 1.5h. There is nothing different that we would do for release 2.0.0 version. The process would be the same :) We do our best to make every release as stable as possible.

**The only reason right now why this is in beta is because I'm doing tweaks to public interface and trying to make it more user friendly. That will cause some small breakages in public interface, but nothing drastic.**

The original plan was to wait for Swift open sourcing, but it looks like that won't be so soon. 

We have moved cross-cross platform solution to 3.0. There will probably be previews for linux version a lot sooner then 3.0 so people can play with it.

The reason why we didn't release 2.0.0 is actually because of semantic versioning. People expect that after we ship 2.0.0, all 2.* APIs will be backwards compatible and public interface sealed.

I'm still polishing some parts of public UI and would want to be sure that once this thing is out, we won't start working on 3.0 a month from that :)

I need to think about what is the best way to do some parts of library, and finish them:

* general observing of method calls (I've got it working yesterday, working on unit tests now)
* expose https://github.com/ReactiveX/RxSwift/issues/143
* try to figure out can I somehow additionally simplify table view binding code (compiler reports silly errors that confuse users and also me sometimes)
* document and possibly do some small tweaks to `Driver`s
* expose unit testing classes from our testing targets together with test schedulers, observable/observer mocks, etc ...
* try out some concepts on my mind to see how they work with current public interface
* remove all deprecated APIs from 2.0.0 version (I'm leaving those deprecated APIs in code for now to help people make the transition)

After that, I think we should be able to seal public API for version 2.0.

I expect this to be done in time frame of month and a half (New Years Eve 2016).

I do understand why people are anxious about using something that has beta label on, but I'm assuming there would be a lot more anger if I would claim that this public interface is final, when there would be some breakages that aren't backwards compatible.

Suggestions are welcome ...

**Comment by fpillet** [comment]
Regarding the deprecated APIs, maybe split them out in a RxCompat module ?

Also, would you mind releasing a 2.0.0-beta4 ? Reason I'm asking is we're waiting on the replayAll() addition to close https://github.com/ashfurrow/Action/issues/3

Thanks for all the hard work. RxSwift is delightful to work with.

**Comment by orta** [comment]
If you want another reason for moving to non-beta, pretty soon cocoapods.org will not show the latest README for a pod if it's a pre-release

**Comment by kzaher** [comment]
Hi guys :)

Believe me, I would love to release 2.0.0. I think we have really lot of cool stuff in here :)

I'll do my best to release 2.0.0 as soon as possible :)
¯\\\_(ツ)\_/¯ 

I think next week is last beta. Then we have max two RCs, and then release hopefully :)

@fpillet I'll release 2.0.0-beta.4 on Monday. We've dropped down on bi weekly release schedule since the project has grown quite a lot recently, and there is a lot of communication happening :)

If we had some critical problem or something, I would consider releasing hotfix immediately for sure :) Hope that's ok with you :)

**Comment by carlosypunto** [comment]
I'm with @khazer, the beta is stable and secure for production but the API is not closed. Very well it's methodology. 'Running is for cowards and bad bullfighters' is a Spanish saying :-) I also want the GM now.

**Comment by humblehacker** [comment]
Not that it's needed, but here's another argument in favor of releasing soon.  I got this when I tried to submit my build to the app store:
![screen shot 2015-12-04 at 2 13 51 pm](https://cloud.githubusercontent.com/assets/117582/11602725/56cd4024-9a91-11e5-8c1f-9658634f933a.png)

**Comment by Spencevail** [comment]
I've been having the same problem as @humblehacker, I imagine everyone who is using this in production is as well. 

Also, as I'm sure everyone is well aware, [Swift has been open sourced](https://github.com/apple/swift), so you can check that box off your list. Would love to see an official 2.0.0 release here in the near future.

**Comment by Entea** [comment]
Yeah, I'm affected by the same problem as @humblehacker 
Would love to see `2.0.0` soon

**Comment by Junus** [comment]
I also have same problem uploading to AppStore :(

**Comment by humblehacker** [comment]
Until the release comes, here's my workaround. If you're using Cocoapods, just tack this on the end of your Podfile:

````ruby
post_install do |installer_representation|
  fix_bundle_version('RxSwift')
  fix_bundle_version('RxCocoa')
end

require 'plist'

def fix_bundle_version(pod)
  filename = "Pods/Target Support Files/#{pod}/Info.plist"
  plist ||= Plist::parse_xml(filename)

  # Make sure bundle version conforms to major.minor.patch
  # e.g. strip off any '-beta' modifiers
  
  version = plist['CFBundleShortVersionString']
  new_version = version.match(/\d+\.\d+\.\d+/).to_s
  if version == new_version
    puts "Versions match.  This fix_bundle_version hack may no longer be necessary"
    return
  end

  plist['CFBundleShortVersionString'] = new_version
  plist.save_plist(filename)
end
````

**Comment by kzaher** [comment]
It is done :)

**Comment by ashfurrow** [comment]
🎉🎉🎉

**Comment by carlosypunto** [comment]
👏👏👏👏👏👏
