### ISSUE TITLE
How to use rx_delegate to deal with optional methods which has return value?

### ISSUE THREAD

**Issue by frogcjn** [ReactiveX/RxSwift#300]
for example, there is a TableVIew, and I want to use `rx_delegate` to deal with
`scrollViewShouldScrollToTop(scrollView: UIScrollView) -> Bool`
and I want to return false, and use a custom action to replace the original scroll to top action.

for general, any delegate function needs a return value as a control, can 'rx_delegate' deal with this kind of case?

**Comment by kzaher** [comment]
Hi @frogcjn ,

I'll explain it in detail tonight, I'm in small rush now :) Wouldn't want to miss something :)

**Comment by kzaher** [comment]
Hi @frogcjn ,

When `forwardToDelegate` is set, calls are always forwarded to `forwardToDelegate` (including required or non required methods, having return type or not).

Currently you would just implement that `scrollViewShouldScrollToTop ` method and set implementor to `forwardToDelegate`. People usually use  UIViewController but you can ofc use any class.

We wanted to really reduce impedance mismatch between reactive methods and normal delegate mechanism, so I think this is kind of reasonable compromise.

--------
Below this line is explanation what else is planed and explanation how this thing work in more detail.


So far all proxies are still private, and that also includes `RxScrollViewDelegateProxy`.

The plan is to expose those delegate proxies before 2.0.0 interface is sealed. 

For every delegate proxy a corresponding virtual method called `func rx_createDelegateProxy()` exists.

There are 2 lightly different scenarios with delegate methods that have return types. Methods can be ...

#### Required
If method is required, then a sensible default implementation needs to be chosen in corresponding delegate proxy (the same is valid for table/collection view data sources). Once that proxy is set, those required methods need to return something.
For table view data source, that's `TableViewDataSourceNotSet`.

#### Optional
For optional methods there is a various number of implementations possible. The default one that we are using now is just proxing those optional methods to `forwardToDelegate`.

When we expose those delegate implementations, then people will be able to create their versions with lambads instead of using `forwardToDelegate` or some other convenience mechanisms.

**Comment by kzaher** [comment]
We've exposed delegate proxies. I guess we can consider this closed. Let me know if there are some further questions regarding this.
