### ISSUE TITLE
Cocoa pods TRACE_RESOURCES setup

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#301]
Hi, guys
Sorry if its not related to Rx, but could you please describe how should I set up my podfile in order to be able to see resources in the debug mode

Because now I do this manualy

**Comment by kzaher** [comment]
Hi @sergdort ,

I believe you need a post install hook.

More info here

http://www.mokacoding.com/blog/cocoapods-and-custom-build-configurations/

... and you need to set these Swift flags (I believe it is called OTHER_SWIFT_FLAGS in configuration).

<img width="731" alt="screen shot 2015-11-30 at 22 13 10" src="https://cloud.githubusercontent.com/assets/1641148/11484662/92e22744-97af-11e5-9998-7a4690f6d171.png">

**Comment by sergdort** [comment]
Hi, @kzaher  
Thanks, I did this with example of this post http://marginalfutility.net/2015/10/11/swift-compiler-flags/

If somebody interested this is my post install hook, I also did what you said with the app target, in order do use #if macro

```Swift
   #if TRACE_RESOURCES
....
   #endif
```

```Ruby
post_install do |installer|
   installer.pods_project.targets.each do |target|
      if target.name == 'RxSwift'
         target.build_configurations.each do |config|
            if config.name == 'Debug'
               config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
            end
         end
      end
   end
end

```

**Comment by scotteg** [comment]
Thanks @sergdort and @kzaher, that `post_install` hook did the trick! I only needed to add the `post_install` hook in order to access `RxSwift.resourceCount`. Adding the compiler flag (using whatever name) just lets you conditionally execute whatever code you write in the `#if #endif` block. Another way to do this is to set an environment variable in the scheme...

![screenshot 2016-04-20 03 57 35](https://cloud.githubusercontent.com/assets/1337867/14668921/1bb7f038-06ac-11e6-91e5-8b3f1558b56d.png)

...and then conditionally check it using `NSProcessInfo`:
```
if NSProcessInfo.processInfo().environment["TRACE_RESOURCES"] != nil {
  print(RxSwift.resourceCount)
}
```
That way you can just check/uncheck a box when you want to enable or disable certain code. 😀

**Comment by caoer** [comment]
we can use macro now. 
![image](https://user-images.githubusercontent.com/225856/89187214-8f755780-d5cf-11ea-9dce-d7bc827a5b76.png)


```
   #if TRACE_RESOURCES
....
   #endif
```
