### ISSUE TITLE
repeatElement() and concat doesn't work as expected

### ISSUE THREAD

**Issue by Yoncise** [ReactiveX/RxSwift#315]
I have undetermined resources need to be fetched from server. I tried to accomplish this by using repeatElement() and concat() operator like this:

    repeatElement(0, CurrentThreadScheduler.instance).map({ _ -> Observable<[Task]> in
        // API.getTasks() uses Alamofire to request data
        return API.getTasks(loggedUser, after: loggedUser.taskPullTime)
    }).concat().takeWhile({ (tasks) -> Bool in
        return tasks.count > 0
    })

Unfortunately, repeatElement will just emit item without waiting for old one being handled. In another word, subscribe execution is not serial.

I used same strategy inspired from [here](http://stackoverflow.com/a/29594194/2408447) in my Android project. Everything works fine.

**Comment by Yoncise** [comment]
I think that Alamorefire executes in a private serial queue is the reason.
However, I can not figure out how to solve this problem.

**Comment by kzaher** [comment]
Hi @Yoncise ,

I believe your original solution is relying on specifics of RxJava back pressure mechanism. 

Unfortunately not all Rx implementations have that back pressure mechanism.

Fortunately there is a way to do paging in way that should work across all versions no matter do they have backpressure mechanisms or not.

This is kind of a sketch of solution. You can just paste it into our playground and check it out
```
import RxSwift
import Foundation
import XCPlayground

func loadPageFromServer(page: Int) -> Observable<[Int]> {
    return just([
        page * 100 + 0,
        page * 100 + 1,
        page * 100 + 2,
        page * 100 + 3,
        page * 100 + 4
    ]).delaySubscription(0.1, MainScheduler.sharedInstance)
}

func pagesStartingWith(page: Int) -> Observable<[Int]> {
    return loadPageFromServer(page).concat(deferred {
        pagesStartingWith(page + 1)
    })
}

pagesStartingWith(0)
    .takeWhile { numbers in
        return numbers[0] < 1000
    }
    .subscribeNext { n in
        print(n)
    }

XCPSetExecutionShouldContinueIndefinitely(true)
```

... this should print out 

```
[0, 1, 2, 3, 4]
[100, 101, 102, 103, 104]
[200, 201, 202, 203, 204]
[300, 301, 302, 303, 304]
[400, 401, 402, 403, 404]
[500, 501, 502, 503, 504]
[600, 601, 602, 603, 604]
[700, 701, 702, 703, 704]
[800, 801, 802, 803, 804]
[900, 901, 902, 903, 904]
```

I'm hoping you can adapt it to suit your needs.

----------
This is kind of a small addition, the code does look little funky, but don't freak out :)

That former version unfortunately won't be able to use tail recursion optimizations because that `deferred` operator will kill tail recursive optimizations.
If you want a version that uses our tail recursion optimizations, you can replace `pagesStartingWithPage` with the following implementation.

```
// this generates
// [generator(0), [generator(1), [generator(2), ..].concat()].concat()].concat()
func generate<T>(startIndex: Int, _ generator: Int -> Observable<T>) -> Observable<T> {
    let all = [0, 1].lazy.map { i in
        return i == 0 ? generator(startIndex) : generate(startIndex + 1, generator)
    }
    return all.concat()
}

generate(0, loadPageFromServer)
    .takeWhile { numbers in
        return numbers[0] < 1000
    }
    .subscribeNext { n in
        print(n)
    }
```

**Comment by Yoncise** [comment]
Hi @kzaher ,

Aha, I also used recursive way to accomplish this before, but your implementation is much more elegant than mine. I changed to loop way because I worried about stack overflow which I encountered in Android.  RxSwift will do tail recursive optimizations is what I don't know before. Is there any doc about this in RxSwift? 

Thank you

**Comment by kzaher** [comment]
Hi @Yoncise ,

That's actually a good suggestion regarding documenting that :) 

I would still like to add some tiny further optimizations to that tail recursion optimizations.

Maybe I'll have a chance to add them this weekend, and add further unit tests that test for that tail recursion.

Then we can document it for sure :)

**Comment by Yoncise** [comment]
Glad to hear this :)

**Comment by ludov04** [comment]
Hi @kzaher,
I want to do polling using RxSwift. Here is the behavior I want:
- An async task (typically a network request) is scheduled every `x` seconds.
- I don't want to fire new requests if the previous one has not returned or timed out.
- If a request take more than `x` seconds, the next one is fired immediately.

The implementation above that use tail recursion optimization does not respect the last point.
So I came up with that:
```
extension ObservableType where E == NSTimeInterval {
  func pollEvery(seconds: Double) -> Observable<Self.E> {
    return self.flatMap({ (e) -> Observable<NSTimeInterval> in
      return Observable.just(e).concat(self.delaySubscription(seconds - e, scheduler: SerialDispatchQueueScheduler.init(internalSerialQueueName: "timersQueue")).repeatEvery2(seconds))
    })
  }
}
```
The NSTimeInterval represents the time that the async tasks took to execute.
This works ok but crash after a while, I suspect stack overflow error due to the recursion if `flatMap`: Can you give me a hint on how to implement the behavior I want ?

**Comment by gregpardo** [comment]
It seems like this is a common task people want to accomplish. I had needed a poller that fired on intervals and also needed a manual trigger using a merged subject. Perhaps these sort of common network scenarios should be explained in the examples or an extension should be written with common network functionality. RxSwift+Polling or something

**Comment by kzaher** [comment]
Hi @ludov04 ,

I know this is not the exact same behavior you are asking, but looks really similar to me:

```
Observable<Int>.interval(x, scheduler: scheduler)
      .flatMapFirst { _ in
             return callServer()
      }
```

If you can ignore third point, this is something you can use right now for time pooling. It is simple and really readable IMHO.

If you want to satisfy all 3 points, it seems to me that the most  straightforward way is to use `generate` operator with timer overload (we haven't find a need to port it), and then concat. That would look something like:

```
Observable.generate(initialState: 0, condition: { _ in true }, timeSelector: { _ in x },  scheduler: scheduler) { $0 }
    .map { _ in pooling() }
    .concat()
```

I would probably just use 
```
Observable<Int>.interval(x, scheduler: scheduler)
      .flatMapFirst { _ in
             return callServer()
      }
```

for time pooling because if receiving a result took longer then x, then it would probably be a good idea to throttle the requests, and not send next one immediately since that will probably produce a lot worse results (take a look at TCP congestion strategies :). The same logic could be applied on application layer as well.

**Comment by ludov04** [comment]
Thank you for your response! It helped me find another approach to polling. I use something similar to your first proposition (with flatMapFirst) but also with exponential back-off in case of errors.

**Comment by kzaher** [comment]
Closing this again :)

**Comment by ballard** [comment]
@kzaher 
is there a some new way to implement serial loading of pages since 2015? :) I'm experimented with "repeatElement" and "interval", but the way with pagesStartingWith(page:) works a way better...
