### ISSUE TITLE
Functions with variadic parameters overload for array

### ISSUE THREAD

**Issue by psophis** [ReactiveX/RxSwift#335]
As of now swift doesn't have a "splat" operator therefor making it very hard to pass Array types to functions with variadic parameters.

Can all functions with variadic parameters also have an overload to accept an array?

[Example with `sequenceOf`](https://github.com/ReactiveX/RxSwift/blob/aeff907a8d187d001071d5e990686911e715c5bf/RxSwift/Observables/Observable%2BCreation.swift#L85)

**Comment by psophis** [comment]
After grepping through the whole project it seems that `sequenceOf` is the only one that used a variadic parameter.

**Comment by psophis** [comment]
See PR #336 for proposed changes.

Though my vote for the future is to not have variadic parametered anywhere and deprecated the ones listed in the future. There is more ambiguity when they are used and are really just some syntactic sugar that isn't need.

**Comment by psophis** [comment]
I'm realizing that the correct way to create an observable from an array of items is to use `.toObservable()`

With that figured out I have closed PR #336.

Is `sequenceOf` needed? Can it be deprecated in favor of `toObservable()`?

**Comment by kzaher** [comment]
Hi @psophis ,

It's like you've said. We have a really small number of variadic versions.

Having a way to create an observable sequence from limited number of elements is useful for me :)

E.g.
```
sequenceOf(xs1, xs2).merge()
```

IMHO is much more concise and readable then

```
[xs1, xs2].toObservable().merge()
```

The same is also valid for `startWith`.

Another reason why we have that `sequenceOf` is because we can later make better guesses how to optimize the code. 
Variadic versions means that the intended use for that API is for somebody to manually build a list of elements in code. That means that array will probably have only a few elements.
That property isn't necessarily valid for generic `Array` (possibly large but finite) or `SequenceType` (possibly infinite number of elements) version.

I think we always weigh is it worth it to create a new version of the operator, and if there is enough statistical evidence, we do it.

On the other side we try to balance this with trying to have minimal number of operators and having a really simple public API.

Ideally there should be only one obvious way of doing things, but in this case I believe having two versions `sequenceOf` and `toObservable` isn't too bad IMHO.

One could also argue that having `just` is unnecessary because `just` = `sequenceOf(oneElement)`, or we could have `just` take variadic number of arguments.

The reasons are again:
* expressing intent
* readability
* optimizations

Having said that, I definitely can't say that how we evaluate those arguments isn't subjective and that if somebody else has done this project he wouldn't assign different weights to those arguments.

¯\_(ツ)_/¯

**Comment by psophis** [comment]
That's understandable.

Is there a possibility of using the same terminology for both `sequenceOf` and `toObservable`? That's where I got confused.

As someone new to RxSwift and FRP in general there seems to be an abundance of ways to accomplish the same thing that read totally different from each other. It may not be is the best decision to change anything, but instead maybe include in the doc string what shortcut operators are shortcuts for. There are some that already do this. Heck, maybe just link directly to http://reactivex.io 's documentation as well. As the way that I find myself learning is using autocomplete to show me whats actually possible and going from there.

**Comment by kzaher** [comment]
Oh, 

so you are proposing something like this?

```
/**
    Projects each element of an observable sequence into a new form.
    
    [reactivex.io](http://reactivex.io/documentation/operators/map.html)

    - parameter selector: A transform function to apply to each source element.
    - returns: An observable sequence whose elements are the result of invoking the transform function on each element of source.
     
    */
    @warn_unused_result(message="http://git.io/rxs.uo")
    public func map<R>(selector: E throws -> R)
        -> Observable<R> {
        return self.asObservable().composeMap(selector)
    }
```

**Comment by psophis** [comment]
Yes, though we are now discussing topic that are not related to the original issue. I'll close this one and open new ones for topics previously discussed.
