### ISSUE TITLE
Just wondering is it a bug or I doing something wrong 

### ISSUE THREAD

**Issue by sergdort** [ReactiveX/RxSwift#353]
I have ```UITableViewCell``` with a button,  the cell has ```viewModel``` property and ```CompositeDisposable```. In ```prepareForReuse``` I dispose my composite disposable to prevent multiple bindings.  And in this case when cell appears for the first time all works fine, but when it comes from reuse  ```submitTrigger``` does not works

```swift
   let compositeDisposable = CompositeDisposable()

   weak var viewModel:MyViewModel? {
      didSet {

            ...
             let submitDisposable = self.submitButton
               .rx_tap
               .bindTo(viewModel.submitTrigger)
            
            compositeDisposable.addDisposable(submitDisposable)
         }
      }
   }

   override func prepareForReuse() {
      super.prepareForReuse()
      self.compositeDisposable.dispose()
   }

```
But with this setup all works fine 

```swift
   private var disposable:RxSwift.Disposable? = nil
   weak var viewModel:MyViewModel? {
      didSet {
            .....
            disposable = self.submitButton
               .rx_tap
               .bindTo(vm.submitTrigger)
      }
   }

   override func prepareForReuse() {
      super.prepareForReuse()
      self.disposable?.dispose()
   }
```

**Comment by thanegill** [comment]
Try this:

```swift
   var compositeDisposable: CompositeDisposable

   weak var viewModel:MyViewModel? {
      didSet {
            compositeDisposable = CompositeDisposable()

            ...
             let submitDisposable = self.submitButton
               .rx_tap
               .bindTo(viewModel.submitTrigger)

            compositeDisposable.addDisposable(submitDisposable)
         }
      }
   }

   override func prepareForReuse() {
      super.prepareForReuse()
      self.compositeDisposable = nil
   }
```

**Comment by kzaher** [comment]
Hi :),

just a tiny hint, instead of `CompositeDisposable`, I would suggest using `DisposeBag`, and then @thanegill 's code should work.

All disposables (CompositeDisposable, SerialDisposable, AnonymousDisposable ...) have the same behavior. 
* once they are disposed, adding another disposable with `addDisposable` will call `dispose` immediately (@sergdot that's why `self.compositeDisposable.dispose()` was causing that weird behavior ;)
* they don't call dispose automatically on deinit

All classes named `*Disposable` are meant to be used while implementing your own Rx operators.

`DisposeBag` is meant to return ARC like memory management to subscriptions, and it will dispose all subscriptions (Disposables) it contains on deinit.

Hope this clears things up :)

**Comment by sergdort** [comment]
Thanks, guys! :+1:
