### ISSUE TITLE
Feedback Request: Looking to add a load of OSX code

### ISSUE THREAD

**Issue by Rheeseyb** [ReactiveX/RxSwift#385]
I checked the CONTRIBUTING.md file, and this seemed to be the best place to request feedback...

We're looking to add a fair amount of code around various OSX (NS) components to the project, and wanted to gather some feedback on what we've done so far so that we don't end up writing a load of code that is never merged in to this project. 

We'd massively appreciate it if anyone could take a look at [this commit] (https://github.com/momentumworks/RxSwift/commit/064233c833e837a19024833d394dd70bf6f08784) where we've added a lot of boilerplate around the NSOutlineView (probably the worst component to pick, but it was one of the main ones we needed). We've tried to stick to the same pattern as used with UITableView, but there are some fundamental areas where the two components differ.

Cheers!

**Comment by kzaher** [comment]
Hi @Rheeseyb,

I think that current OSX support is not very rich compared to iOS, so we would like to improve it :(

I don't have much experience with `NSOutlineView`, so I think I would need to investigate it little bit more to say for sure. I have most experience on iOS platform by far :).

It seems to me that `NSOutlineView` is a subclass of `NSTableView`, so it would make sense to include table view integration also. Including `NSOutlineView` alone wouldn't allow us to retrofit `NSTableView` support without breaking public API.

I did some preliminary investigation some time ago while investigating how to wrap those nasty table and collection views. It did take me a while to figure out that what we have now is the most optimal way, and what we have now is probably version number 7th :)

Since it was this hard to wrap something I was so familiar with, I was little burned out and didn't have time or nerves for OSX :)

If you are asking me would we want to support some equivalent API for OSX that we do for iOS table views and collection views, the answer is yes, ofc.

If the question is would we accept PR from outside that has everything needed, the answer is also yes.

To include a bunch of code to our repository for maintenance it would need to satisfy the following criteria:
* it would need to have idiomatic names
* it would need to include `NSTableView` extensions because of mentioned reasons
* it would need to have unit tests
* build server would need to be happy
* we would need to agree upon how would that interface look like (probably a lot closer contact over time with some iterations because it's not realistic to get this right with first attempt, and not just making that final PR with 4k lines of code :) 
* it would need to satisfy common use cases (>90%) without significant increase in complexity (hoping iOS solution architecture works well on OSX also)
* it would need to be documented
* we would need to redo OSX app into something like we have for iOS, list of individual samples, and add at least two of them, one for `NSOutlineView`, and one for `NSTableView`.

The reason why we want to have sample app together with API is because:
* maintenance
* it demonstrates how to use the API
* it is a sanity check
* you can easily investigate issues on simple examples
* there is usually no way to confirm that API isn't broken unless you use it in real app, so we can automate and redo those checks before we ship new versions of the library, like we currently do for iOS while keeping the project velocity (unit tests can test everything, although with new UI tests, that is changing)
* everything needs to be self contained.

There is a caveat that there is something on OSX that I've overlooked and that changes things drastically. In case something like that happens, there is always a chance that we won't pull this to OSX support inside of this library because it would either be too complicated or too messy ...

For example, I haven't tested how editing behaves on OSX and does it have the same properties like on iOS (`- addTableColumn:`, `- removeTableColumn:`, `- moveColumn:toColumn:`. ¯\\\_(ツ)\_/¯ Have no idea.

`- tableView:toolTipForCell:rect:tableColumn:row:mouseLocation:` ¯\\\_(ツ)\_/¯

I guess in the worst case most of these delegate/data source messages could be just forwarded using normal mechanism to some delegate that implements them but there could be unknown risks. ¯\\\_(ツ)\_/¯

Another caveat is that you'll probably want to use this as soon as possible (since you are developing a product with deadlines), and that we won't be able to pull those changes unless they are ready to be shared with broader community into main repository. 

I guess one possible solution could be for you to use your explicit fork until fate of those extensions is sealed and in that way you could use them with less risk, but propagating changes to fork between releases usually requires manual re-including of files in project because of git project conflicts. 

I'm definitely curious can we extract a new successful implementation for OSX that is battle tested and that we can share with this community.

Ofc, the question is did you have something like that in mind or a simple PR :). 

No matter what, I always need to make sure all code that enters this repository is maintainable, tested, works, and doesn't slow down evolution significantly because it's maintenance is automated and issues easily debuggable.

I can ofc help you to avoid pitfalls I've ran into while developing iOS extensions, provide more context why things are designed the way they are, etc ... but it's probably not realistic for this to become first on the list of priorities.

I guess we haven't done anything similar like this in past because of all of these complications and huge velocity we were trying to accomplish, but I don't see any reason why it wouldn't be possible.

¯\\\_(ツ)\_/¯

**Comment by kzaher** [comment]
I guess this wasn't an issue, and it is stale, so closing this one.

**Comment by DivineDominion** [comment]
Dang, sad to see nothing happened :) NSTableView sure is a nasty bit. I am very new to RxSwift, and I wonder how much of NSTableView configuration we need to support to make this work for most cases.

There are a lot of weird intricacies, like some events from table cells will only bubble up to the table view's delegate, even though the delegate itself has nothing to do with these callbacks. That, in turn, either means an Rx component has to be the delegate and "catch all" forwarder of events, or we ditch 100% compatibility and aim for "common" interactions and wrapping the data source.
