### ISSUE TITLE
Carthage Support?

### ISSUE THREAD

**Issue by m00sey** [ReactiveX/RxSwift#40]
Hey,

I see a reference to Carthage in the .gitignore, but simply adding to a Cart file produces the error

    *** Fetching RxSwift
    *** Checking out RxSwift at "1.6"
    *** xcodebuild output can be found in /var/folders/1w/kkmgrb0n1p7gm08j06x8wjtw0000gn/T/carthage-     xcodebuild.kBvFvj.log
    Project "Preprocessor.xcodeproj" has no shared schemes

Is the project expected to support Carthage?
More than happy to take a swing at it if not.

**Comment by kzaher** [comment]
Hi,

I've tried to support Carthage a couple of months ago and failed.

The problem is that Carthage supported only one scheme per repository, and it has some weird automagic logic that detects that scheme.

I'm not a Carthage expert, so I could have been doing something wrong.

If you can help us support Carthage in a non destructive way, you will forever be my hero and have my perpetual, irrevocable, universewide, royalty-free, and non-exclusive gratitude :)

**Comment by m00sey** [comment]
So I cloned RxSwift and was able to run the builds/examples fine.
I was able to build the frameworks independently using 

    xcodebuild -scheme RxSwift-iOS -workspace Rx.xcworkspace build
    xcodebuild -scheme RxCocoa-iOS -workspace Rx.xcworkspace build


What is the preprocessor.scheme, and what is it's relasionship to the sub-projects in the workspace?  Since that's the default scheme, and has no shared schemes, carthage for me, stop right there.

**Comment by kzaher** [comment]
For optimal performance we generate code for operators that have n-arity (for now those are `zip` and `combineLatest`).

You can take a look at project for 
* CombineLatest+arity.tt swift template -> generates CombineLatest+arity.swift
* Zip+arity.tt swift template -> generates Zip-arity.swift

We also automatically generate part of unit tests :)
* Observable+MultipleTest+CombineLatest.tt
* Observable+MultipleTest+Zip.tt

Preprocessor needs to be run only when you change those .tt metafiles. It's not a real dependency for building RxSwift/Cocoa projects because generated .swift files are commited.

**Comment by aschuch** [comment]
@kzaher would it be possible to add the [compiled .framework to the Github release page](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file)? 
This way, Carthage would download the pre-built framework instead of building from source.

**Comment by m00sey** [comment]
That does appear to be the simplest way to support Carthage.

**Comment by kzaher** [comment]
Hi guys,

even though Carthage is really popular, I think we would all agree it's still experimental software.

I've reported this problem to Carthage collaborators more then a month ago with proposed solution
https://github.com/Carthage/Carthage/issues/395

We all agree what needs to be done and I'm waiting for this issue to be resolved on their end.

The main problem is that they don't support repositories with multiple shared schemes, or any way of selecting build targets.

I'm not sure would attaching binaries solve anything because:

* there are multiple versions of Xcode out there, and not all have binary compatible formats
* I would need to attach multiple zip files (not sure if Carthage would know how to handle that since there are RxSwift and RxCocoa projects)

The fix / options until then are pretty simple:

* clone the repository and hit build (there are no external dependencies, it's just one `git clone` +  open Rx.xcworkspace + click build)
* use cocoa pods

Hope they resolve issue on their end soon. Maybe some community pressure would be helpful ;)

Kruno

**Comment by kzaher** [comment]
I've created a temporary workaround for Carthage :(

```
git "git@github.com:kzaher/RxSwift.git" "latest-carthage/rxswift"
git "https://github.com/kzaher/RxSwift.git" "latest-carthage/rxcocoa"
```

It's ugly, but it should work.

**Comment by kzaher** [comment]
It looks like you can't have Carthage fetching both in parallel :( so you'll need to only uncomment one of them at a time.

Comment one, `carhage update`, then comment other `carthage update`.

**Comment by tp** [comment]
Thanks, this works for me :)

Such a waste that one needs this time consuming workarounds for the time being.

**Comment by zenkimoto** [comment]
Thanks @kzaher 

Anyone having problems with access denied messages should create your SSH key.  See this link:
https://help.github.com/articles/generating-ssh-keys/

**Comment by kzaher** [comment]
:+1:

**Comment by bontoJR** [comment]
Guy, what's the status on this issue? 
I personally don't use Carthage, so I have no idea how things are going...

**Comment by kzaher** [comment]
I've made updates to rxswift-2.0 branch.

After merging `RxSwift.xcodeproj`, `RxCocoa.xcodeproj` and `RxBlocking.xcodeproj` into `Rx.xcodeproj` it looks like we'll have more pleasant Carthage integration for RxSwift 2.0.

**Comment by lfaoro** [comment]
9c893e7 closes this
