### ISSUE TITLE
using rx_itemsWithCellIdentifier with observable that emits errors

### ISSUE THREAD

**Issue by gferreri** [ReactiveX/RxSwift#405]
I have a BehaviorSubject<[Item]> that's bound to a tableView like this:

```
viewModel.availableItems.bindTo(tableView.rx_itemsWithCellIdentifier("Cell")) {
 (row, element, cell) in
     let listCell = cell as! ItemListTableCell
     listCell.titleLabel.text = element.name
 }.addDisposableTo(disposeBag)
```

This works great when viewModel.availableItems emits an [Item] but crashes when it emits an Error with this message:

>fatal error: DataSource not set: file /Users/...Pods/RxCocoa/RxCocoa/Common/RxCocoa.swift, line 130

Is this expected behavior? Am I thinking about this wrong by allowing viewModel.availableItems to emit an error? Thanks!

**Comment by kzaher** [comment]
Hi @gferreri ,

you are correct, binding error to UI is not supported because that is undefined behavior :)

You should get a previous warning/assert printed to stdout saying something like `Binding error to UI: ....`

You need to manually define how to handle errors. You also need to bind those values from main thread. 

I suggest using one of `catch*` operators or `Driver` unit if you want to use compiler to prove those properties before binding to UI.

**Comment by kzaher** [comment]
This one doesn't look like a problem with library, and is stale.
