### ISSUE TITLE
Redundant 'unused' warnings

### ISSUE THREAD

**Issue by larcus94** [ReactiveX/RxSwift#453]
I've discussed this with @bontoJR just a minute ago.

When I subscribe to an observable and make sure that it will be disposed using the 'takeUntil' operator, the 'subscribe' method still yields a warning.

So I guess there are two solutions:
- Make sure that the warning isn't yielded in this situation
- Add more predefined DisposeBags, for example 'rx_deallocatingBag' or alike

What do you think?

**Comment by kzaher** [comment]
Hi @larcus94 ,

we try to give a fair warning that it needs to be decided what to do with disposable.

If you are using `takeUntil` and you are ok with it managing the subscription, you can just do:
```
_ = xs
    .map { ...
    .takeUntil(something)
    .subscribe { ....
```
... that will solve the warning. That's how you communicate, yeah, it's ok to ignore this, it will complete because of `something`, and everything will be disposed.

If you want to use automatic dealloc bag, you can use https://github.com/RxSwiftCommunity/NSObject-Rx

**Comment by larcus94** [comment]
Oh nice, I think I'll use the NSObject-Rx extensions then, thanks :)
