### ISSUE TITLE
New ObserverType That Can't Receive an Error Event

### ISSUE THREAD

**Issue by thanegill** [ReactiveX/RxSwift#458]
Would abstract way this mess that is everywhere in RxCocoa: 

```swift
return AnyObserver { [weak self] event in
    switch event {
    case .Next(let value):
        // Do something with value
    case .Error(let error):
        bindingErrorToInterface(error)
        break
    case .Completed:
        break
    }
}
```

Could also fix to need to make `bindingErrorToInterface` public (See #274)

Would force use of `Driver` with RxCocoa

**Comment by kzaher** [comment]
I think that we'll just create some kind of `BindingObserver` abstraction. Still thinking about few approaches to do that. That would move that internal boilerplate into one place, and enable public usage of `BindingObserver`.

That's why we didn't make `bindingErrorToInterface`, we need to properly abstract it first.

The decision to not force users to use `Driver` with `RxCocoa` was not accident :). That decisions has it pros and cons.

+:
I wanted to allow people to create their own units and use the same bindings. Didn't want to monopolize API to use just our one unit, Driver. I've even considered separating it into it's own project, but decided it would be little too much :)
It is ofc best practice to use it or some similar compiler assisted proving engine, but people can build what ever unit they want, use it in any way they want and they should be able to use our bindings.

-:
The downside of that decision is that it's possible to bind something that isn't on main thread or errors out and we need to have a runtime check for that => use Driver for those sequences, or if users want to use some other proving engine, that's fine by us :+1:

I think that if Swift 3.0 adds typed throws we'll probably add typed error to observable sequences in RxSwift 3.0, so that would remove one runtime check, but if people are using units properly, that shouldn't bring much to the table.

I'm not sure does this answer your question :)

**Comment by thanegill** [comment]
It maybe that I'm not correct in saying that it would force Driver on RxCocoa users. Currently during release builds there is a fatal error is thrown when RxCocoa Observers receive an error. What I'm suggesting is that we abstract that fatal error to it's own ObserverType that it's used throughout RxCocoa but could also be used for creating Rx extensions that we don't want included in RxCocoa, removing the need to make `bindingErrorToInterface` public. 

See here: https://github.com/thanegill/RxSwift/commit/d98c7883175a56f8deabe26e98eadd13f42b93e0
(This might be exactly what you're talking about with a `BindingObserver` that's just named incorrectly)

**Comment by thanegill** [comment]
I believe that I have when the fatal error is thrown backwards but my point still stands.

**Comment by kzaher** [comment]
Hey,

yeah, I think we would want to do something similar for 2.* version. Something like

```
public var rx_alpha: AnyObserver<CGFloat> {
        return ControlBinder(self) { (self, value) in
            self.alphaValue = value
        }.asObserver()
    }
```

... and for 3.* I think we would probably want:

```
public var rx_alpha: ControlBinder<CGFloat> {
        return ControlBinder(self) { (self, value) in
            self.alphaValue = value
        }
    }
```

I wouldn't want to change `AnyObserver` to `ControlBinder` in 2.* since that would be a lot of breaking changes. But yeah ...

**Comment by kzaher** [comment]
We've added `UIBindingObserver` in the last release that should correspond to this issue.

Assuming we can close this one now.

**Comment by thanegill** [comment]
@kzaher Why specify that the Observer is UI binding? Is there no cases in RxCocoa where there is an Observer there doesn't bind to a UI element?

**Comment by sergdort** [comment]
Hi, guys, do you think usage of `UI` prefix is a good style ?

**Comment by kzaher** [comment]
Hi guys, 

Let me try to explain the reasoning.

I believe that we would want to give semantics to observers. 
That's why we've named it `UIBindingObserver`. If you see it somewhere, you know that this thing can only accept values on main thread and you shouldn't try to bind something that fails.

I really wanted to make the name specialized. I don't think we currently bind things to anything other then user interface elements. That includes (constraints, `UIBarButtonItem`s and UIView subclasses... ). All of these things are ui elements.

If we were to bind to something else, maybe we would need to bind on some specific background scheduler, or not even have a scheduler constraint, we we'll create another observer if needed.

UI is not a namespace prefix, but abbreviation of `UserInterfaceElementObserver` since I really felt that full name was too verbose, although technically correct. 
The practical difference between those two interpretations is that we don't plan to prefix all classes with UI, and we will use `UIBindingObserver` for Cocoa also because that's not a namespace prefix. I think that Swift doesn't have those conventions since Swift has modules.

I'm sure that with time people will let us know their suggestions and if we decide that there is some obvious better alternative for 3.0, we can change the name then ¯\\\_(ツ)\_/¯ .

**Comment by thanegill** [comment]
I agree that it should be named something where it implies main thread and no errors, but isn't that exactly what Driver already is? Why have another naming for the observers that Driver's bind to? I'd like it to be consistent and be named some conjugation of Drive just as Observer is to Observable.

**Comment by kzaher** [comment]
Observable sequence is meant to have no semantics what so ever.

`Driver` has semantics that are more general then just receiving elements on main thread and not erroring out (sharing of computation results in a certain way), where `UIElementObserver` is an observer that requires that anything that binds to it is receiving elements on main thread and not erroring out.

`Driver` can power `UIElementObserver` for sure, but also any other type of observer with some subset of those properties (maybe only receiving elements on main thread, or only no erroring out).

A generic observable sequence can power `UIElementObserver` in case it has those properties proven in some other way.

I think it's better to have naming semantics closely aligned with the reason that abstraction exist, then to create over general abstractions that might need more then one reason to change and thus have to make compromises and least common denominator.

For example, if we were to name it `Drivable` or something more generic like that and use it in place of `UIElementObserver` and in place of some other concepts, we might have multiple reasons to change behavior policy in case those runtime constraints aren't satisfied separately for those those semantically different cases, and then we couldn't do that. (for example logging)

`UIElementObserver` expresses semantics and it's implementation is a just a policy how to behave when certain runtime requirements aren't satisfied, so there isn't any danger of duplication of logic.
