### ISSUE TITLE
Control Property skips events

### ISSUE THREAD

**Issue by JARinteractive** [ReactiveX/RxSwift#471]
the distinctUntilChanged() operator used in ControlProperty can result in missing value change events from a control. The simplest example of this is a UISwitch's rx_value. 

1. When subscribing rx_value sends `.Next(false)`
2. Send `.Next(true)` intto rx_value. rx_value correctly does not send an event.
3. User flips switch. rx_value does NOT send `.Next(false)` even though the value of the control changed.

**Comment by sergdort** [comment]
Hm, that is weird..
I've just made a simple example

```swift
        switchControl.rx_value.distinctUntilChanged()
            .subscribeNext { (value) -> Void in
                print(value)
            }
            .addDisposableTo(disposeBag)

```

and for me it works

**Comment by thanegill** [comment]
@JARinteractive Can you post code that shows this behavior?

**Comment by JARinteractive** [comment]
Here is a test for the expected behavior I described.

```
class TestControl: UISwitch {
	
	// best approximation of UIControl behavior without running UI tests
	override func sendActionsForControlEvents(controlEvents: UIControlEvents) {
		self.allTargets().forEach { target in
			self.actionsForTarget(target, forControlEvent: controlEvents)?.forEach { action in
				target.performSelector(NSSelectorFromString(action), withObject: self)
			}
		}
	}
}

class ControlPropertyTest: XCTest {
	func testControlPropertyEventsOnValueChange() {
		let control = TestControl()
		control.on = true
		
		var events: [Bool] = []
		_ = control.rx_value.subscribeNext {
			events.append($0)
		}
		
		control.on = false
		control.sendActionsForControlEvents([.ValueChanged])
		XCTAssertEqual(events, [true, false])
		
		control.rx_value.onNext(true)
		
		control.on = false
		control.sendActionsForControlEvents([.ValueChanged])
		XCTAssertEqual(events, [true, false, false])
	}
}
```

**Comment by kzaher** [comment]
Hi @JARinteractive ,

I don't think I would expect this behavior. 

`rx_value` represents a value over time, and not a set of all events otherwise you wouldn't get that first `true` since that's not a change event but an initial value.

Can you explain why do you need this and why do you expect to have `false`, `false` since the value was already `false`, and you can't change a switch in the UI to go from `false` to `false` without going through `true`.

**Comment by JARinteractive** [comment]
@kzaher Given your expected behavior of ControlProperty, shouldn't there be an event when the control is set to true programmatically? The last assert would then be `XCTAssertEqual(events, [true, false, true, false])`. That doesn't happen with the current implementation. 

I'd rather deal with user events, but I understand now that ControlProperty/RxCocoa is not meant to work in those terms.

**Comment by sergdort** [comment]
I think the problem here is when you manually send next
`switchControl.rx_value.on(.Next(false))`

The value  doesn't send to subscribers

And in this case if you for example have functionality like this

```swift
let variable = Variable(false)

variable.asObservable()
            .bindTo(switchControl.rx_value)
            .addDisposableTo(disposeBag)

//and other subscribers to the switchControl

        switchControl.rx_value
            .distinctUntilChanged()
            .subscribeNext { (value) -> Void in
                // subscribers will not receive changes of variable but,
               // on UI switch control has been switched

            }
            .addDisposableTo(disposeBag)

//some where else

variable.value = true

```

From what I see in the code this is because there are (if it normal terminology) two observers which sends values :

- The first one is from ` Observable.create` which is the source of `ControlProperty`
- The second one is the `valueSink` which changes the switch's control value of `on` within the `setter`
 ( this changes will never be sent to subscribers of `rx_value`)

The fixes: 

I'm not sure if its ok :)

But to make this work I've sightly changed implementation of `rx_value` to this

```swift
    public var rx_value: ControlProperty<Bool> {
        return rx_value(getter: { [weak self] in
            self?.on ?? false
        }, setter: { [weak self] value in
            self?.on = value
            self?.sendActionsForControlEvents(.ValueChanged) //this will send values to subscribers
//and because there is `distinctUntilChanged()` this will not lead to the recursive call
        })
    }
```swift

**Comment by sergdort** [comment]
But in this case I guess this will not work for other controls, so I guess if its ok we should move this inside of `rx_value: , setter ` method

**Comment by kzaher** [comment]
Hi,

correct me if I'm wrong, but it seems the real question is why don't we send changes that are set programatically. It is not an accident it behaves that way :)

These are the reasons:
* having that "feature" would mean that causing stack overflows would be extremely easy since any programatic change would cause even propagation (including programmatic setting of initial value).
* you really don't need that "feature" anyway since your system already knows (should know) all of the programatic changes
* that "feature" would be necessary only if the switch value is the place of truth and not just a reflection of value stored in some kind of model
* the current behavior is consistent with platform behavior (when setting `on` programmatically you won't get value changed event probably because of the same reasons :)

In case only `.ValueChanged` are needed, you can just use `switch.rx_controlEvent(.ValueChanged).map { _ in switch.on }`, but this won't send those events when `switch.on = true` is set because of the mentioned reasons.

I've asked the same questions myself when I've been working on these interfaces. I've tried to understand why Apple has made the choices they have, and I think that the current behavior is what you would ideally want

... unless there are some obvious reasons that I might have missed :)

**Comment by JARinteractive** [comment]
The current behavior seems inconsistent to me. I see two consistent options:

Option 1: Act like Variable and send all distinct value changes (programmatic or not)

Option 2: Send events every time .ValueChanged (or similar) event is fired from the control. Do not ignore duplicate values. Do not send initial value (because event was not fired).

I'd prefer to see option #2, which I think matches with the reasons you listed above.

**Comment by kzaher** [comment]
Hi @JARinteractive ,

I think this is consistent as much as possible with `Variable` up to a point where it's not possible to be more consistent without breaking other consistencies. 

There isn't just one obvious inconsistency that we can fix in isolation and IMHO I don't see any other more optimal solution.

If you are relying on receiving those duplicate events, maybe there is a more optimal way to think about this.
That is a more of a philosophical question then a practical one, because if you change some value to the same value, have you changed it? Don't think you have.

I don't think anything is set in stone, but until we figure out some really compelling reason why we would want to change this, we can leave it like this for now.

I think we can close this one for now.
