### ISSUE TITLE
Add toArray to Driver

### ISSUE THREAD

**Issue by thanegill** [ReactiveX/RxSwift#496]
There must be a way to have some common operators between Driver and Observable where code doesn't need to be copy pasted, maybe extend ObservableConvertibleType instead of ObserverType for the common operators?

**Comment by thanegill** [comment]
I'm realizing that the method definitions don't match. As operators on Driver don't throw errors.

**Comment by kzaher** [comment]
Hey @thanegill ,

I think that `Driver` is unit intended to model never ending streams that drive your app. Just curios, why do you need `toArray`?

I've been thinking a long time about a relation between observable sequences, and observable sequences that carry semantics (units).

My conclusion was that you don't want to apply observable operator automatically to some unit because you need to only apply those operators that preserve unit properties, and make sense in the context of unit semantics.

For example, generic observable sequence has map defined this way:
```
public func map<R>(selector: E throws -> R)
```

... but `Driver` has only 

```
public func map<R>(selector: E  -> R)
```

... because transformation shouldn't fail for `Driver` (that's one of the properties in his definition).

When one is defining operator on unit by using generic observable unit operator, that's not a duplication of logic (since you are only calling operator, not copy pasting logic), and that is a statement that you've somehow proved that this operator is not breaking particular unit (`Driver` in this case) contract.

**Comment by thanegill** [comment]
I understand that there are some differences in operators between Driver and Observable. I I was using `toArray()` for some crude unit testing. Ended up covering to observable to use `toArray()`.

Maybe I'm just using Driver as an Observable that doesn't error instead of its intended use.
