### ISSUE TITLE
Need example for insert/delete row in UITableView

### ISSUE THREAD

**Issue by 1bannamgiauten** [ReactiveX/RxSwift#594]
Sorry, my english is bad :(

Hi all,

I used rx_itemsWithCellIdentifier but this same reloadData() in UITableView, right?

**var initValue = [1, 2, 3]
let subject = BehaviorSubject<[Int]>(value: initValue)
subject.bindTo(tableView.rx_itemsWithCellIdentifier(...).addDisposableTo(disposeBag)**

I need add some new value to initValue:

**initValue.append(4)
initValue.append(5)
initValue.append(6)**

Then I want UITableView insertRowsAtIndexPaths, not reloadData. But I don’t know how to do this with RxSwift. I have only choose:

**subject.onNext(initValue)**

But with code above, UITableView will same reloadData, not same insertRowsAtIndexPaths.

How I can insertRowsAtIndexPaths/deleteRowsAtIndexPaths in RxSwift?

Thanks!

**Comment by retsohuang** [comment]
Hi @1bannamgiauten ,
If you want to animated updates instead of reloading entire table view, you should use `rx_itemsAnimatedWithDataSource` and bind with `RxTableViewSectionedAnimatedDataSource`,  you can check sample code here [RxSwiftCommunity/RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources).

**Comment by kzaher** [comment]
Assuming this is resolved :)
