### ISSUE TITLE
Crash when app goes into background.

### ISSUE THREAD

**Issue by alexiosdev** [ReactiveX/RxSwift#698]
I have been using RxSwift in several apps and it is really great.
I sometimes get this crash when debugging app.

![rxswift](https://cloud.githubusercontent.com/assets/10130578/15446456/ffd68aee-1f53-11e6-8fbf-2c21fd2d249b.jpg)

When app goes into background, I replace root view controller of the app with white screen view controller and dismiss all presented view controllers of original root view controller. 

I got crash above on a certain View Controller when it is about to be released due to change of root view controller.
I am using RxSwift in many places, but it is so curious why this happens.

I think this is not bug in this RxSwift & RxCocoa, but this happens in RxCocoa's `_RxDelegateProxy.m`.

I hope anybody can explain why this happens.

Thanks.

**Comment by kzaher** [comment]
Hi @alexiosdev ,

This happens because you've deallocated the user interface but you haven't disposed (unsubscribed) to observable sequences. That's why DelegateProxies still have references to old view elements.

Maybe you just have memory leaks, and that's why you dispose bags haven't been dereferenced and dispose the subscriptions.

**Comment by alexiosdev** [comment]
Hi @kzaher , Thank you for replying.
I checked my code and removed all rx - related codes and simply displayed empty view controllers, but same thing happened.

I am sure this is not Rx-Swift issue and memory leak comes from my source code, 3rd party library I use or in worst case from Apple.

So I am closing issue :)
Thank you again.
