### ISSUE TITLE
Variable -> asObservable().distinctUntilChanged() broken in 2.5

### ISSUE THREAD

**Issue by rshev** [ReactiveX/RxSwift#708]
Have the following code in my app:
```swift
    private var _isTouchIdAvailable = Variable(false)
    var isTouchIdAvailable$: Observable<Bool> {
        return _isTouchIdAvailable.asObservable().distinctUntilChanged()
    }
```
After upgrade to 2.5 (you've tinkered with `distinctUntilChanged()` there as of changelog), I can have a sequence of consecutive `false`s when subscribed. Haven't happened on 2.4.

**Comment by kzaher** [comment]
Hi @rshev ,

We needed to change that behavior somewhat because there were problems with using `distinctUntilChanged` inside those extension. 

I'm sorry that it broke your code, we are trying to be careful when performing changes on existing extensions. 

Since user input is always unpredictable, I didn't think this was a breaking change since it shouldn't matter how many updates one receives from the user interface, and on the other hand, we really needed to do this since it was causing issues because of interaction with validation.

I'm not sure how to resolve your issue. Could you maybe explain what is the question/suggestion?

**Comment by rshev** [comment]
Hi @kzaher ,

sorry, my example wasn't the case. Hunted down the bug, it was related to changed `rx_text` behavior where I've been receiving duplicate values. Thanks.
