### ISSUE TITLE
Variable OOO bug?

### ISSUE THREAD

**Issue by sprynmr** [ReactiveX/RxSwift#713]
I believe what I'm seeing is a bug. If I have a `Variable` with multiple subscribers, and one of those updates the variable value as part of it's side effect, then other subscribers get the values out of order. If I wrap a dispatch_async around the setting of the `Variable` value, then it works properly.

I would think the `Variable` should ensure that it's subscribers get the values in the right order, but correct me if I'm wrong.

Test case attached. 
[rxswift-bug.zip](https://github.com/ReactiveX/RxSwift/files/287236/rxswift-bug.zip)

**Comment by kzaher** [comment]
Hi @sprynmr ,

this is not a bug :) If you are sending element to itself when processing elements, the result is basically undefined.

You've added cleverly `filter { $0 != nil }` to prevent stack overflow, but this is still undefined behavior scenario as far Rx is concerned :)

**Comment by sprynmr** [comment]
Huh. Interesting. I would sort of think that the observable would track that, and ensure proper order.

So I have a valid scenario here where after using the value set into `coupon`, it should be cleared. Which I guess can potentially happen in the same runloop. Is my dispatch_async solution sort of the best I'm going to do? Perhaps a buffer with 0 instead. Closing issue.

**Comment by kzaher** [comment]
Rx is about unidirectional sequences :) Loops can be done if needed inside some operator ;), and you can use AsyncLocks for scenarios like this, but we haven't exposed `AsyncLock` code. Not sure would that be a good idea.

But you can check out AsyncLock code to see how that is being done in case you are interested. It's pretty simple, but because we've tried to make it performant, we've complicated it a bit with `InvocableType` so lambdas don't allocate additional objects on heap, but you can replace `InvocableType` with `() -> ()`, and it will work the same.
