### ISSUE TITLE
Expand CONTRIBUTING.md with more information

### ISSUE THREAD

**Issue by solidcell** [ReactiveX/RxSwift#718]
[`CONTRIBUTING.md`](https://github.com/ReactiveX/RxSwift/blob/master/CONTRIBUTING.md) is pretty lacking at the moment. This can lead to misguided work, ex. #680. I can think of at least a couple other helpful bits of information, such as: describing requirements for PR acceptance (`pre-release-tests.sh` passes, code is tested, etc.) and suggesting high-priority work.

Any thoughts? I think formatting it will depend on what gets included.

**Comment by solidcell** [comment]
Maybe listing the remaining (if any) core operators that could be implemented.

**Comment by solidcell** [comment]
A lot of this is stuff that comes to mind as points of confusion for me (as someone new to the repo).

**Comment by kzaher** [comment]
Hi @solidcell ,


I'll try to add some explanations.
Can you maybe explain which things were confusing for you?

**Comment by solidcell** [comment]
Yea definitely.

1. Being explicit about what is required of a PR:
  1. Unit tested (maybe to what extent, if you have a goal in mind as to what's enough or too much).
  2. Documented (where, and again, what's a good balance)
2. Goals / Mission
  1. Limiting RxCocoa to essentials and as-needed basis (this relates to #680)
  2. Limiting [Rx operators](http://reactivex.io/documentation/operators.html) (you've mentioned intentionally omitting operators for much the same reasons as for RxCocoa: maintenance, build time, etc.)
 3. Besides one-off operators and bugs in Issues, what's the direction of the project?
    1. Where do you envision the project going? (If it's not already there)
    2. What are top priorities? (Some refactor to get us to v3)
    3. What are some things that could use work, but aren't suited for a never-ending Issue? (Would you want to add all missing delegate proxies? If not, maybe there's something else?)

**Comment by kzaher** [comment]
Hi @solidcell ,

I've added instructions how to run unit tests to `CONTRIBUTING.md`, you are correct, that is a useful information.

I don't think adding Goals/Mission to CONTRIBUTING.md would be useful since those things change.

Another reason is that it's empirically proven that nobody who makes PRs actually follows instructions in CONTRIBUTING.md :)

I would just keep it simple and say, the main goal right now is the Swift 3.0 transition and porting to Linux. 

We will also add other small improvements on a case by case basis. I just use it, and try to figure out what makes sense, what works and what's missing.

I think we'll be mostly focusing on improving and polishing existing features, then adding bunch of new stuff. I'm pretty sure a lot of people don't know how to use what cool things we have right now, so I wouldn't want to make it even more confusing by adding more stuff in.

> What are some things that could use work, but aren't suited for a never-ending Issue? 

Nothing really comes to my mind right now.

Hope this answer gave some useful information.

**Comment by solidcell** [comment]
Cool, thanks for the info, that all makes sense.
