### ISSUE TITLE
ActivityIndicator part of RxCocoa

### ISSUE THREAD

**Issue by jonlambert** [ReactiveX/RxSwift#731]
Hi,

Just wondering if there were any plans to make the `ActivityIndicator` example part of `RxCocoa`? It's very useful, and it would be great to have it included without having to pull it in separately.

**Comment by kzaher** [comment]
Hi @jonlambert ,

I was thinking about where to put ActivityIndicator for quite some time. There are some pros and cons to putting it to RxCocoa:

Pro:
* visibility
* ease of importing

Con:
* it's high level abstraction, and not an interface wrapper
* it would confuse people about what is the purpose of RxCocoa project, so we would probably get a lot of PRs with other conveniences, that we would probably need to turn down
* although this isn't technically a breaking change, and it's ok with respect to semantic versioning, it will break people's code because of naming collision (this is a small nuisance, but just putting it out there)

Ideally I would like to wrap it somewhere else, but can't say that the idea of putting it inside RxCocoa doesn't sound tempting to me.

**Comment by devxoul** [comment]
@kzaher, How about separating from RxSwift and RxCocoa? Such as `RxActivityIndicator` or something else.

**Comment by jonlambert** [comment]
@kzaher Yeah that makes complete sense. If it wasn't dependant on `RxCocoa`, bundling it into an alternative `RxUtilities`/`RxTools`-type wrapper where it could live with some other high-level abstractions, tools etc. would be great.

**Comment by kzaher** [comment]
#771

**Comment by solidcell** [comment]
If anyone is coming here looking for a way to use `ActivityIndicator` in their own projects, it's now in a separate framework located here: https://github.com/RxSwiftCommunity/RxSwiftUtilities
