### ISSUE TITLE
Driver made from Variable crash because executing on background thread

### ISSUE THREAD

**Issue by rshev** [ReactiveX/RxSwift#743]
Hi. How that can happen that this piece of code:
```swift
    private let _isOnboarded = Variable(false)
    var isOnboarded$: Driver<Bool> {
        return _isOnboarded.asDriver().distinctUntilChanged()
    }

    private init() {
        _isOnboarded.value = UserDefaults.sharedInstance.isVpnBoarded    // just a boolean var there
        isOnboarded$.skip(1).driveNext {
            UserDefaults.sharedInstance.isVpnBoarded = $0
        }.addDisposableTo(disposeBag)
```

crashes with the message:
```
fatal error: Executing on backgound thread. Please use `MainScheduler.instance.schedule` to schedule work on main thread.
```

if its clearly stated in the documentation that `Driver` ensures running on the main thread?

**Comment by kzaher** [comment]
Hi @rshev ,

All of these things are correct. `Driver` will ensure that elements and other events are received on main thread, but calling `drive*` methods is only allowed from `MainThread`, otherwise it's considered programming bug.

It is true that we need to document this requirement better.

The reason why that is the case is because `Driver` uses `shareReplay` internally, and in some cases can immediately return element on the scheduler/thread that is calling `drive*` method.

There were possible solutions for that cases also, but they have worse behavior characteristics, so we've decided to take the simplest solution since it made most sense.

**Comment by rshev** [comment]
Completely agree with @acecilia that `Driver` is almost pointless because it doesn't do `observeOn(MainScheduler.instance` automatically.

**Comment by kzaher** [comment]
Hi @rshev ,

There is a chance that you've maybe misunderstood my previous response..

I've tried to provide more detailed explanations of how `Driver` works, and why it has that requirement to call `drive` method from main thread to make sure all elements are received on main scheduler in #747.

I think that requirement is pretty reasonable, and you are ofc entitled to your opinions, but `Driver` is extremely useful for me.

**Comment by rshev** [comment]
Didn't mean to offend you, sorry.
On the @acecilia issue you've said that it's replaying the first element on the caller's thread, why does it still crash in my case if I have `skip(1)` there?

**Comment by kzaher** [comment]
Hi @rshev ,

could you maybe provide a self contained example that reproduces this issue? It's little hard to say for sure what could be causing this, and where is that assert failing.

The only one that comes to my mind is in `drive` method, so if you are calling ` private init()` on background thread, then this will happen by design.

**Comment by xueyongwei** [comment]
> Didn't mean to offend you, sorry. On the @acecilia issue you've said that it's replaying the first element on the caller's thread, why does it still crash in my case if I have `skip(1)` there?

Codes shows that if current thread is not main,call FatalError. It has nothing to do with skip(1)
