### ISSUE TITLE
Why rx_text in UITextFields fires on beginEditing and EndEditing events, despite the text do not change?

### ISSUE THREAD

**Issue by acecilia** [ReactiveX/RxSwift#745]
I could not find an answer anywhere in the documentation or stackOverflow. I thought rx_text was called at subscription and when text changes only, but not on begin or end edition of the textField.

Thanks!

**Comment by kzaher** [comment]
Hi @acecilia ,

we've tried to made that behavior as best as we could, but unfortunately we can't make it perfect.

This was the narrowest set of events that we could find that detects all text changes.

There are problems with autocorrect changing text after text field looses focus, etc.

If you want to use only distinct values, please just add `distinctUntilChanged` operator. We can't add it inside of control property because of control value validations (there is issue somewhere in this repo that explains this).

If there is some better way that covers all of the cases, we can always try to improve this, but as far as I'm aware of, there isn't any guarantee in the documentation that these extensions will only return distinct values.

This behavior so far hasn't been a problem for me.

¯\\\_(ツ)\_/¯

**Comment by acecilia** [comment]
Great to know, thank you very much :)
