### ISSUE TITLE
Two-way binding in a separated project inside the RxSwiftCommunity repo?

### ISSUE THREAD

**Issue by acecilia** [ReactiveX/RxSwift#771]
Would it be interesting to put the two-way binding operator in a separated project inside RxSwiftCommunity repo?
(I find myself right now copying the code from [https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Operators.swift](https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Operators.swift) inside my own project)

Thank you very much :)

**Comment by kzaher** [comment]
Hi @acecilia ,

This is similar to #731

We just need somebody to create a project in RxSwiftCommunity with a sexy name, and help us maintain it :)

Send us your best suggestions for names, let's vote for name. We need some contributor to help us maintain it, setup CocoaPods, Carthage integration, readme full of gifs and reasonable tests.

So far we have bindings and activity indicator to distribute using it.

Unsure about the name. Lot of different things in one repo sounds like utilities, which sounds, ugh ... extensions maybe describe this better?
Since Rx already means reactive extensions :), RxxCocoa :)? Sounds boring as hell to me.

As far as I'm concerned the repo can be called RxDaenerysSormborn :), we just need brave men to rule the repo now more then ever.

**Comment by acecilia** [comment]
Hey @kzaher : 
I have been working in the new repo stuff. Setting up a multiplatform project is a hell!!! I think I finally got something reasonable >> [here](https://github.com/acecilia/RxSwiftAddons) <<. I rewrote the twoWayBinding and introduced it in the project. My own cocoapods specs repo with the project is [here](https://github.com/acecilia/specs). If you have some time please check it and tell me what you think, im a newby in creating frameworks.

**Comment by kzaher** [comment]
Hi @acecilia ,

Sorry for not responding sooner, I've missed your response.

Looks great to me. I guess if you like, we can move this to RxSwiftCommunity and you can continue to work on it there.

I've sent you an invite to RxSwiftCommunity.

**Comment by acecilia** [comment]
Hi @kzaher!
Good to here that. Unfortunately right now I just moved to live to another country so I am really busy... Hope to have some spare time in two weeks (right now I am looking for a permanent place to stay, etc..), 
I will get back to you as soon as posible!

**Comment by kzaher** [comment]
Hi @acecilia ,

sure, take your time.

**Comment by kzaher** [comment]
If somebody will have time to do this great that would be awesome.

Since this is not an issue, let's close this for now. We can reopen this if somebody will have time to do this.

**Comment by solidcell** [comment]
@acecilia I created a project which is a good place to put stuff like this: https://github.com/RxSwiftCommunity/RxSwiftUtilities

If you want, you can submit your stuff as a PR to that.
