### ISSUE TITLE
Start looking at adding inline documentation 

### ISSUE THREAD

**Issue by orta** [ReactiveX/RxSwift#79]
This isn't an instantly actionable, but ideally it's going to be good to start pushing [this 1%](http://cocoadocs.org/docsets/RxSwift/1.9/Functions.html#/s:ZF7RxSwiftop1mU__FGOS_8RxResultQ__Q_) publicly documented upwards.

**Comment by bontoJR** [comment]
I agree! 👏

I think it would be great to use images like [RxMables](http://rxmarbles.com/) inside the documentation of operators.

**Comment by kzaher** [comment]
I think that is a fair point, I would like to add more inline documentation for sure, just the velocity of getting this thing was so large I didn't have resources to think about documenting it a lot.

I think we're now at a point where this is a reasonable thing to expect, so that is one of the top priorities on my todo list. 

I'll also update roadmap since it's pretty stale right now.

@bontoJR @orta 

Can you please present an example here of what would be awesome form, and acceptable form of documenting for example `map` :)

I was thinking of reusing `ReactiveX.io` documentation. Something like

```
/**
Transform the items emitted by an Observable by applying a function to each item
[marble diagram and more](http://reactivex.io/documentation/operators/map.html)
*/
public func map<E, R>
    (selector: E -> R)
    -> (Observable<E> -> Observable<R>)
```
First line is first sentence from their docs.

**Comment by bontoJR** [comment]
The link to ReactiveX's website is totally ok, but I would like to have more information about operators.
The inline documentation has a reason to exists and is very useful when a developer has already some insight in the library and/or is offline. The inline documentation should be the first instance to understand how a certain function works, further investigation online using the provided link is a good thing, but we need to give the basic information in the inline documentation.

@orta Do you have any stats about how ofter a documentation is visited in Cocoapods?

Anyway, I would skip in a first instance the documentation of internal methods and focus on, in order:

* Classes: definition of what a certain class is used for, ex: Observable, Disposable, etc...
* Operators: definition of what a certain operatore does, I would like to have diagrams in it, but wondering how it would look the documentation in offline mode.
* Public methods: documentation of methods used publicly

I think documentation of classes is a high priority requirement right now, it would be great to have the explanation of the role in every class that is publicly available, later focusing in operators. :)

Let me know what are your thoughts.
