### ISSUE TITLE
Issue or problem with understanding

### ISSUE THREAD

**Issue by nonameplum** [ReactiveX/RxSwift#818]
Hi,

I have this code:

```swift
        doRequestThatReturnsArray()
            .flatMap { $0.toObservable() }
            .filter { $0.organization.id == organizationId }
            .single()
            .flatMap { [weak self] (elem) -> Observable<Response> in
                // Why this code is called even single throws error MoreThanOneElement
                return self.doSomeRequest(elem)
            }
            .subscribe(
                onNext: { print($0)},
                onError: { print($0) }, // Here will be printed "Sequence contains more than one element."
                onCompleted: nil, 
                onDisposed: nil)
            .addDisposableTo(disposeBag)
```

I wonder why code inside `flatMap` is called even `.single()` throws error when `filter` returns more than one element?

**Comment by kzaher** [comment]
Hi,

this is one of the unit tests

```swift
func testSinglePredicate_Many() {
        let scheduler = TestScheduler(initialClock: 0)
        
        let xs = scheduler.createHotObservable([
            next(150, 1),
            next(210, 2),
            next(220, 3),
            next(230, 4),
            next(240, 5),
            completed(250)
            ])
        
        let res = scheduler.start {
            xs.single() { e in
                return (e % 2) == 1
            }
        }
        
        XCTAssertEqual(res.events, [
            next(220, 3),
            error(240, RxError.moreThanOneElement)
            ])
        
        XCTAssertEqual(xs.subscriptions, [
            Subscription(200, 240)
            ])
    }
```

If there are other Rx implementations that behave differently please let us know, so we can make this more consistent in future.

**Comment by nonameplum** [comment]
So I my understanding of the event propagation in Rx was probably wrong :)
I also don't clearly understand how to deal correctly with this behaviour. Because `doSomeRequest` can for example doing `.POST` request to create something on the backed but which should be avoided if earlier some error occured.

Also I played a bit with RxSwift playground and created some thing like this:

```swift
    Observable.of(
        "🐱", "🐰", "🐶",
        "🐸", "🐱", "🐰",
        "🐹", "🐸", "🐱")
        .map { (elem) -> String in
            print("map1 " + elem)
            if elem == "🐶" {
                throw RxError.Unknown
            }
            return elem + " :)"
        }
        .map {
            print("map2 " + $0)
            return $0.characters.count
        }
        .subscribe(
            onNext: { print("#next -> ", $0) },
            onError: { print("# error -> ", $0) },
            onCompleted: { print("# completed") },
            onDisposed: { print("# disposed") })
        .addDisposableTo(disposeBag)
```

This code prints:
```
map1 🐱
map2 🐱 :)
#next ->  4
map1 🐰
map2 🐰 :)
#next ->  4
map1 🐶
# error ->  Unknown error occured.
# disposed
map1 🐸
map2 🐸 :)
map1 🐱
map2 🐱 :)
map1 🐰
map2 🐰 :)
map1 🐹
map2 🐹 :)
map1 🐸
map2 🐸 :)
map1 🐱
map2 🐱 :)
```

Why map is still working in this case even it was disposed when error occured?
Sorry that I am asking second question but I think it is related to my main problem.

**Comment by kzaher** [comment]
Hi @nonameplum ,

Yeah, I understand why this is confusing :) The solution is quite simple.

```swift
Observable.of(
        "🐱", "🐰", "🐶",
        "🐸", "🐱", "🐰",
        "🐹", "🐸", "🐱", scheduler: CurrentThreadScheduler.instance) // using scheduler
        .map { (elem) -> String in
            print("map1 " + elem)
            if elem == "🐶" {
                throw RxError.Unknown
            }
            return elem + " :)"
        }
        .map {
            print("map2 " + $0)
            return $0.characters.count
        }
        .subscribe(
            onNext: { print("#next -> ", $0) },
            onError: { print("# error -> ", $0) },
            onCompleted: { print("# completed") },
            onDisposed: { print("# disposed") })
        .addDisposableTo(disposeBag)
```

The main problem was not using scheduler for element production. We'll can consider making this default behavior for RxSwift 3.0, and never allow generating elements immediately for collections without a scheduler.

**Note that the final callbacks (#next, #error) did fire correct number of times.**

Sincerely, first I really wanted to make the system as performant as possible because I really didn't want to paint myself into a corner and provide with escape hatches in case there were some performance issues.

But since after really heavy use I didn't notice any issues, I think we can maybe changing some default policies to be more conservative.

The reason why this was allowed in RxSwift 2.0 was because in 99.99% of cases there isn't a need to be able to cancel production of **finite sequences of elements**, only forwarding them to observers. You can just let them to complete on their own. I believe that statistically that will burn less CPU then always using scheduling, but the difference isn't that big.

In the end, we've passed that choice on the user:

**Element production cancellation possible because of using a scheduler**: 
```swift
Observable.of(
        "🐱", "🐰", "🐶",
        "🐸", "🐱", "🐰",
        "🐹", "🐸", "🐱", scheduler: CurrentThreadScheduler.instance)
```
**Element production cancellation not possible, but it you don't need it, it's slightly more performant**:
```swift
Observable.of(
        "🐱", "🐰", "🐶",
        "🐸", "🐱", "🐰",
        "🐹", "🐸", "🐱")
```

Please also note that if there wasn't a map, map combo, but some other operator like filter

```
Observable.of(
    "🐱", "🐰", "🐶",
    "🐸", "🐱", "🐰",
    "🐹", "🐸", "🐱")
    .map { (elem) -> String in
        print("map1 " + elem)
        if elem == "🐶" {
            throw RxError.Unknown
        }
        return elem + " :)"
    }
    .filter {
        print("filter " + $0)
        return true
    }
    .subscribe(
        onNext: { print("#next -> ", $0) },
        onError: { print("# error -> ", $0) },
        onCompleted: { print("# completed") },
        onDisposed: { print("# disposed") })
    .addDisposableTo(disposeBag)
```

... then only first lambda would fire.

The reason why that is the case is because of `map` operator optimizations. 
If we notice there are n consecutive `map` operators one behind the other, then we internally convert them to one `map` operator that has a lambda that is a composition of their mapping lambdas, which is kind of nice since we save ~(n-1)/n percent of allocations and ~(n-1)/2n percent of stack calls :)

So in your example, those 2 map operators are internally converted into one with composition of their lambdas :)

**Comment by nonameplum** [comment]
Huh, I appreciate your great explanation 👍 
It seems to be reasonable approach that you picked.

I'm only a bit confused because of error propagation. I was used to Promise behaviour that when error occurred then it skip all chaining method to error handler if exist.

I was expecting this in case of `single()` or any other like with my second example with `map` that throws an error so it could skip all methods to probably `subscribe error` handler if exists.

Can I achieve something similar in current implementation?

**Comment by kzaher** [comment]
> I wonder why code inside flatMap is called even .single() throws error when filter returns more than one element?

I would say because single first propagates an element like unit tests explains that triggers flatMap and then sends error when it encounters second element.

**Comment by kzaher** [comment]
> I was expecting this in case of single() or any other like with my second example with map that throws an error so it could skip all methods to probably subscribe error handler if exists.

As far as I can tell, it does behave this way. There was only some confusion because scheduler wasn't used to generate elements.

**Comment by kzaher** [comment]
This should be improved now in `swift-3.0` branch.
