### ISSUE TITLE
Adds "deprecated" annotations for `rx.something` to `rx_something` transition.

### ISSUE THREAD

**Issue by JegnuX** [ReactiveX/RxSwift#841]
Following issue #826 and PR #832, I was wondering if we shouldn't keep `rx_something`syntax, and forward calls to `rx.something` syntax, and add `@deprecated( )` annotations.

It seems that this was done to almost all changes in the `swift-3.0` branch, so I guess it must be done for those changes as well ?

**Comment by kzaher** [comment]
Hi @JegnuX ,

Ideally yes, but I think that it wouldn't be too practical to add them in every possible case.

We'll prominently add that change on top of the release notes for the following release, so there shouldn't be to hard to figure out what needs to be done.

The only exception IMHO where I think it would be useful to add those `@deprecated( )` annotations are UITableView and UICollectionView extensions, since they are by far the most complex ones.

**Comment by kzaher** [comment]
I've add deprecated api warnings to table and collection view extensions. I think we are ok for now. If you have any other suggestions, feel free to make a PR.
