### ISSUE TITLE
The root subscribing will be unsubscribed even when onError is called from any level.

### ISSUE THREAD

**Issue by RyogaK** [ReactiveX/RxSwift#849]
*Short description*:

  The top level subscribing will be unsubscribed when onError is fired from any level.

*Self contained code example that reproduces the issue*:

  I can reproduce on this repo.
  https://github.com/tailec/boilerplate
  And also, I can reproduce that with just RxSwift 2.6.0. I can't do that with RxSwift 2.5.0 or earlier.

*Xcode version*:

  Version 7.3.1 (7D1014)

*Expected outcome*:

  Should continuously subscribing even after onError called.

*What actually happens*:

  If I failed to sign-in once, I can no longer run signing-in process because the subscribing from `rx_tap` is already unsubscribed.

*Installation method*:

  * CocoaPods (1.0.0)

*I have multiple versions of Xcode installed*:

  * no

*Level of RxSwift knowledge*:

  * I have a small code base

**Comment by kzaher** [comment]
Hi @RyogaK ,

If you are talking about this code https://github.com/tailec/boilerplate/blob/cb80a8a167b0389690c704596e028d3203053f09/github/github/View%20Models/LoginViewModel.swift#L37 , I believe that code contains a bug.

`.asDriver(onErrorJustReturn: LoginResult.Failed(message: "Oops, something went wrong")).debug()` that has `catchError` operator inside it is being used too late.

It or just `catchError` operator should be used inside `flatMapLatest`, somewhere around here https://github.com/tailec/boilerplate/blob/cb80a8a167b0389690c704596e028d3203053f09/github/github/View%20Models/LoginViewModel.swift#L44 

A lot of examples how to use `Driver` or `catchError` are contained inside RxExample app inside this repo, so you can use that as a reference.

> If I failed to sign-in once, I can no longer run signing-in process because the subscribing from rx_tap is already unsubscribed.

According to this code, that is expected behavior. That follows from sequence grammar. Sequence grammar is alpha and omega as far as Rx is concerned :) Once you send an error that means that sequence needs to be terminated.

**Comment by RyogaK** [comment]
I see. That's I'm not schooled.
This repo has no problem about this :)
Thanks a lot.
