### ISSUE TITLE
How to organize state with scan if new state could be obtained only as Observable?

### ISSUE THREAD

**Issue by rehsals** [ReactiveX/RxSwift#851]
Hi! I have a question and need some advice.
I have a `tableView` and use `RxCocoa` with `RxDataSources` to handle it.
I want to follow the pattern from [Example3_TableViewEditing](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example3_TableViewEditing.swift)
But my problem is that my `execute` method returns `Observable<SectionedTableViewState>` since in order to create new model I should perform some async work and wait for result. I can't figure out how to structure my `Observable` chain to make this work.

**Comment by kzaher** [comment]
Hi @rehsals ,

I think it would probably make sense to try to add into [RxSwiftExt](https://github.com/RxSwiftCommunity/RxSwiftExt) project a version of `scan` operator that is a hybrid between `scan` and `flatMapLatest`.

I'm not sure is there some other obvious solution.

I'll try to open an issue there. I think I can implement it also since I often need similar operator.

**Comment by rehsals** [comment]
Thanks for your feedback. My level of confidence with ReactiveX does not allow me to implement this myself yet but I get your idea. Would be handy to have such operator indeed. I guess I close this issue   here if it suits RxSwiftExt project better.
