### ISSUE TITLE
Carthage builds useless schema

### ISSUE THREAD

**Issue by serluca** [ReactiveX/RxSwift#859]
**Short description of the issue**:
Carthage builds useless schema making the carthage build time even longer ( up to 7 minutes when building iOs platform only on my mac )

**Xcode version**:

```
  Xcode 7.3
```

**Expected outcome**:

```
*** Building scheme "RxCocoa-iOS" in Rx.xcworkspace
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
```

**What actually happens**:

```
*** Building scheme "RxTests-iOS" in Rx.xcworkspace
*** Building scheme "RxBlocking-iOS" in Rx.xcworkspace
*** Building scheme "RxCocoa-iOS" in Rx.xcworkspace
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
```

**Installation method**:
  - [ ] CocoaPods
  - [x] Carthage
  - [ ] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [ ] yes (which ones)
  - [x] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by kzaher** [comment]
Hi @serluca ,

I'm not sure Carthage has any feature that enables selecting schemes. 

I agree that building RxSwift using Carthage is excruciating slow. On the other hand, I don't think it should matter because we create a new release once a month. So building something once a month that takes 7 min isn't really horrible IMHO :)

I understand that when you do `carthage update` it rebuilds all dependencies no matter have they changed or not, but I would identify that as the main issue.

We can perform a simple thought experiment. 

Let's say you do carthage update once a week (and that's probably pessimistic view because you do it more often then that), and we improve build time by 50%, to 3.5 min.
In a month, you'll spend ~15.2 min waiting for it to build vs 7 min a month if carthage were to implement caching. And this calculation doesn't even consider savings because of recursive dependencies.

I think this will become better with time.
* when Swift will reach ABI stability we'll be able to publish frameworks
* or Carthage will be improved
     * not rebuilding dependencies that weren't modified
     * being able to reuse once built dependencies (e.g. if RxSwift is already built with Carthage as a dependency, then if one includes RxDataSources as a dependency -> that has RxSwift as a dependency, and RxSwift has already been built, then reuse built dependency, don't build it again)

I'm assuming maybe Carthage team is also waiting for ABI stability to implement those features, but really have no idea.

**Comment by serluca** [comment]
HI @kzaher 

Thanks for the reply let's hope swift will reach the ABI stability asap and the build time gets improved.

**Comment by DianQK** [comment]
Hi~ @serluca 

What about try this command:

```
carthage update --verbose --platform ios --color auto
```

**Comment by BernardGatt** [comment]
Created a PR that should solve this issue.

https://github.com/ReactiveX/RxSwift/pull/861

**Comment by kzaher** [comment]
I think there is a bunch of low hanging fruit on Carthage side. I'm sure somebody will pick it :)

Since I don't think we can tackle this in this repo. Let's close this for now.
