### ISSUE TITLE
Any hint on the performance impact on using RxSwift?

### ISSUE THREAD

**Issue by shuoli84** [ReactiveX/RxSwift#86]
I just wondering how far we can push the lib to. And I mean runtime performance for RxSwift vs handwriting error prone code. :)

**Comment by kzaher** [comment]
This is a really hard question to answer. You can use every tool in a wrong way.

In normal usages it could actually increase the performance of your system for some scenarios regarding canceling of unnecessary work.

Rx is meant to be used as a composition tool. If granularity is rational, then I don't think it could cause performance issues.

So far we've done what ever was possible on architecture level to optimize the system. We are using all of the architecture optimization tricks that original Rx team has made. They've done an amazing job there.

There are still some micro level optimizations regarding replacing spin locks with compare and swap instructions that are possible, but it didn't have time to research how to use atomic swaps of arc references in swift, so I've just used spin locks so far.
I also know areas where we unnecessary pass observer array by value, and thus creating copies, when we could be using the same immutable references again.

I didn't have time to really push optimizations because there wasn't a need for that so far, but there is room for sure.

I think that probably biggest price on performance are NSRecursiveLocks that are used for operators that merge multiple sequences.
Those locks aren't necessary with operators that operate on single sequences because of sequence semantics (map, filter, take .... don't have them)

I would like to define some reasonable test cases so we can further benchmark the system. 

What I've done long time ago was setup an example that uses rx pretty heavily, and see how it will behave. It looks pretty fine to me.

We are planning to push that performance further in future by using type system tricks to prove statically properties about sequences that would allow using totally lockless versions of operators safely (without those NSRecursiveLocks).

DispatchQueueSchedulers and timing operators are pretty generic, but they are also smart. In case they detect usage of dispatch queue schedulers, they will optimize `observeOn` to `dispatch_async`.

If you are using `observeOn` with `MainScheduler` and sequence callback is already executing on main thread, it will just execute it without `dispatch_*`.

If you can help me make some benchmarks regarding throughput of operators and get some concrete measurements, I would really appreciate that. 

When we have some concrete measurements, then we can better understand where further optimizations need to happen.

As far as for writing hand written error prone code, I don't think you'll gain much. Bottlenecks have a weird property of appearing in totally unexpected places. I see this happening all the time :) You can only get better at guessing where they will happen :)

I am interested very much if somebody has any performance issues with using this project, so let me know if that happens.

**Comment by shuoli84** [comment]
Thanks for the lengthy and informative reply :) 

```
If granularity is rational, then I don't think it could cause performance issues.
```

The rational granularity is something I am interested, I will write some testing code to test the throughput. Will come back when something interesting happened.

**Comment by bontoJR** [comment]
No input since a month.
Looking forward to hear your results @shuoli84. :+1:

In the meantime I will close this, if you have any further input, please re-open this issue. :)
