### ISSUE TITLE
all/every operator implementation

### ISSUE THREAD

**Issue by Czajnikowski** [ReactiveX/RxSwift#867]
*Short description of missing functionality*:

I want this library to implement `all`/`every` operator.

*Short code example of how you would like to use the API*:

[Here's how it works](http://reactivex.io/documentation/operators/all.html)

*The reason why I need this functionality*:

I actually don't necessarily need it 😉 

*So why am I wasting your time?*

I'm currently learning RxSwift/Rx and I have figured out that this operator is (probably) missing in current implementation. I believe learning by doing is a good idea, so implementing it will probably give me loads of understanding on how RxSwift works deep down, and it will allow me to make my first step in open source 😅 

I've had already a [brief chat](https://rxswift.slack.com/archives/contributing/p1473266312000003) with @fpillet on a Slack, and he suggested that it might be plausible to implement it in the RxSwiftExt repo.

What do you think?

**Comment by kzaher** [comment]
Hi @Czajnikowski ,

Thnx for reaching out. 

I have a pretty simple way of deciding should we include something in this repo or not. If we find that functionality is useful enough for us to maintain it forever and ship it with every app out there that uses this library, then we'll include it, otherwise we won't :)

Unfortunately, at the moment it doesn't seem to me that these operators fulfill those criteria.

Having said that, I don't think that anything I've said stops you from learning Rx internals and implementing those operators yourself.

I think there are plenty of ways how one can get involved and I'm sure you'll find something that is interesting enough for you.
