### ISSUE TITLE
How to bind value with an elegant way in Swift3?

### ISSUE THREAD

**Issue by linqingmo** [ReactiveX/RxSwift#875]
When I use RxCocoa I found a  change from Swift2 to Swift3.
In Swift2:
```swift
let textObservable: Observable<String>
textObservable.bindTo(label.rx_text)
```
It's OK. But In Swift3:
```swift
let textObservable: Observable<String>
textObservable.bindTo(label.rx.text)
```
It fails. Because type `AnyObserver<String>` cannot covert to type `AnyObserver<String?>`.
So how to bind value in a better way?

```swift
textObservable
    .map({ $0 })
    .bindTo(label.rx.text)
```
or
```swift
fileprivate func _optional<T>(_ element: T) -> T? {
    return Optional(element)
}

extension ObservableType {
    public func optional() -> Observable<E?> {
        return map(_optional)
    }
}
```

**Comment by kzaher** [comment]
Hi @linqingmo ,

yeah, I think both solutions are valid, we were trying to make rx wrapper types more consistent with underlying types.

I think both solutions you've proposed are valid. Or you can just create your extension 

```swift
extension Reactive where Base: UILabel {
    
    /**
    Bindable sink for `text` property.
    */
    public var textValue: AnyObserver<String> { // or some other name
        return UIBindingObserver(UIElement: self.base) { label, text in
            label.text = text
        }.asObserver()
    }
}
```

Probably the most elegant solution would be to have something like

```swift
extension Reactive where Base: UILabel {
    
    /**
    Bindable sink for `text` property.
    */
    public var text: AnyObserver<CustomStringConvertible> { // or some other name
        return UIBindingObserver(UIElement: self.base) { label, text in
            label.text = text.description
        }.asObserver()
    }
}
```

but the problem is that we can't make optional string conforming to this as far as I'm aware of. This can't be written

```swift
extension Optional where Wrapped == String : CustomStringConvertible {
.....
}
```

... so not sure is there a more elegant way to express this API.

**Comment by jonlambert** [comment]
@linqingmo did you find another solution for this?

**Comment by linqingmo** [comment]
@jonlambert Sorry, no idea. I have no idea why
```swift
let a: Observable<String?> = Observable<String>
```
is invalid.
