### ISSUE TITLE
Add subscribeResult(_:) subscription method

### ISSUE THREAD

**Issue by dev4dev** [ReactiveX/RxSwift#933]
*Short description of missing functionality*:

It's more convenient way to handle success and error in one block using *switch* statement. The same as in ReactiveSwift.

*Short code example of how you would like to use the API*:

```swift
viewModel.loadNextPage().subscribeResult { [unowned self] result in
			APESuperHUD.removeHUD(animated: true, presentingView: self.view, completion: nil)
			switch result {
			case .success(let locations):
				// handle result
			case .failure(let error):
				// handle error
			}
		}.addDisposableTo(trash)
```

*The reason why I need this functionality*:

  Because it's a better way to do this

*Code I have right now*:

```swift
viewModel.loadNextPage().subscribe { [unowned self] event in
			APESuperHUD.removeHUD(animated: true, presentingView: self.view, completion: nil)
			switch event {
			case .next(let locations):
				// handle result
			case .error(let error):
				// handle error
			case .completed:
				break  // *why do I need this here???*
			}
		}.addDisposableTo(trash)
```

**Comment by dev4dev** [comment]
Test implementation

```swift
public enum Result<T> {
	case success(T)
	case failure(Swift.Error)
}

```

```swift
public func subscribeResult(onResult: @escaping (Result<E>) -> Void)
		-> Disposable {

			let disposable =  Disposables.create()

			let observer = AnonymousObserver<E> { e in
				switch e {
				case .next(let value):
					onResult(.success(value))
				case .error(let e):
					onResult(.failure(e))
					disposable.dispose()
				case .completed:
					disposable.dispose()
				}
			}
			return Disposables.create(
				self.subscribeSafe(observer),
				disposable
			)
	}
```

**Comment by kzaher** [comment]
Hi @dev4dev ,

We've previously had `Result` in public interface of RxSwift 1.x. The reason why it was there was because Swift didn't have any built in error handling mechanism and we had no other choice.

I can understand your motivation, but I don't think it's in this library domain to define `Result` enum.

Because there are so many different ways people can define or import Result and combine it with this library I think it's far simpler and clearer to just leave those choices for this library users.

**Comment by dangthaison91** [comment]
@dev4dev You can try Action in RxSwiftCommunity.
