### ISSUE TITLE
Should Driver automatically be .distinctUntilChanged() 

### ISSUE THREAD

**Issue by MadsBogeskov** [ReactiveX/RxSwift#958]
**Short description of the issue**:
Since the Driver type is mostly used to bind items to UI components, it would make sense to limit the amount of updates.

**Expected outcome**:
If I bind a driver to a UI component I would like it not to push the same item to the UI and thereby force it to update. The right operator to include on the Driver would be `.distinctUntilChanged()`.

**What actually happens**:
It will update the UI for each item in the sequence

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
- [ ] just starting
- [ ] I have a small code base
- [X ] I have a significant code base

**Comment by AndrewSB** [comment]
Chiming in: I'm using Drivers to represent sequences that can't error, as well as to bind to UI components. I believe some of my code depends on the repeated `.next` events

**Comment by kzaher** [comment]
Hi @MadsBogeskov ,

I think `Driver` is just what it is :)

```
    - it never fails
    - it delivers events on `MainScheduler.instance`
    - `shareReplayLatestWhileConnected()` behavior
        - all observers share sequence computation resources
        - it's stateful, upon subscription (calling subscribe) last element is immediately replayed if it was produced
        - computation of elements is reference counted with respect to the number of observers
        - if there are no subscribers, it will release sequence computation resources
```

Although it's mostly used to update UI components, it doesn't have to be.

I think that using `distinctUntilChanged` should be explicit because it creates internal state that user doesn't have control over.

We've had some issues before when using them in ControlProperty.

That change would also require for driver to work only on elements that are equatable, which is serious limitation IMHO.

**Comment by MadsBogeskov** [comment]
True, which makes sense. Thanks for the clarification.
