### ISSUE TITLE
Question: Merge observables with limiting the number of concurrent

### ISSUE THREAD

**Issue by ngocluu** [ReactiveX/RxSwift#977]
I have a root observable:

```
struct Item {
  let id: Int
}

func start() -> Observable<Item> {
  return Observable.create { o in
    ...
    o.onNext(item1)
    o.onNext(item2)
    o.onNext(item3)
    o.onCompleted()
    return Disposables.create()
  }
}
```

`start` observable can emit zero or more items. I want to perform an HTTP request on each emitted item:

```
func request(item: Item) -> Observable<Item> {
  let req = Observable.create { o in
    Manager.request('someurl').response {
      o.onNext(item1)
      o.onNext(item2)
      o.onNext(item3)
      o.onCompleted()
    }
    return Disposables.create()
  }
  return req.map {
    request($0)
  }.concat()
}
```

`request` observable can emit zero or more other child items and perform `request` on each one.

The following code works well:

```
let final = start().map {
  request($0)
}.concat()
```

But it performs only 1 request at a time. I want to perform max of 3 concurrent requests at a time.

This code does not work, if `start` emits only one item, only one request is performed at a time:

```
let final = start().map {
  request($0)
}.merge(maxConcurrent: 3)
```

And this code also, since 9 requests can be performed at the same time:

```
func request(item: Item) -> Observable<Item> {
  let req = Observable.create { ... }
  return req.map {
    request($0)
  }.merge(maxConcurrent: 3)
}

let final = start().map {
  request($0)
}.merge(maxConcurrent: 3)
```

There are any way to perform max of 3 concurrent requests at a time, regardless the item is emitted from `start` or inner `request`s?

**Comment by kzaher** [comment]
Hi @ngocluu ,

If CPU was bottleneck you could just create operation queue scheduler and limit number of concurrent operations.

It seems to me that you want a more generic solution where you can throttle the max number of concurrent observable sequence subscriptions.

You can create your own operator that performs that kind of throttling with internals similar to those of `merge(maxConcurrent:)` operator, so you would be able to do:

```
let throttlingResource = ThrottlingResource(maxConcurrent: 3) // you would need to extract 
// internals of merge operator yourself
func request(item: Item) -> Observable<Item> {
  let req = Observable.create { o in
    Manager.request('someurl').response {
      o.onNext(item1)
      o.onNext(item2)
      o.onNext(item3)
      o.onCompleted()
    }
    return Disposables.create()
  }.throttle(throttlingResource)
}
```

I never needed something like this because I would usually use something built on top of NSURLSession, and it already has `HTTPMaximumConnectionsPerHost` property http://stackoverflow.com/questions/20888841/set-number-of-concurrent-downloads-with-nsurlsessiondownloadtask.

**Comment by kzaher** [comment]
Unsure what can we do more here.
